const AseviyeCumleler = [
{eng:"I like apples.", tr:"Elma severim."},
{eng:"He is my friend.", tr:"O benim arkadaşım."},
{eng:"She is happy.", tr:"O mutlu."},
{eng:"We go to school.", tr:"Okula gideriz."},
{eng:"I have a dog.", tr:"Bir köpeğim var."},
{eng:"The sun is hot.", tr:"Güneş sıcak."},
{eng:"I eat bread.", tr:"Ekmek yerim."},
{eng:"They are tired.", tr:"Onlar yorgun."},
{eng:"He has a car.", tr:"Bir arabası var."},
{eng:"I am a student.", tr:"Ben öğrenciyim."},
{eng:"She likes music.", tr:"Müziği sever."},
{eng:"We play football.", tr:"Futbol oynarız."},
{eng:"It is cold today.", tr:"Bugün hava soğuk."},
{eng:"I can swim.", tr:"Yüzebilirim."},
{eng:"They are my parents.", tr:"Onlar benim ebeveynim."},
{eng:"I usually wake up at seven.", tr:"Genellikle yedide uyanırım."},
{eng:"She often goes to the market.", tr:"Sık sık markete gider."},
{eng:"He likes to read books in the evening.", tr:"Akşamları kitap okumayı sever."},
{eng:"We are going to the park this afternoon.", tr:"Bu öğleden sonra parka gidiyoruz."},
{eng:"I have never been to Paris.", tr:"Hiç Paris'e gitmedim."},
{eng:"She is learning to cook Italian food.", tr:"İtalyan yemeği yapmayı öğreniyor."},
{eng:"He does not like watching TV.", tr:"TV izlemeyi sevmez."},
{eng:"They usually eat breakfast at eight o'clock.", tr:"Genellikle kahvaltıyı sekizde yaparlar."},
{eng:"I want to buy a new phone.", tr:"Yeni bir telefon almak istiyorum."},
{eng:"She goes to school by bus every day.", tr:"Her gün okula otobüsle gider."},
{eng:"We have been friends for two years.", tr:"İki yıldır arkadaşız."},
{eng:"He is very good at playing chess.", tr:"Satrançta çok iyidir."},
{eng:"I sometimes forget my keys.", tr:"Bazen anahtarlarımı unuturum."},
{eng:"She will visit her grandparents next week.", tr:"Gelecek hafta büyükannelerini ziyaret edecek."},
{eng:"They are going to watch a movie tonight.", tr:"Bu gece film izleyecekler."},
{eng:"I like pizza.", tr:"Pizza severim."},
{eng:"He is reading a book.", tr:"O kitap okuyor."},
{eng:"She drinks water every day.", tr:"Her gün su içer."},
{eng:"We go to the park on Sundays.", tr:"Pazar günleri parka gideriz."},
{eng:"I have a brother.", tr:"Bir erkek kardeşim var."},
{eng:"The dog is black.", tr:"Köpek siyah."},
{eng:"I eat rice for dinner.", tr:"Akşam yemeğinde pirinç yerim."},
{eng:"They are playing outside.", tr:"Dışarıda oynuyorlar."},
{eng:"He has a new bike.", tr:"Yeni bir bisikleti var."},
{eng:"I am happy today.", tr:"Bugün mutluyum."},
{eng:"She likes to sing.", tr:"Şarkı söylemeyi sever."},
{eng:"We play in the garden.", tr:"Bahçede oynarız."},
{eng:"It is sunny now.", tr:"Şu anda güneşli."},
{eng:"I can ride a bike.", tr:"Bisiklet sürebilirim."},
{eng:"They are my friends.", tr:"Onlar benim arkadaşlarım."},
{eng:"I usually eat breakfast at eight.", tr:"Genellikle kahvaltıyı sekizde yerim."},
{eng:"She sometimes goes shopping.", tr:"Bazen alışverişe gider."},
{eng:"He always drinks tea.", tr:"Her zaman çay içer."},
{eng:"We rarely go to the cinema.", tr:"Nadiren sinemaya gideriz."},
{eng:"I often read books.", tr:"Sık sık kitap okurum."},
{eng:"She hardly ever watches TV.", tr:"Neredeyse hiç TV izlemez."},
{eng:"He frequently plays football.", tr:"Sık sık futbol oynar."},
{eng:"We occasionally visit our cousins.", tr:"Zaman zaman kuzenlerimizi ziyaret ederiz."},
{eng:"Turn left at the corner.", tr:"Köşede sola dön."},
{eng:"Go straight and then turn right.", tr:"Düz git sonra sağa dön."},
{eng:"Take the second street on the left.", tr:"Soldaki ikinci sokağa gir."},
{eng:"The post office is next to the school.", tr:"Postane okulun yanında."},
{eng:"Walk past the bank and turn left.", tr:"Bankanın önünden geç ve sola dön."},
{eng:"The hotel is opposite the park.", tr:"Otel parkın karşısında."},
{eng:"It is about ten minutes on foot.", tr:"Yürüyerek yaklaşık on dakika."},
{eng:"Take the bus number twelve.", tr:"On iki numaralı otobüse bin."},
{eng:"Get off at the third stop.", tr:"Üçüncü durağa inin."},
{eng:"The station is at the end of this road.", tr:"İstasyon bu yolun sonunda."},
{eng:"I would like a table for two.", tr:"İki kişilik bir masa istiyorum."},
{eng:"What do you recommend?", tr:"Ne tavsiye edersiniz?"},
{eng:"I have a headache.", tr:"Başım ağrıyor."},
{eng:"She is reading a magazine.", tr:"Bir dergi okuyor."},
{eng:"He goes to work by bus.", tr:"İşe otobüsle gider."},
{eng:"We are watching TV now.", tr:"Şu anda TV izliyoruz."},
{eng:"I like to drink coffee.", tr:"Kahve içmeyi severim."},
{eng:"She is very tired.", tr:"O çok yorgun."},
{eng:"He has two sisters.", tr:"İki kız kardeşi var."},
{eng:"We go shopping on Saturdays.", tr:"Cumartesi günleri alışverişe gideriz."},
{eng:"I want to eat ice cream.", tr:"Dondurma yemek istiyorum."},
{eng:"She can speak English.", tr:"İngilizce konuşabilir."},
{eng:"He is playing football.", tr:"Futbol oynuyor."},
{eng:"They live in a big house.", tr:"Büyük bir evde yaşıyorlar."},
{eng:"I am learning English.", tr:"İngilizce öğreniyorum."},
{eng:"She likes to draw pictures.", tr:"Resim yapmayı sever."},
{eng:"We go to the park in the afternoon.", tr:"Öğleden sonra parka gideriz."},
{eng:"I have a small garden.", tr:"Küçük bir bahçem var."},
{eng:"He is drinking water.", tr:"Su içiyor."},
{eng:"She often listens to music.", tr:"Sık sık müzik dinler."},
{eng:"We are eating lunch now.", tr:"Şu anda öğle yemeği yiyoruz."},
{eng:"I usually read books before bed.", tr:"Genellikle yatmadan önce kitap okurum."},
{eng:"He sometimes plays basketball.", tr:"Bazen basketbol oynar."},
{eng:"She never eats meat.", tr:"Hiç et yemez."},
{eng:"We often go to the beach.", tr:"Sık sık sahile gideriz."},
{eng:"I like my new shoes.", tr:"Yeni ayakkabılarımı seviyorum."},
{eng:"He is studying for the test.", tr:"Test için çalışıyor."},
{eng:"She goes to the library every week.", tr:"Her hafta kütüphaneye gider."},
{eng:"We are cleaning the house.", tr:"Evi temizliyoruz."},
{eng:"I have a red car.", tr:"Kırmızı bir arabam var."},
{eng:"He is very tall.", tr:"O çok uzun boylu."},
{eng:"She is wearing a blue dress.", tr:"Mavi bir elbise giymiş."},
{eng:"We go to the cinema on Fridays.", tr:"Cuma günleri sinemaya gideriz."},
{eng:"I sometimes eat pizza.", tr:"Bazen pizza yerim."},
{eng:"He likes to play computer games.", tr:"Bilgisayar oyunu oynamayı sever."},
{eng:"She is happy today.", tr:"Bugün mutlu."},
{eng:"We are waiting for the bus.", tr:"Otobüsü bekliyoruz."},
{eng:"I need a pen.", tr:"Bir kaleme ihtiyacım var."},
{eng:"He is my teacher.", tr:"O benim öğretmenim."},
{eng:"She has a new bag.", tr:"Yeni bir çantası var."},
{eng:"We are going to the market.", tr:"Markete gidiyoruz."},
{eng:"I like chocolate.", tr:"Çikolatayı severim."},
{eng:"He is eating an apple.", tr:"Bir elma yiyor."},
{eng:"She can dance very well.", tr:"Çok iyi dans edebilir."},
{eng:"We go to the park every day.", tr:"Her gün parka gideriz."},
{eng:"I often drink tea.", tr:"Sık sık çay içerim."},
{eng:"He usually wakes up at six.", tr:"Genellikle altıda uyanır."},
{eng:"She is listening to music.", tr:"Müzik dinliyor."},
{eng:"We like to swim in summer.", tr:"Yazın yüzmeyi severiz."},
{eng:"I sometimes go to the cinema.", tr:"Bazen sinemaya giderim."},
{eng:"He is reading a newspaper.", tr:"Gazete okuyor."},
{eng:"She likes to cook.", tr:"Yemek yapmayı sever."},
{eng:"We are playing in the garden.", tr:"Bahçede oynuyoruz."},
{eng:"I have two cats.", tr:"İki kedim var."},
{eng:"He goes to school by car.", tr:"Okula arabayla gider."},
{eng:"She is very kind.", tr:"O çok nazik."},
{eng:"We usually have dinner at seven.", tr:"Genellikle yedide akşam yemeği yeriz."},
{eng:"I like reading books.", tr:"Kitap okumayı severim."},
{eng:"He often goes swimming.", tr:"Sık sık yüzmeye gider."},
{eng:"She is writing a letter.", tr:"Bir mektup yazıyor."},
{eng:"We are having lunch now.", tr:"Şu anda öğle yemeği yiyoruz."},
{eng:"I need some water.", tr:"Biraz suya ihtiyacım var."},
{eng:"He likes coffee.", tr:"Kahveyi sever."},
{eng:"She goes to work every day.", tr:"Her gün işe gider."},
{eng:"We are studying English.", tr:"İngilizce çalışıyoruz."},
{eng:"I sometimes go to the park.", tr:"Bazen parka giderim."},
{eng:"He has a new phone.", tr:"Yeni bir telefonu var."},
{eng:"She is wearing a hat.", tr:"Şapka takmış."},
{eng:"We like to play football.", tr:"Futbol oynamayı severiz."},
{eng:"I usually drink milk.", tr:"Genellikle süt içerim."},
{eng:"He often plays football.", tr:"Sık sık futbol oynar."},
{eng:"She sometimes sings.", tr:"Bazen şarkı söyler."},
{eng:"We are walking to school.", tr:"Okula yürüyoruz."},
{eng:"I have a small dog.", tr:"Küçük bir köpeğim var."},
{eng:"He is very friendly.", tr:"O çok arkadaş canlısı."},
{eng:"She likes to swim.", tr:"Yüzmeyi sever."},
{eng:"We usually go shopping on Sundays.", tr:"Genellikle Pazar günleri alışverişe gideriz."},
{eng:"I am drinking juice.", tr:"Meyve suyu içiyorum."},
{eng:"He is watching TV.", tr:"TV izliyor."},
{eng:"She has two brothers.", tr:"İki erkek kardeşi var."},
{eng:"We like ice cream.", tr:"Dondurmayı severiz."},
{eng:"I usually eat breakfast at seven.", tr:"Genellikle yedide kahvaltı yaparım."},
{eng:"He goes to the park every morning.", tr:"Her sabah parka gider."},
{eng:"She sometimes eats pasta.", tr:"Bazen makarna yer."},
{eng:"We are listening to the teacher.", tr:"Öğretmeni dinliyoruz."},
{eng:"I like swimming.", tr:"Yüzmeyi severim."},
{eng:"He is my brother.", tr:"O benim kardeşim."},
{eng:"She has a red dress.", tr:"Kırmızı bir elbisesi var."},
{eng:"We sometimes go to the cinema.", tr:"Bazen sinemaya gideriz."},
{eng:"I am very tired today.", tr:"Bugün çok yorgunum."},
{eng:"He likes to play the guitar.", tr:"Gitar çalmayı sever."},
{eng:"She is reading a story.", tr:"Bir hikaye okuyor."},
{eng:"We go to the library on Fridays.", tr:"Cuma günleri kütüphaneye gideriz."},
{eng:"I need a new bag.", tr:"Yeni bir çantaya ihtiyacım var."},
{eng:"He often drinks water.", tr:"Sık sık su içer."},
{eng:"She is very beautiful.", tr:"O çok güzel."},
{eng:"We like to walk in the park.", tr:"Parkta yürümeyi severiz."},
{eng:"I usually play football.", tr:"Genellikle futbol oynarım."},
{eng:"He sometimes watches TV.", tr:"Bazen TV izler."},
{eng:"She has a blue bag.", tr:"Mavi bir çantası var."},
{eng:"We are going to the shop.", tr:"Dükkâna gidiyoruz."},
{eng:"I like cats.", tr:"Kedileri severim."},
{eng:"He is learning English.", tr:"İngilizce öğreniyor."},
{eng:"She sometimes goes to the market.", tr:"Bazen markete gider."},
{eng:"We usually have lunch at twelve.", tr:"Genellikle öğle yemeğini on ikide yeriz."},
{eng:"I am very happy.", tr:"Çok mutluyum."},
{eng:"He likes swimming.", tr:"Yüzmeyi sever."},
{eng:"She is my sister.", tr:"O benim kız kardeşim."},
{eng:"We go to school every day.", tr:"Her gün okula gideriz."},
{eng:"I sometimes drink tea.", tr:"Bazen çay içerim."},
{eng:"He is reading a book now.", tr:"Şu anda bir kitap okuyor."},
{eng:"She likes to play football.", tr:"Futbol oynamayı sever."},
{eng:"We are cleaning the garden.", tr:"Bahçeyi temizliyoruz."},
{eng:"I like apples.", tr:"Elma severim."},
{eng:"He is cooking dinner.", tr:"Akşam yemeği pişiriyor."},
{eng:"She goes to the park in the morning.", tr:"Sabahları parka gider."},
{eng:"We are watching a movie now.", tr:"Şu anda film izliyoruz."},
{eng:"I have a new phone.", tr:"Yeni bir telefonum var."},
{eng:"He sometimes eats pizza.", tr:"Bazen pizza yer."},
{eng:"She is listening to the radio.", tr:"Radyo dinliyor."},
{eng:"We go to school by bus.", tr:"Okula otobüsle gideriz."},
{eng:"I like to draw.", tr:"Resim yapmayı severim."},
{eng:"He is reading a newspaper.", tr:"Gazete okuyor."},
{eng:"She likes chocolate.", tr:"Çikolatayı sever."},
{eng:"We are playing football.", tr:"Futbol oynuyoruz."},
{eng:"I sometimes go swimming.", tr:"Bazen yüzmeye giderim."},
{eng:"He has a cat.", tr:"Bir kedisi var."},
{eng:"She is very kind.", tr:"O çok nazik."},
{eng:"We usually wake up early.", tr:"Genellikle erken uyanırız."},
{eng:"I like to listen to music.", tr:"Müzik dinlemeyi severim."},
{eng:"He goes to the market on Sundays.", tr:"Pazar günleri markete gider."},
{eng:"She is reading a story now.", tr:"Şu anda bir hikaye okuyor."},
{eng:"We have dinner at six.", tr:"Altıda akşam yemeği yeriz."},
{eng:"I sometimes watch TV.", tr:"Bazen TV izlerim."},
{eng:"He is playing the guitar.", tr:"Gitar çalıyor."},
{eng:"She likes to run in the morning.", tr:"Sabahları koşmayı sever."},
{eng:"We are walking to the park.", tr:"Parkta yürüyoruz."},
{eng:"I have two brothers.", tr:"İki erkek kardeşim var."},
{eng:"He likes to read books.", tr:"Kitap okumayı sever."},
{eng:"She is very tired today.", tr:"Bugün çok yorgun."},
{eng:"We go to the library every week.", tr:"Her hafta kütüphaneye gideriz."},
{eng:"I like swimming in the sea.", tr:"Denizde yüzmeyi severim."},
{eng:"He is eating breakfast now.", tr:"Şu anda kahvaltı yapıyor."},
{eng:"She sometimes drinks coffee.", tr:"Bazen kahve içer."},
{eng:"We are cleaning the house.", tr:"Evi temizliyoruz."},
{eng:"I have a small garden.", tr:"Küçük bir bahçem var."},
{eng:"He is very friendly.", tr:"O çok arkadaş canlısı."},
{eng:"She goes to work by car.", tr:"İşe arabayla gider."},
{eng:"We like to eat ice cream.", tr:"Dondurma yemeyi severiz."},
{eng:"I usually drink water.", tr:"Genellikle su içerim."},
{eng:"He sometimes plays basketball.", tr:"Bazen basketbol oynar."},
{eng:"She is listening to music now.", tr:"Şu anda müzik dinliyor."},
{eng:"We go shopping on Saturdays.", tr:"Cumartesi günleri alışverişe gideriz."},
{eng:"I like to eat pasta.", tr:"Makarna yemeyi severim."},
{eng:"He is very tall.", tr:"O çok uzun."},
{eng:"She has a new dress.", tr:"Yeni bir elbisesi var."},
{eng:"We are playing in the garden.", tr:"Bahçede oynuyoruz."},
{eng:"I sometimes go to the cinema.", tr:"Bazen sinemaya giderim."},
{eng:"He likes coffee very much.", tr:"Kahveyi çok sever."},
{eng:"She is my sister.", tr:"O benim kız kardeşim."},
{eng:"We usually eat breakfast at seven.", tr:"Genellikle yedide kahvaltı yaparız."},
{eng:"I like cats and dogs.", tr:"Kedi ve köpeği severim."},
{eng:"He is reading a book.", tr:"Bir kitap okuyor."},
{eng:"She likes to dance.", tr:"Dans etmeyi sever."},
{eng:"We are going to the market.", tr:"Markete gidiyoruz."},
{eng:"I sometimes eat pizza.", tr:"Bazen pizza yerim."},
{eng:"He is learning English now.", tr:"Şu anda İngilizce öğreniyor."},
{eng:"She is very beautiful.", tr:"O çok güzel."},
{eng:"We go to school every day.", tr:"Her gün okula gideriz."},
{eng:"I like to play football.", tr:"Futbol oynamayı severim."},
{eng:"He sometimes watches TV.", tr:"Bazen TV izler."},
{eng:"She has a blue bag.", tr:"Mavi bir çantası var."},
{eng:"We like to walk in the park.", tr:"Parkta yürümeyi severiz."},
{eng:"I usually play football.", tr:"Genellikle futbol oynarım."},
{eng:"He sometimes drinks water.", tr:"Bazen su içer."},
{eng:"She likes swimming.", tr:"Yüzmeyi sever."},
{eng:"We go to the cinema on Fridays.", tr:"Cuma günleri sinemaya gideriz."},
{eng:"I have a small dog.", tr:"Küçük bir köpeğim var."},
{eng:"He is very kind.", tr:"O çok nazik."},
{eng:"She is listening to the radio.", tr:"Radyo dinliyor."},
{eng:"We usually go shopping on Sundays.", tr:"Genellikle Pazar günleri alışverişe gideriz."},
{eng:"I like chocolate.", tr:"Çikolatayı severim."},
{eng:"He goes to the park every morning.", tr:"Her sabah parka gider."},
{eng:"She sometimes eats pasta.", tr:"Bazen makarna yer."},
{eng:"We are listening to the teacher.", tr:"Öğretmeni dinliyoruz."},
{eng:"I like swimming.", tr:"Yüzmeyi severim."},
{eng:"He is my brother.", tr:"O benim kardeşim."},
{eng:"She has a red dress.", tr:"Kırmızı bir elbisesi var."},
{eng:"We sometimes go to the cinema.", tr:"Bazen sinemaya gideriz."},
{eng:"I am very happy.", tr:"Çok mutluyum."},
{eng:"He likes swimming.", tr:"Yüzmeyi sever."},
{eng:"She is my sister.", tr:"O benim kız kardeşim."},
{eng:"We go to school every day.", tr:"Her gün okula gideriz."},
{eng:"I sometimes drink tea.", tr:"Bazen çay içerim."},
{eng:"He is reading a book now.", tr:"Şu anda bir kitap okuyor."},
{eng:"She likes to play football.", tr:"Futbol oynamayı sever."},
{eng:"We are cleaning the garden.", tr:"Bahçeyi temizliyoruz."},
{eng:"I need some milk.", tr:"Biraz süte ihtiyacım var."},
{eng:"He is cooking lunch.", tr:"Öğle yemeği pişiriyor."},
{eng:"She sometimes goes to the park.", tr:"Bazen parka gider."},
{eng:"We are walking to school now.", tr:"Şu anda okula yürüyoruz."},
{eng:"I like dogs.", tr:"Köpekleri severim."},
{eng:"He is learning French.", tr:"Fransızca öğreniyor."},
{eng:"She likes to sing.", tr:"Şarkı söylemeyi sever."},
{eng:"We go to the library on Mondays.", tr:"Pazartesi günleri kütüphaneye gideriz."},
{eng:"I usually have breakfast at eight.", tr:"Genellikle sekizde kahvaltı yaparım."},
{eng:"He likes apples and bananas.", tr:"Elma ve muz sever."},
{eng:"She is drinking water.", tr:"Su içiyor."},
{eng:"We go to the park every weekend.", tr:"Her hafta sonu parka gideriz."},
{eng:"I sometimes eat ice cream.", tr:"Bazen dondurma yerim."},
{eng:"He is very friendly.", tr:"O çok arkadaş canlısı."},
{eng:"She has two cats.", tr:"İki kedisi var."},
{eng:"We are learning English.", tr:"İngilizce öğreniyoruz."},
{eng:"I like to play games.", tr:"Oyun oynamayı severim."},
{eng:"He is reading a story.", tr:"Bir hikaye okuyor."},
{eng:"She sometimes drinks juice.", tr:"Bazen meyve suyu içer."},
{eng:"We usually wake up early.", tr:"Genellikle erken uyanırız."},
{eng:"I like to eat vegetables.", tr:"Sebze yemeyi severim."},
{eng:"He is cooking dinner now.", tr:"Şu anda akşam yemeği pişiriyor."},
{eng:"She likes to watch TV.", tr:"TV izlemeyi sever."},
{eng:"We go to school by bike.", tr:"Okula bisikletle gideriz."},
{eng:"I have a red pen.", tr:"Kırmızı bir kalemim var."},
{eng:"He sometimes plays football.", tr:"Bazen futbol oynar."},
{eng:"She is very happy.", tr:"O çok mutlu."},
{eng:"We are going shopping now.", tr:"Şu anda alışverişe gidiyoruz."},
{eng:"I like swimming in the pool.", tr:"Havuzda yüzmeyi severim."},
{eng:"He has a new book.", tr:"Yeni bir kitabı var."},
{eng:"She is my friend.", tr:"O benim arkadaşım."},
{eng:"We usually eat lunch at twelve.", tr:"Genellikle on ikide öğle yemeği yeriz."},
{eng:"I like to read books.", tr:"Kitap okumayı severim."},
{eng:"He sometimes drinks tea.", tr:"Bazen çay içer."},
{eng:"She is learning to play the piano.", tr:"Piyano çalmayı öğreniyor."},
{eng:"We are cleaning our room.", tr:"Odamızı temizliyoruz."},
{eng:"I have a small car.", tr:"Küçük bir arabam var."},
{eng:"He is very tall.", tr:"O çok uzun."},
{eng:"She likes to draw pictures.", tr:"Resim yapmayı sever."},
{eng:"We go to the cinema on Fridays.", tr:"Cuma günleri sinemaya gideriz."},
{eng:"I sometimes go to the park.", tr:"Bazen parka giderim."},
{eng:"He likes to ride his bike.", tr:"Bisiklet sürmeyi sever."},
{eng:"She is reading a newspaper.", tr:"Gazete okuyor."},
{eng:"We are playing basketball.", tr:"Basketbol oynuyoruz."},
{eng:"I like chocolate very much.", tr:"Çikolatayı çok severim."},
{eng:"He is learning Spanish.", tr:"İspanyolca öğreniyor."},
{eng:"She has a blue bag.", tr:"Mavi bir çantası var."},
{eng:"We usually go to the beach in summer.", tr:"Yazın genellikle sahile gideriz."},
{eng:"I like to eat pizza.", tr:"Pizza yemeyi severim."},
{eng:"He sometimes watches movies.", tr:"Bazen film izler."},
{eng:"She is very kind.", tr:"O çok nazik."},
{eng:"We are walking to the school.", tr:"Okula yürüyoruz."},
{eng:"I have a dog.", tr:"Bir köpeğim var."},
{eng:"He likes to swim.", tr:"Yüzmeyi sever."},
{eng:"She sometimes plays football.", tr:"Bazen futbol oynar."},
{eng:"We go to the library on Mondays.", tr:"Pazartesi günleri kütüphaneye gideriz."},
{eng:"I like to eat fruit.", tr:"Meyve yemeyi severim."},
{eng:"He is very clever.", tr:"O çok zeki."},
{eng:"She is listening to the teacher.", tr:"Öğretmeni dinliyor."},
{eng:"We usually wake up at seven.", tr:"Genellikle yedide uyanırız."},
{eng:"I sometimes drink milk.", tr:"Bazen süt içerim."},
{eng:"He likes to play chess.", tr:"Satranç oynamayı sever."},
{eng:"She is reading a book now.", tr:"Şu anda kitap okuyor."},
{eng:"We are playing in the garden.", tr:"Bahçede oynuyoruz."},
{eng:"I have a small house.", tr:"Küçük bir evim var."},
{eng:"He is very happy today.", tr:"Bugün çok mutlu."},
{eng:"She likes singing.", tr:"Şarkı söylemeyi sever."},
{eng:"We go to school every morning.", tr:"Her sabah okula gideriz."},
{eng:"I like dogs and cats.", tr:"Köpek ve kedileri severim."},
{eng:"He is reading a story now.", tr:"Şu anda bir hikaye okuyor."},
{eng:"She sometimes drinks water.", tr:"Bazen su içer."},
{eng:"We are watching TV.", tr:"TV izliyoruz."},
{eng:"I have a big bag.", tr:"Büyük bir çantam var."},
{eng:"He likes apples.", tr:"Elma sever."},
{eng:"She is very friendly.", tr:"O çok arkadaş canlısı."},
{eng:"We usually go shopping on Sundays.", tr:"Genellikle Pazar günleri alışverişe gideriz."},
{eng:"I like chocolate and candy.", tr:"Çikolata ve şekerlemeyi severim."},
{eng:"He sometimes eats ice cream.", tr:"Bazen dondurma yer."},
{eng:"She has a red pen.", tr:"Kırmızı bir kalemi var."},
{eng:"We go to the park in the afternoon.", tr:"Öğleden sonra parka gideriz."},
{eng:"I like to play football in the evening.", tr:"Akşamları futbol oynamayı severim."},
{eng:"He is very busy today.", tr:"Bugün çok meşgul."},
{eng:"She sometimes goes swimming.", tr:"Bazen yüzmeye gider."},
{eng:"We are listening to music.", tr:"Müzik dinliyoruz."},
{eng:"I have a new bag.", tr:"Yeni bir çantam var."},
{eng:"He likes reading books.", tr:"Kitap okumayı sever."},
{eng:"She is my best friend.", tr:"O benim en iyi arkadaşım."},
{eng:"We usually have lunch at twelve.", tr:"Genellikle on ikide öğle yemeği yeriz."},
{eng:"I like to draw pictures.", tr:"Resim yapmayı severim."},
{eng:"He sometimes drinks coffee.", tr:"Bazen kahve içer."},
{eng:"She is learning English.", tr:"İngilizce öğreniyor."},
{eng:"We are cleaning our house.", tr:"Evimizi temizliyoruz."},
{eng:"I have a small bike.", tr:"Küçük bir bisikletim var."},
{eng:"He is very kind.", tr:"O çok nazik."},
{eng:"She likes to dance.", tr:"Dans etmeyi sever."},
{eng:"We go to the cinema on Fridays.", tr:"Cuma günleri sinemaya gideriz."},
{eng:"I sometimes go to the park.", tr:"Bazen parka giderim."},
{eng:"He likes to ride his bike.", tr:"Bisiklet sürmeyi sever."},
{eng:"She is reading a newspaper.", tr:"Gazete okuyor."},
{eng:"We are playing basketball.", tr:"Basketbol oynuyoruz."},
{eng:"I like chocolate very much.", tr:"Çikolatayı çok severim."},
{eng:"He is learning Spanish.", tr:"İspanyolca öğreniyor."},
{eng:"She has a blue bag.", tr:"Mavi bir çantası var."},
{eng:"We usually go to the beach in summer.", tr:"Yazın genellikle sahile gideriz."},
{eng:"I like to eat pizza.", tr:"Pizza yemeyi severim."},
{eng:"He sometimes watches movies.", tr:"Bazen film izler."},
{eng:"She is very kind.", tr:"O çok nazik."},
{eng:"I like sunny days.", tr:"Güneşli günleri severim."},
{eng:"He goes to the gym every morning.", tr:"Her sabah spor salonuna gider."},
{eng:"She is wearing a red dress.", tr:"Kırmızı bir elbise giymiş."},
{eng:"We have dinner at seven.", tr:"Yedide akşam yemeği yeriz."},
{eng:"I usually drink tea in the morning.", tr:"Genellikle sabahları çay içerim."},
{eng:"He is listening to a song.", tr:"Bir şarkı dinliyor."},
{eng:"She sometimes goes to the library.", tr:"Bazen kütüphaneye gider."},
{eng:"We are waiting for the bus.", tr:"Otobüsü bekliyoruz."},
{eng:"I have a new phone.", tr:"Yeni bir telefonum var."},
{eng:"He likes to draw pictures.", tr:"Resim yapmayı sever."},
{eng:"She is very tired today.", tr:"Bugün çok yorgun."},
{eng:"We go shopping on Saturdays.", tr:"Cumartesi günleri alışverişe gideriz."},
{eng:"I like reading books.", tr:"Kitap okumayı severim."},
{eng:"He sometimes plays basketball.", tr:"Bazen basketbol oynar."},
{eng:"She is cooking dinner now.", tr:"Şu anda akşam yemeği pişiriyor."},
{eng:"We usually wake up at six.", tr:"Genellikle altıda uyanırız."},
{eng:"I like listening to music.", tr:"Müzik dinlemeyi severim."},
{eng:"He has two sisters.", tr:"İki kız kardeşi var."},
{eng:"She is very smart.", tr:"O çok zeki."},
{eng:"We are having lunch together.", tr:"Birlikte öğle yemeği yiyoruz."},
{eng:"I sometimes eat fast food.", tr:"Bazen hızlı yemek yerim."},
{eng:"He likes swimming in the pool.", tr:"Havuzda yüzmeyi sever."},
{eng:"She is reading a magazine.", tr:"Bir dergi okuyor."},
{eng:"We go to the park in the morning.", tr:"Sabahları parka gideriz."},
{eng:"I have a small dog.", tr:"Küçük bir köpeğim var."},
{eng:"He is very polite.", tr:"O çok kibar."},
{eng:"She likes to play the piano.", tr:"Piyano çalmayı sever."},
{eng:"We usually study in the evening.", tr:"Genellikle akşamları çalışırız."},
{eng:"I like eating ice cream.", tr:"Dondurma yemeyi severim."},
{eng:"He sometimes drinks juice.", tr:"Bazen meyve suyu içer."},
{eng:"She is learning French.", tr:"Fransızca öğreniyor."},
{eng:"We are cleaning the house now.", tr:"Şu anda evi temizliyoruz."},
{eng:"I have a new bag.", tr:"Yeni bir çantam var."},
{eng:"He likes playing football.", tr:"Futbol oynamayı sever."},
{eng:"She is very happy today.", tr:"Bugün çok mutlu."},
{eng:"We go to school every day.", tr:"Her gün okula gideriz."},
{eng:"I sometimes watch TV.", tr:"Bazen TV izlerim."},
{eng:"He likes reading stories.", tr:"Hikaye okumayı sever."},
{eng:"She is wearing a blue jacket.", tr:"Mavi bir ceket giymiş."},
{eng:"We usually go to bed at ten.", tr:"Genellikle onda yatarız."},
{eng:"I like playing games.", tr:"Oyun oynamayı severim."},
{eng:"He sometimes eats pizza.", tr:"Bazen pizza yer."},
{eng:"She is very kind to everyone.", tr:"Herkese karşı çok nazik."},
{eng:"We are walking to the park.", tr:"Parkta yürüyoruz."},
{eng:"I have two brothers.", tr:"İki erkek kardeşim var."},
{eng:"He likes sunny weather.", tr:"Güneşli havayı sever."},
{eng:"She is reading a book in the garden.", tr:"Bahçede kitap okuyor."},
{eng:"We usually have breakfast at eight.", tr:"Genellikle sekizde kahvaltı yaparız."},
{eng:"I like drinking water.", tr:"Su içmeyi severim."},
{eng:"He sometimes goes to the cinema.", tr:"Bazen sinemaya gider."},
{eng:"She is very friendly to children.", tr:"Çocuklara karşı çok arkadaş canlısı."},
{eng:"We are playing football now.", tr:"Şu anda futbol oynuyoruz."},{eng:"I usually go to bed at eleven.", tr:"Genellikle on birde yatarım."},
{eng:"He likes reading newspapers.", tr:"Gazete okumayı sever."},
{eng:"She is listening to the radio.", tr:"Radyo dinliyor."},
{eng:"We sometimes go swimming.", tr:"Bazen yüzmeye gideriz."},
{eng:"I have a black cat.", tr:"Siyah bir kedim var."},
{eng:"He is very friendly.", tr:"O çok arkadaş canlısı."},
{eng:"She likes drawing pictures.", tr:"Resim yapmayı sever."},
{eng:"We are going to the shop.", tr:"Dükkâna gidiyoruz."},
{eng:"I sometimes play the guitar.", tr:"Bazen gitar çalarım."},
{eng:"He likes drinking tea.", tr:"Çay içmeyi sever."},
{eng:"She is wearing a hat.", tr:"Şapka takıyor."},
{eng:"We usually eat dinner at seven.", tr:"Genellikle yedide akşam yemeği yeriz."},
{eng:"I have a new bicycle.", tr:"Yeni bir bisikletim var."},
{eng:"He sometimes rides his bike.", tr:"Bazen bisiklet sürer."},
{eng:"She likes eating chocolate.", tr:"Çikolata yemeyi sever."},
{eng:"We are cleaning our room.", tr:"Odamızı temizliyoruz."},
{eng:"I usually drink coffee in the morning.", tr:"Genellikle sabahları kahve içerim."},
{eng:"He is very clever.", tr:"O çok akıllı."},
{eng:"She sometimes goes to the park.", tr:"Bazen parka gider."},
{eng:"We are reading a story.", tr:"Bir hikaye okuyoruz."},
{eng:"I have a small fish.", tr:"Küçük bir balığım var."},
{eng:"He likes to run in the morning.", tr:"Sabahları koşmayı sever."},
{eng:"She is very polite.", tr:"O çok kibar."},
{eng:"We usually meet on Sundays.", tr:"Genellikle Pazar günleri buluşuruz."},
{eng:"I sometimes go to the market.", tr:"Bazen pazara giderim."},
{eng:"He likes to watch cartoons.", tr:"Çizgi film izlemeyi sever."},
{eng:"She is learning English now.", tr:"Şu anda İngilizce öğreniyor."},
{eng:"We are having breakfast now.", tr:"Şu anda kahvaltı yapıyoruz."},
{eng:"I have two pens.", tr:"İki kalemim var."},
{eng:"He is very careful.", tr:"O çok dikkatli."},
{eng:"She sometimes drinks milk.", tr:"Bazen süt içer."},
{eng:"We go to the cinema on Fridays.", tr:"Cuma günleri sinemaya gideriz."},
{eng:"I like eating fruits.", tr:"Meyve yemeyi severim."},
{eng:"He sometimes watches football on TV.", tr:"Bazen televizyonda futbol izler."},
{eng:"She is very happy today.", tr:"Bugün çok mutlu."},
{eng:"We are learning new words.", tr:"Yeni kelimeler öğreniyoruz."},
{eng:"I have a blue bag.", tr:"Mavi bir çantam var."},
{eng:"He likes listening to music.", tr:"Müzik dinlemeyi sever."},
{eng:"She sometimes goes shopping.", tr:"Bazen alışverişe gider."},
{eng:"We usually play games in the evening.", tr:"Genellikle akşamları oyun oynarız."},
{eng:"I sometimes ride my scooter.", tr:"Bazen scooter sürerim."},
{eng:"He is very strong.", tr:"O çok güçlü."},
{eng:"She likes to dance.", tr:"Dans etmeyi sever."},
{eng:"We are visiting our friends.", tr:"Arkadaşlarımızı ziyaret ediyoruz."},
{eng:"I have a green notebook.", tr:"Yeşil bir defterim var."},
{eng:"He sometimes eats sandwiches.", tr:"Bazen sandviç yer."},
{eng:"She is very kind.", tr:"O çok nazik."},
{eng:"We go to school by bus.", tr:"Okula otobüsle gideriz."},
{eng:"I like sunny weather.", tr:"Güneşli havayı severim."},
{eng:"He sometimes rides the train.", tr:"Bazen trenle gider."},
{eng:"She is wearing glasses.", tr:"Gözlük takıyor."},
{eng:"We usually have lunch at one.", tr:"Genellikle birde öğle yemeği yeriz."},
{eng:"I sometimes watch movies.", tr:"Bazen film izlerim."}
];