const BseviyeCumleler = [
{eng:"I work every day.",tr:"Her gün çalışırım."},
{eng:"I usually wake up early.",tr:"Genelde erken uyanırım."},
{eng:"I go to work by bus.",tr:"İşe otobüsle giderim."},
{eng:"I drink coffee in the morning.",tr:"Sabah kahve içerim."},
{eng:"I read the news every day.",tr:"Her gün haber okurum."},
{eng:"I like learning new things.",tr:"Yeni şeyler öğrenmeyi severim."},
{eng:"I study English every evening.",tr:"Her akşam İngilizce çalışırım."},
{eng:"I sometimes watch TV.",tr:"Bazen televizyon izlerim."},
{eng:"I often listen to music.",tr:"Sık sık müzik dinlerim."},
{eng:"I walk to the park.",tr:"Parka yürürüm."},
{eng:"I meet my friends on weekends.",tr:"Hafta sonları arkadaşlarımla buluşurum."},
{eng:"I like spending time with my family.",tr:"Ailemle vakit geçirmeyi severim."},
{eng:"I cook dinner at home.",tr:"Evde akşam yemeği yaparım."},
{eng:"I buy food at the supermarket.",tr:"Süpermarketten yiyecek alırım."},
{eng:"I try to eat healthy food.",tr:"Sağlıklı yemek yemeye çalışırım."},
{eng:"I drink a lot of water.",tr:"Çok su içerim."},
{eng:"I like traveling to new places.",tr:"Yeni yerlere seyahat etmeyi severim."},
{eng:"I want to improve my English.",tr:"İngilizcemi geliştirmek istiyorum."},
{eng:"I practice English with my friends.",tr:"Arkadaşlarımla İngilizce pratik yaparım."},
{eng:"I watch movies in English.",tr:"Filmleri İngilizce izlerim."},
{eng:"I read English books.",tr:"İngilizce kitap okurum."},
{eng:"I try to speak English every day.",tr:"Her gün İngilizce konuşmaya çalışırım."},
{eng:"I make many mistakes.",tr:"Birçok hata yaparım."},
{eng:"I learn from my mistakes.",tr:"Hatalarımdan öğrenirim."},
{eng:"I feel happy today.",tr:"Bugün mutlu hissediyorum."},
{eng:"I feel tired after work.",tr:"İşten sonra yorgun hissederim."},
{eng:"I feel excited about the future.",tr:"Gelecek hakkında heyecanlı hissediyorum."},
{eng:"I feel nervous sometimes.",tr:"Bazen gergin hissederim."},
{eng:"I think this idea is good.",tr:"Bu fikrin iyi olduğunu düşünüyorum."},
{eng:"I believe you.",tr:"Sana inanıyorum."},
{eng:"I understand the problem.",tr:"Problemi anlıyorum."},
{eng:"I remember that day.",tr:"O günü hatırlıyorum."},
{eng:"I forget things sometimes.",tr:"Bazen şeyleri unuturum."},
{eng:"I need some help.",tr:"Biraz yardıma ihtiyacım var."},
{eng:"I need more time.",tr:"Daha fazla zamana ihtiyacım var."},
{eng:"I need to finish this work.",tr:"Bu işi bitirmem gerekiyor."},
{eng:"I want to go home.",tr:"Eve gitmek istiyorum."},
{eng:"I want to learn more.",tr:"Daha fazla öğrenmek istiyorum."},
{eng:"I want to travel abroad.",tr:"Yurt dışına seyahat etmek istiyorum."},
{eng:"I want to buy a new phone.",tr:"Yeni bir telefon almak istiyorum."},
{eng:"I plan to study tonight.",tr:"Bu gece ders çalışmayı planlıyorum."},
{eng:"I plan to travel next year.",tr:"Seneye seyahat etmeyi planlıyorum."},
{eng:"I will call you later.",tr:"Seni sonra arayacağım."},
{eng:"I will send you a message.",tr:"Sana mesaj göndereceğim."},
{eng:"I will finish this tomorrow.",tr:"Bunu yarın bitireceğim."},
{eng:"I will help you.",tr:"Sana yardım edeceğim."},
{eng:"I will explain everything.",tr:"Her şeyi açıklayacağım."},
{eng:"I will wait here.",tr:"Burada bekleyeceğim."},
{eng:"I will come back soon.",tr:"Yakında geri döneceğim."},
{eng:"I will start now.",tr:"Şimdi başlayacağım."},
{eng:"I will try again.",tr:"Tekrar deneyeceğim."},
{eng:"I will never forget this.",tr:"Bunu asla unutmayacağım."},
{eng:"I can help you.",tr:"Sana yardım edebilirim."},
{eng:"I can explain this.",tr:"Bunu açıklayabilirim."},
{eng:"I can understand English.",tr:"İngilizce anlayabilirim."},
{eng:"I can speak a little English.",tr:"Biraz İngilizce konuşabilirim."},
{eng:"I can solve this problem.",tr:"Bu problemi çözebilirim."},
{eng:"I can finish this today.",tr:"Bunu bugün bitirebilirim."},
{eng:"I cannot find my phone.",tr:"Telefonumu bulamıyorum."},
{eng:"I cannot remember his name.",tr:"Onun adını hatırlayamıyorum."},
{eng:"I cannot open this file.",tr:"Bu dosyayı açamıyorum."},
{eng:"I cannot understand this question.",tr:"Bu soruyu anlayamıyorum."},
{eng:"I should study more.",tr:"Daha fazla ders çalışmalıyım."},
{eng:"I should sleep earlier.",tr:"Daha erken uyumalıyım."},
{eng:"I should exercise more.",tr:"Daha fazla egzersiz yapmalıyım."},
{eng:"I should eat healthy food.",tr:"Sağlıklı yemek yemeliyim."},
{eng:"I must finish this today.",tr:"Bunu bugün bitirmeliyim."},
{eng:"I must go now.",tr:"Şimdi gitmeliyim."},
{eng:"I must call my friend.",tr:"Arkadaşımı aramalıyım."},
{eng:"I must be careful.",tr:"Dikkatli olmalıyım."},
{eng:"I have a lot of work.",tr:"Çok işim var."},
{eng:"I have many friends.",tr:"Birçok arkadaşım var."},
{eng:"I have a question.",tr:"Bir sorum var."},
{eng:"I have an idea.",tr:"Bir fikrim var."},
{eng:"I have some free time.",tr:"Biraz boş zamanım var."},
{eng:"I have a meeting today.",tr:"Bugün bir toplantım var."},
{eng:"I have a problem.",tr:"Bir problemim var."},
{eng:"I have a solution.",tr:"Bir çözümüm var."},
{eng:"I have good news.",tr:"İyi haberim var."},
{eng:"I have bad news.",tr:"Kötü haberim var."},
{eng:"I had a busy day.",tr:"Yoğun bir gün geçirdim."},
{eng:"I had a great time.",tr:"Harika vakit geçirdim."},
{eng:"I had an interesting conversation.",tr:"İlginç bir konuşma yaptım."},
{eng:"I had a strange dream.",tr:"Garip bir rüya gördüm."},
{eng:"I had dinner with my family.",tr:"Ailemle akşam yemeği yedim."},
{eng:"I had coffee with a friend.",tr:"Bir arkadaşımla kahve içtim."},
{eng:"I saw him yesterday.",tr:"Onu dün gördüm."},
{eng:"I saw a beautiful place.",tr:"Güzel bir yer gördüm."},
{eng:"I saw an interesting movie.",tr:"İlginç bir film izledim."},
{eng:"I saw something strange.",tr:"Garip bir şey gördüm."},
{eng:"I met a new friend.",tr:"Yeni bir arkadaşla tanıştım."},
{eng:"I met him last week.",tr:"Onunla geçen hafta tanıştım."},
{eng:"I met her at the cafe.",tr:"Onunla kafede tanıştım."},
{eng:"I met many people there.",tr:"Orada birçok insanla tanıştım."},
{eng:"I learned something new.",tr:"Yeni bir şey öğrendim."},
{eng:"I learned a lot today.",tr:"Bugün çok şey öğrendim."},
{eng:"I learned English at school.",tr:"Okulda İngilizce öğrendim."},
{eng:"I learned this from a book.",tr:"Bunu bir kitaptan öğrendim."},
{eng:"I have been very busy lately.",tr:"Son zamanlarda çok meşguldüm."},
{eng:"I usually prefer coffee to tea.",tr:"Genelde çayı değil kahveyi tercih ederim."},
{eng:"I forgot to bring my phone.",tr:"Telefonumu getirmeyi unuttum."},
{eng:"I almost missed the bus.",tr:"Otobüsü neredeyse kaçırıyordum."},
{eng:"I managed to finish the work.",tr:"İşi bitirmeyi başardım."},
{eng:"I tried to explain the situation.",tr:"Durumu açıklamaya çalıştım."},
{eng:"I decided to change my plans.",tr:"Planlarımı değiştirmeye karar verdim."},
{eng:"I started learning English last year.",tr:"Geçen yıl İngilizce öğrenmeye başladım."},
{eng:"I stopped using that application.",tr:"O uygulamayı kullanmayı bıraktım."},
{eng:"I continued working despite the noise.",tr:"Gürültüye rağmen çalışmaya devam ettim."},
{eng:"I completely agree with you.",tr:"Seninle tamamen aynı fikirdeyim."},
{eng:"I strongly disagree with that idea.",tr:"O fikre kesinlikle katılmıyorum."},
{eng:"I clearly remember that moment.",tr:"O anı açıkça hatırlıyorum."},
{eng:"I barely understand this topic.",tr:"Bu konuyu zar zor anlıyorum."},
{eng:"I hardly ever watch television.",tr:"Neredeyse hiç televizyon izlemem."},
{eng:"I sometimes forget people's names.",tr:"Bazen insanların isimlerini unuturum."},
{eng:"I often think about the future.",tr:"Sık sık geleceği düşünürüm."},
{eng:"I rarely eat fast food.",tr:"Nadiren fast food yerim."},
{eng:"I usually wake up before sunrise.",tr:"Genelde gün doğmadan uyanırım."},
{eng:"I always try to stay positive.",tr:"Her zaman pozitif kalmaya çalışırım."},
{eng:"I never give up easily.",tr:"Kolay kolay pes etmem."},
{eng:"I would like to visit another country.",tr:"Başka bir ülkeyi ziyaret etmek isterim."},
{eng:"I would prefer staying at home tonight.",tr:"Bu gece evde kalmayı tercih ederim."},
{eng:"I would rather walk than take a taxi.",tr:"Taksiye binmektense yürümeyi tercih ederim."},
{eng:"I should probably leave now.",tr:"Muhtemelen artık gitmeliyim."},
{eng:"I might call you later.",tr:"Seni daha sonra arayabilirim."},
{eng:"I might forget about this.",tr:"Bunu unutabilirim."},
{eng:"I may visit my friend tomorrow.",tr:"Yarın arkadaşımı ziyaret edebilirim."},
{eng:"I must finish this report today.",tr:"Bu raporu bugün bitirmeliyim."},
{eng:"I must remember to call her.",tr:"Onu aramayı hatırlamalıyım."},
{eng:"I need to improve my skills.",tr:"Yeteneklerimi geliştirmem gerekiyor."},
{eng:"I need to focus on my work.",tr:"İşime odaklanmam gerekiyor."},
{eng:"I need to organize my schedule.",tr:"Programımı düzenlemem gerekiyor."},
{eng:"I want to achieve my goals.",tr:"Hedeflerime ulaşmak istiyorum."},
{eng:"I want to become more confident.",tr:"Daha özgüvenli olmak istiyorum."},
{eng:"I want to understand this better.",tr:"Bunu daha iyi anlamak istiyorum."},
{eng:"I want to develop new habits.",tr:"Yeni alışkanlıklar geliştirmek istiyorum."},
{eng:"I want to avoid unnecessary problems.",tr:"Gereksiz problemlerden kaçınmak istiyorum."},
{eng:"I plan to move to another city.",tr:"Başka bir şehre taşınmayı planlıyorum."},
{eng:"I plan to start a new project.",tr:"Yeni bir projeye başlamayı planlıyorum."},
{eng:"I plan to improve my health.",tr:"Sağlığımı geliştirmeyi planlıyorum."},
{eng:"I plan to learn another language.",tr:"Başka bir dil öğrenmeyi planlıyorum."},
{eng:"I hope everything goes well.",tr:"Umarım her şey iyi gider."},
{eng:"I hope to see you again.",tr:"Seni tekrar görmeyi umuyorum."},
{eng:"I hope you understand me.",tr:"Umarım beni anlarsın."},
{eng:"I expect the meeting to be long.",tr:"Toplantının uzun olmasını bekliyorum."},
{eng:"I expect things to change soon.",tr:"Yakında şeylerin değişmesini bekliyorum."},
{eng:"I believe this is possible.",tr:"Bunun mümkün olduğuna inanıyorum."},
{eng:"I believe we can solve this.",tr:"Bunu çözebileceğimize inanıyorum."},
{eng:"I guess he is busy today.",tr:"Sanırım bugün meşgul."},
{eng:"I guess she already knows.",tr:"Sanırım o zaten biliyor."},
{eng:"I guess this will work.",tr:"Sanırım bu işe yarayacak."},
{eng:"I think we should leave.",tr:"Bence gitmeliyiz."},
{eng:"I think this is a good idea.",tr:"Bence bu iyi bir fikir."},
{eng:"I think something is wrong.",tr:"Bir şeylerin yanlış olduğunu düşünüyorum."},
{eng:"I think you are right.",tr:"Bence haklısın."},
{eng:"I suppose he forgot.",tr:"Sanırım o unuttu."},
{eng:"I suppose this is normal.",tr:"Sanırım bu normal."},
{eng:"I noticed something strange.",tr:"Garip bir şey fark ettim."},
{eng:"I noticed that you were quiet.",tr:"Sessiz olduğunu fark ettim."},
{eng:"I realized my mistake.",tr:"Hatamı fark ettim."},
{eng:"I realized the truth.",tr:"Gerçeği fark ettim."},
{eng:"I suddenly remembered your name.",tr:"Birden adını hatırladım."},
{eng:"I suddenly felt nervous.",tr:"Birden gergin hissettim."},
{eng:"I felt relieved after the exam.",tr:"Sınavdan sonra rahatladım."},
{eng:"I felt proud of myself.",tr:"Kendimle gurur duydum."},
{eng:"I felt disappointed about the result.",tr:"Sonuçtan hayal kırıklığına uğradım."},
{eng:"I felt worried about the future.",tr:"Gelecek hakkında endişelendim."},
{eng:"I spent the whole day studying.",tr:"Bütün günü ders çalışarak geçirdim."},
{eng:"I spent a lot of money.",tr:"Çok para harcadım."},
{eng:"I spent some time thinking.",tr:"Biraz zaman düşünerek geçirdim."},
{eng:"I spent the evening with friends.",tr:"Akşamı arkadaşlarla geçirdim."},
{eng:"I learned a valuable lesson.",tr:"Değerli bir ders öğrendim."},
{eng:"I learned how to solve it.",tr:"Onu nasıl çözeceğimi öğrendim."},
{eng:"I learned something important.",tr:"Önemli bir şey öğrendim."},
{eng:"I improved my English skills.",tr:"İngilizce becerilerimi geliştirdim."},
{eng:"I improved my communication skills.",tr:"İletişim becerilerimi geliştirdim."},
{eng:"I improved my understanding.",tr:"Anlayışımı geliştirdim."},
{eng:"I changed my opinion.",tr:"Fikrimi değiştirdim."},
{eng:"I changed my plans suddenly.",tr:"Planlarımı aniden değiştirdim."},
{eng:"I changed my approach.",tr:"Yaklaşımımı değiştirdim."},
{eng:"I solved the problem.",tr:"Problemi çözdüm."},
{eng:"I solved it by myself.",tr:"Bunu kendi başıma çözdüm."},
{eng:"I solved the issue quickly.",tr:"Sorunu hızlıca çözdüm."},
{eng:"I avoided a big mistake.",tr:"Büyük bir hatadan kaçındım."},
{eng:"I avoided unnecessary arguments.",tr:"Gereksiz tartışmalardan kaçındım."},
{eng:"I avoided talking about politics.",tr:"Siyaset hakkında konuşmaktan kaçındım."},
{eng:"I faced many challenges.",tr:"Birçok zorlukla karşılaştım."},
{eng:"I faced a difficult decision.",tr:"Zor bir kararla karşılaştım."},
{eng:"I faced the consequences.",tr:"Sonuçlarıyla yüzleştim."},
{eng:"I took a deep breath.",tr:"Derin bir nefes aldım."},
{eng:"I took a short break.",tr:"Kısa bir mola verdim."},
{eng:"I took responsibility.",tr:"Sorumluluk aldım."},
{eng:"I took the opportunity.",tr:"Fırsatı değerlendirdim."},
{eng:"I made a decision.",tr:"Bir karar verdim."},
{eng:"I made a big mistake.",tr:"Büyük bir hata yaptım."},
{eng:"I made some progress.",tr:"Biraz ilerleme kaydettim."},
{eng:"I made a good impression.",tr:"İyi bir izlenim bıraktım."},
{eng:"I made a promise.",tr:"Bir söz verdim."},
{eng:"I made a suggestion.",tr:"Bir öneride bulundum."},
{eng:"I made a complaint.",tr:"Bir şikayette bulundum."},
{eng:"I made a reservation.",tr:"Rezervasyon yaptım."},
{eng:"I paid attention carefully.",tr:"Dikkatlice dikkat ettim."},
{eng:"I paid the bill.",tr:"Hesabı ödedim."},
{eng:"I paid for the tickets.",tr:"Biletlerin parasını ödedim."},
{eng:"I paid the price.",tr:"Bedelini ödedim."},
{eng:"I kept my promise.",tr:"Sözümü tuttum."},
{eng:"I kept the secret.",tr:"Sırrı sakladım."},
{eng:"I kept trying.",tr:"Denemeye devam ettim."},
{eng:"I kept working.",tr:"Çalışmaya devam ettim."},
{eng:"I came across an interesting article.",tr:"İlginç bir makaleye rastladım."},
{eng:"I ran into an old friend yesterday.",tr:"Dün eski bir arkadaşıma rastladım."},
{eng:"I figured out the solution.",tr:"Çözümü buldum."},
{eng:"I found out the truth later.",tr:"Gerçeği daha sonra öğrendim."},
{eng:"I gave up trying after a while.",tr:"Bir süre sonra denemeyi bıraktım."},
{eng:"I kept going despite the difficulties.",tr:"Zorluklara rağmen devam ettim."},
{eng:"I carried on working.",tr:"Çalışmaya devam ettim."},
{eng:"I looked into the problem carefully.",tr:"Problemi dikkatlice araştırdım."},
{eng:"I dealt with the situation calmly.",tr:"Durumla sakin bir şekilde başa çıktım."},
{eng:"I ended up staying at home.",tr:"Sonunda evde kaldım."},
{eng:"I ended up learning a lot.",tr:"Sonunda çok şey öğrendim."},
{eng:"I picked up some useful skills.",tr:"Bazı faydalı beceriler edindim."},
{eng:"I picked up the phone quickly.",tr:"Telefonu hızlıca açtım."},
{eng:"I turned off the computer.",tr:"Bilgisayarı kapattım."},
{eng:"I turned on the lights.",tr:"Işıkları açtım."},
{eng:"I turned out to be right.",tr:"Sonunda haklı çıktım."},
{eng:"I worked out the answer.",tr:"Cevabı hesapladım."},
{eng:"I sorted out the issue.",tr:"Sorunu çözdüm."},
{eng:"I pointed out the mistake.",tr:"Hatayı işaret ettim."},
{eng:"I wrote down the information.",tr:"Bilgiyi yazdım."},
{eng:"I filled out the form.",tr:"Formu doldurdum."},
{eng:"I signed the document.",tr:"Belgeyi imzaladım."},
{eng:"I submitted the report.",tr:"Raporu teslim ettim."},
{eng:"I checked the details.",tr:"Detayları kontrol ettim."},
{eng:"I checked my email.",tr:"E-postamı kontrol ettim."},
{eng:"I responded to the message.",tr:"Mesaja cevap verdim."},
{eng:"I replied immediately.",tr:"Hemen cevap verdim."},
{eng:"I ignored the warning.",tr:"Uyarıyı görmezden geldim."},
{eng:"I considered your suggestion.",tr:"Önerini düşündüm."},
{eng:"I accepted the offer.",tr:"Teklifi kabul ettim."},
{eng:"I rejected the proposal.",tr:"Teklifi reddettim."},
{eng:"I solved the puzzle.",tr:"Bulmacayı çözdüm."},
{eng:"I explained the process.",tr:"Süreci açıkladım."},
{eng:"I described the situation.",tr:"Durumu tarif ettim."},
{eng:"I summarized the main idea.",tr:"Ana fikri özetledim."},
{eng:"I compared the two options.",tr:"İki seçeneği karşılaştırdım."},
{eng:"I analyzed the results.",tr:"Sonuçları analiz ettim."},
{eng:"I improved my strategy.",tr:"Stratejimi geliştirdim."},
{eng:"I focused on the important parts.",tr:"Önemli kısımlara odaklandım."},
{eng:"I tried a different method.",tr:"Farklı bir yöntem denedim."},
{eng:"I reached my destination.",tr:"Varış yerime ulaştım."},
{eng:"I missed the opportunity.",tr:"Fırsatı kaçırdım."},
{eng:"I seized the opportunity.",tr:"Fırsatı değerlendirdim."},
{eng:"I overcame my fear.",tr:"Korkumu yendim."},
{eng:"I overcame many obstacles.",tr:"Birçok engeli aştım."},
{eng:"I gained valuable experience.",tr:"Değerli deneyim kazandım."},
{eng:"I lost my motivation.",tr:"Motivasyonumu kaybettim."},
{eng:"I regained my confidence.",tr:"Özgüvenimi geri kazandım."},
{eng:"I improved my performance.",tr:"Performansımı geliştirdim."},
{eng:"I developed a new habit.",tr:"Yeni bir alışkanlık geliştirdim."},
{eng:"I broke a bad habit.",tr:"Kötü bir alışkanlığı bıraktım."},
{eng:"I faced unexpected problems.",tr:"Beklenmedik problemlerle karşılaştım."},
{eng:"I found a practical solution.",tr:"Pratik bir çözüm buldum."},
{eng:"I handled the pressure well.",tr:"Baskıyı iyi yönettim."},
{eng:"I stayed calm under pressure.",tr:"Baskı altında sakin kaldım."},
{eng:"I remained positive.",tr:"Pozitif kaldım."},
{eng:"I stayed focused.",tr:"Odaklanmış kaldım."},
{eng:"I kept my motivation.",tr:"Motivasyonumu korudum."},
{eng:"I lost track of time.",tr:"Zamanın nasıl geçtiğini fark etmedim."},
{eng:"I ran out of time.",tr:"Zamanım bitti."},
{eng:"I ran out of money.",tr:"Param bitti."},
{eng:"I took advantage of the opportunity.",tr:"Fırsattan yararlandım."},
{eng:"I made the most of my time.",tr:"Zamanımı en iyi şekilde kullandım."},
{eng:"I got used to the routine.",tr:"Rutine alıştım."},
{eng:"I got tired of waiting.",tr:"Beklemekten yoruldum."},
{eng:"I got better at speaking.",tr:"Konuşmada daha iyi oldum."},
{eng:"I got worse over time.",tr:"Zamanla daha kötü oldu."},
{eng:"I got confused.",tr:"Kafam karıştı."},
{eng:"I got surprised.",tr:"Şaşırdım."},
{eng:"I got frustrated.",tr:"Hayal kırıklığına uğradım."},
{eng:"I got excited.",tr:"Heyecanlandım."},
{eng:"I got worried.",tr:"Endişelendim."},
{eng:"I felt uncomfortable.",tr:"Rahatsız hissettim."},
{eng:"I felt confident.",tr:"Kendime güvenli hissettim."},
{eng:"I felt relaxed.",tr:"Rahatlamış hissettim."},
{eng:"I felt motivated.",tr:"Motivasyonlu hissettim."},
{eng:"I felt inspired.",tr:"İlham aldım."},
{eng:"I felt exhausted.",tr:"Bitkin hissettim."},
{eng:"I felt confused.",tr:"Kafam karışmış hissettim."},
{eng:"I felt hopeful.",tr:"Umutlu hissettim."},
{eng:"I felt grateful.",tr:"Minnettar hissettim."},
{eng:"I felt satisfied.",tr:"Memnun hissettim."},
{eng:"I felt disappointed.",tr:"Hayal kırıklığına uğradım."},
{eng:"I felt ashamed.",tr:"Utandım."},
{eng:"I felt proud.",tr:"Gurur duydum."},
{eng:"I felt curious.",tr:"Meraklı hissettim."},
{eng:"I felt uncertain.",tr:"Emin değildim."},
{eng:"I felt optimistic.",tr:"İyimser hissettim."},
{eng:"I felt pessimistic.",tr:"Karamsar hissettim."},
{eng:"I felt relieved.",tr:"Rahatlamış hissettim."},
{eng:"I felt determined.",tr:"Kararlı hissettim."},
{eng:"I felt prepared.",tr:"Hazır hissettim."},
{eng:"I tried to stay calm during the meeting.",tr:"Toplantı sırasında sakin kalmaya çalıştım."},
{eng:"I managed to solve the problem alone.",tr:"Problemi tek başıma çözmeyi başardım."},
{eng:"I spent too much time on this task.",tr:"Bu görev için çok fazla zaman harcadım."},
{eng:"I forgot to lock the door.",tr:"Kapıyı kilitlemeyi unuttum."},
{eng:"I remembered to bring the documents.",tr:"Belgeleri getirmeyi hatırladım."},
{eng:"I started to understand the situation.",tr:"Durumu anlamaya başladım."},
{eng:"I continued working late at night.",tr:"Gece geç saatlere kadar çalışmaya devam ettim."},
{eng:"I stopped worrying about the result.",tr:"Sonuç hakkında endişelenmeyi bıraktım."},
{eng:"I avoided making the same mistake.",tr:"Aynı hatayı yapmaktan kaçındım."},
{eng:"I tried to be more patient.",tr:"Daha sabırlı olmaya çalıştım."},
{eng:"I decided to take a short break.",tr:"Kısa bir mola vermeye karar verdim."},
{eng:"I learned how to fix the issue.",tr:"Sorunu nasıl düzelteceğimi öğrendim."},
{eng:"I improved my pronunciation.",tr:"Telaffuzumu geliştirdim."},
{eng:"I practiced speaking every day.",tr:"Her gün konuşma pratiği yaptım."},
{eng:"I listened carefully to the teacher.",tr:"Öğretmeni dikkatlice dinledim."},
{eng:"I asked an important question.",tr:"Önemli bir soru sordum."},
{eng:"I answered the question confidently.",tr:"Soruyu özgüvenle cevapladım."},
{eng:"I explained my opinion clearly.",tr:"Fikrimi açıkça açıkladım."},
{eng:"I described the situation in detail.",tr:"Durumu detaylı şekilde anlattım."},
{eng:"I compared the results carefully.",tr:"Sonuçları dikkatlice karşılaştırdım."},
{eng:"I noticed a small difference.",tr:"Küçük bir fark fark ettim."},
{eng:"I realized the importance of practice.",tr:"Pratiğin önemini fark ettim."},
{eng:"I accepted the challenge.",tr:"Meydan okumayı kabul ettim."},
{eng:"I refused to give up.",tr:"Pes etmeyi reddettim."},
{eng:"I promised to help my friend.",tr:"Arkadaşıma yardım edeceğime söz verdim."},
{eng:"I offered my support.",tr:"Destek teklif ettim."},
{eng:"I suggested a better idea.",tr:"Daha iyi bir fikir önerdim."},
{eng:"I recommended this book.",tr:"Bu kitabı tavsiye ettim."},
{eng:"I advised him to wait.",tr:"Ona beklemesini tavsiye ettim."},
{eng:"I encouraged my friend.",tr:"Arkadaşımı cesaretlendirdim."},
{eng:"I tried to motivate the team.",tr:"Takımı motive etmeye çalıştım."},
{eng:"I helped my colleague.",tr:"Meslektaşıma yardım ettim."},
{eng:"I supported my family.",tr:"Ailemi destekledim."},
{eng:"I trusted his decision.",tr:"Onun kararına güvendim."},
{eng:"I doubted his explanation.",tr:"Onun açıklamasından şüphe ettim."},
{eng:"I questioned the result.",tr:"Sonucu sorguladım."},
{eng:"I reviewed the report.",tr:"Raporu gözden geçirdim."},
{eng:"I checked the schedule.",tr:"Programı kontrol ettim."},
{eng:"I updated the information.",tr:"Bilgiyi güncelledim."},
{eng:"I corrected the mistake.",tr:"Hatayı düzelttim."},
{eng:"I fixed the problem quickly.",tr:"Sorunu hızlıca düzelttim."},
{eng:"I prepared the presentation.",tr:"Sunumu hazırladım."},
{eng:"I delivered the message.",tr:"Mesajı ilettim."},
{eng:"I shared the news.",tr:"Haberi paylaştım."},
{eng:"I announced the decision.",tr:"Kararı duyurdum."},
{eng:"I explained the rules.",tr:"Kuralları açıkladım."},
{eng:"I followed the instructions.",tr:"Talimatları takip ettim."},
{eng:"I completed the assignment.",tr:"Ödevi tamamladım."},
{eng:"I submitted my work.",tr:"Çalışmamı teslim ettim."},
{eng:"I finished everything on time.",tr:"Her şeyi zamanında bitirdim."},
{eng:"The meeting started earlier than expected.",tr:"Toplantı beklenenden erken başladı."},
{eng:"The discussion became very interesting.",tr:"Tartışma çok ilginç hale geldi."},
{eng:"The situation changed suddenly.",tr:"Durum aniden değişti."},
{eng:"The weather became colder.",tr:"Hava daha soğuk oldu."},
{eng:"The traffic was heavier today.",tr:"Trafik bugün daha yoğundu."},
{eng:"The journey took longer than expected.",tr:"Yolculuk beklenenden uzun sürdü."},
{eng:"The result surprised everyone.",tr:"Sonuç herkesi şaşırttı."},
{eng:"The answer seemed correct.",tr:"Cevap doğru görünüyordu."},
{eng:"The problem looked complicated.",tr:"Problem karmaşık görünüyordu."},
{eng:"The solution seemed simple.",tr:"Çözüm basit görünüyordu."},
{eng:"People often make mistakes.",tr:"İnsanlar sık sık hata yapar."},
{eng:"People learn from experience.",tr:"İnsanlar deneyimden öğrenir."},
{eng:"People sometimes change their opinions.",tr:"İnsanlar bazen fikirlerini değiştirir."},
{eng:"People usually prefer comfort.",tr:"İnsanlar genelde rahatlığı tercih eder."},
{eng:"People rarely admit their mistakes.",tr:"İnsanlar nadiren hatalarını kabul eder."},
{eng:"This idea sounds interesting.",tr:"Bu fikir ilginç geliyor."},
{eng:"This plan seems risky.",tr:"Bu plan riskli görünüyor."},
{eng:"This problem requires patience.",tr:"Bu problem sabır gerektirir."},
{eng:"This solution might work.",tr:"Bu çözüm işe yarayabilir."},
{eng:"This situation needs attention.",tr:"Bu durum dikkat gerektiriyor."},
{eng:"That explanation makes sense.",tr:"O açıklama mantıklı."},
{eng:"That decision surprised everyone.",tr:"O karar herkesi şaşırttı."},
{eng:"That mistake caused problems.",tr:"O hata sorunlara yol açtı."},
{eng:"That event changed everything.",tr:"O olay her şeyi değiştirdi."},
{eng:"That experience taught me a lot.",tr:"O deneyim bana çok şey öğretti."},
{eng:"We discussed the issue.",tr:"Sorunu tartıştık."},
{eng:"We reached an agreement.",tr:"Bir anlaşmaya vardık."},
{eng:"We solved the problem together.",tr:"Problemi birlikte çözdük."},
{eng:"We worked as a team.",tr:"Takım olarak çalıştık."},
{eng:"We achieved our goal.",tr:"Hedefimize ulaştık."},
{eng:"They finished the project.",tr:"Projeyi bitirdiler."},
{eng:"They improved the system.",tr:"Sistemi geliştirdiler."},
{eng:"They changed their strategy.",tr:"Stratejilerini değiştirdiler."},
{eng:"They discovered a mistake.",tr:"Bir hata keşfettiler."},
{eng:"They corrected the error.",tr:"Hatayı düzelttiler."},
{eng:"He solved the puzzle quickly.",tr:"Bulmacayı hızlı çözdü."},
{eng:"He explained the problem clearly.",tr:"Problemi açıkça açıkladı."},
{eng:"He noticed the difference.",tr:"Farkı fark etti."},
{eng:"He followed the instructions.",tr:"Talimatları takip etti."},
{eng:"He reached the conclusion.",tr:"Sonuca ulaştı."},
{eng:"She organized the meeting.",tr:"Toplantıyı organize etti."},
{eng:"She prepared the documents.",tr:"Belgeleri hazırladı."},
{eng:"She checked the details.",tr:"Detayları kontrol etti."},
{eng:"She corrected the mistake.",tr:"Hatayı düzeltti."},
{eng:"She improved the process.",tr:"Süreci geliştirdi."},
{eng:"The team worked efficiently.",tr:"Takım verimli çalıştı."},
{eng:"The company increased its profits.",tr:"Şirket kârını artırdı."},
{eng:"The manager approved the plan.",tr:"Müdür planı onayladı."},
{eng:"The engineer solved the issue.",tr:"Mühendis sorunu çözdü."},
{eng:"The teacher explained the lesson.",tr:"Öğretmen dersi açıkladı."},
{eng:"Learning a language takes time.",tr:"Dil öğrenmek zaman alır."},
{eng:"Practice improves your skills.",tr:"Pratik becerilerini geliştirir."},
{eng:"Experience makes people wiser.",tr:"Deneyim insanları daha bilge yapar."},
{eng:"Patience helps you succeed.",tr:"Sabır başarılı olmana yardımcı olur."},
{eng:"Hard work brings results.",tr:"Çok çalışmak sonuç getirir."},
{eng:"Success requires effort.",tr:"Başarı çaba gerektirir."},
{eng:"Failure teaches valuable lessons.",tr:"Başarısızlık değerli dersler öğretir."},
{eng:"Challenges build character.",tr:"Zorluklar karakter oluşturur."},
{eng:"Mistakes help you grow.",tr:"Hatalar gelişmene yardımcı olur."},
{eng:"Confidence improves performance.",tr:"Özgüven performansı artırır."},
{eng:"I woke up earlier than usual today.",tr:"Bugün normalden daha erken uyandım."},
{eng:"I had trouble falling asleep last night.",tr:"Dün gece uykuya dalmakta zorlandım."},
{eng:"I checked the weather before leaving.",tr:"Çıkmadan önce havayı kontrol ettim."},
{eng:"I packed my bag carefully.",tr:"Çantamı dikkatlice hazırladım."},
{eng:"I forgot where I parked the car.",tr:"Arabayı nereye park ettiğimi unuttum."},
{eng:"I waited for the bus for twenty minutes.",tr:"Otobüsü yirmi dakika bekledim."},
{eng:"I arrived at work a bit late.",tr:"İşe biraz geç vardım."},
{eng:"I greeted my colleagues politely.",tr:"Meslektaşlarımı nazikçe selamladım."},
{eng:"I organized my desk before starting.",tr:"Başlamadan önce masamı düzenledim."},
{eng:"I checked my tasks for the day.",tr:"Günün görevlerini kontrol ettim."},
{eng:"I tried to concentrate on my work.",tr:"İşime odaklanmaya çalıştım."},
{eng:"I solved a difficult problem.",tr:"Zor bir problemi çözdüm."},
{eng:"I asked my manager for advice.",tr:"Müdürümden tavsiye istedim."},
{eng:"I discussed the project with my team.",tr:"Projeyi ekibimle tartıştım."},
{eng:"I shared my ideas during the meeting.",tr:"Toplantı sırasında fikirlerimi paylaştım."},
{eng:"I listened carefully to the feedback.",tr:"Geri bildirimi dikkatlice dinledim."},
{eng:"I took notes during the presentation.",tr:"Sunum sırasında not aldım."},
{eng:"I reviewed my work before sending it.",tr:"Göndermeden önce çalışmamı gözden geçirdim."},
{eng:"I corrected several small errors.",tr:"Birkaç küçük hatayı düzelttim."},
{eng:"I sent the report to my manager.",tr:"Raporu müdürüme gönderdim."},
{eng:"I felt satisfied with my progress.",tr:"İlerlememden memnun hissettim."},
{eng:"I felt stressed because of the deadline.",tr:"Son tarih yüzünden stresli hissettim."},
{eng:"I felt confident about my decision.",tr:"Kararım konusunda kendime güvendim."},
{eng:"I felt uncertain about the result.",tr:"Sonuç konusunda emin değildim."},
{eng:"I felt grateful for the opportunity.",tr:"Fırsat için minnettar hissettim."},
{eng:"I felt motivated to continue.",tr:"Devam etmek için motive hissettim."},
{eng:"I felt relaxed after finishing the work.",tr:"İşi bitirdikten sonra rahatladım."},
{eng:"I felt curious about the topic.",tr:"Konu hakkında meraklı hissettim."},
{eng:"I felt proud of my achievement.",tr:"Başarımıyla gurur duydum."},
{eng:"I felt nervous before the presentation.",tr:"Sunumdan önce gergindim."},
{eng:"I walked home after work.",tr:"İşten sonra eve yürüdüm."},
{eng:"I stopped at a small café.",tr:"Küçük bir kafede durdum."},
{eng:"I ordered a cup of coffee.",tr:"Bir fincan kahve sipariş ettim."},
{eng:"I watched people passing by.",tr:"Geçen insanları izledim."},
{eng:"I enjoyed the peaceful atmosphere.",tr:"Sakin atmosferin tadını çıkardım."},
{eng:"I called my friend in the evening.",tr:"Akşam arkadaşımı aradım."},
{eng:"I talked about my day.",tr:"Günüm hakkında konuştum."},
{eng:"I listened to his story.",tr:"Onun hikayesini dinledim."},
{eng:"I laughed at his joke.",tr:"Şakasına güldüm."},
{eng:"I promised to meet him soon.",tr:"Yakında onunla buluşacağıma söz verdim."},
{eng:"I cooked dinner for myself.",tr:"Kendime akşam yemeği yaptım."},
{eng:"I tried a new recipe.",tr:"Yeni bir tarif denedim."},
{eng:"I added some extra spices.",tr:"Biraz ekstra baharat ekledim."},
{eng:"I tasted the food carefully.",tr:"Yemeğin tadına dikkatlice baktım."},
{eng:"I enjoyed the meal.",tr:"Yemeğin tadını çıkardım."},
{eng:"I cleaned the kitchen after dinner.",tr:"Akşam yemeğinden sonra mutfağı temizledim."},
{eng:"I washed the dishes.",tr:"Bulaşıkları yıkadım."},
{eng:"I wiped the table.",tr:"Masayı sildim."},
{eng:"I took out the trash.",tr:"Çöpü dışarı çıkardım."},
{eng:"I organized the shelves.",tr:"Rafları düzenledim."},
{eng:"I sat on the sofa to relax.",tr:"Rahatlamak için kanepeye oturdum."},
{eng:"I watched an interesting documentary.",tr:"İlginç bir belgesel izledim."},
{eng:"I learned something new from it.",tr:"Ondan yeni bir şey öğrendim."},
{eng:"I searched the topic online.",tr:"Konuyu internette araştırdım."},
{eng:"I read several articles.",tr:"Birkaç makale okudum."},
{eng:"I practiced my English for an hour.",tr:"Bir saat İngilizce çalıştım."},
{eng:"I learned some new vocabulary.",tr:"Yeni kelimeler öğrendim."},
{eng:"I repeated the pronunciation.",tr:"Telaffuzu tekrar ettim."},
{eng:"I wrote some example sentences.",tr:"Bazı örnek cümleler yazdım."},
{eng:"I tested myself with questions.",tr:"Kendimi sorularla test ettim."},
{eng:"I checked my messages before sleeping.",tr:"Uyumadan önce mesajlarımı kontrol ettim."},
{eng:"I replied to an email.",tr:"Bir e-postaya cevap verdim."},
{eng:"I turned off the lights.",tr:"Işıkları kapattım."},
{eng:"I set my alarm for the morning.",tr:"Sabah için alarm kurdum."},
{eng:"I went to bed feeling tired.",tr:"Yorgun hissederek yatağa gittim."},
{eng:"Life sometimes brings unexpected surprises.",tr:"Hayat bazen beklenmedik sürprizler getirir."},
{eng:"Every experience teaches something new.",tr:"Her deneyim yeni bir şey öğretir."},
{eng:"Hard work often leads to success.",tr:"Çok çalışmak genelde başarıya götürür."},
{eng:"Patience helps people overcome difficulties.",tr:"Sabır insanların zorlukları aşmasına yardımcı olur."},
{eng:"Learning never really ends.",tr:"Öğrenme aslında hiç bitmez."},
{eng:"I tried to stay focused despite the noise.",tr:"Gürültüye rağmen odaklanmaya çalıştım."},
{eng:"I realized that I forgot my keys.",tr:"Anahtarlarımı unuttuğumu fark ettim."},
{eng:"I checked the map before starting the trip.",tr:"Yolculuğa başlamadan önce haritayı kontrol ettim."},
{eng:"I packed everything the night before.",tr:"Her şeyi bir gece önceden hazırladım."},
{eng:"I left the house earlier than planned.",tr:"Evden planlanandan daha erken çıktım."},
{eng:"I noticed a new café on the street.",tr:"Sokakta yeni bir kafe fark ettim."},
{eng:"I stopped to take a photo.",tr:"Fotoğraf çekmek için durdum."},
{eng:"I watched the sunset from the hill.",tr:"Gün batımını tepeden izledim."},
{eng:"I enjoyed the fresh air.",tr:"Temiz havanın tadını çıkardım."},
{eng:"I felt more relaxed after the walk.",tr:"Yürüyüşten sonra daha rahat hissettim."},
{eng:"I spent the afternoon reading a novel.",tr:"Öğleden sonrayı roman okuyarak geçirdim."},
{eng:"I highlighted important sentences.",tr:"Önemli cümlelerin altını çizdim."},
{eng:"I wrote down some useful phrases.",tr:"Bazı faydalı ifadeleri yazdım."},
{eng:"I tried to memorize new words.",tr:"Yeni kelimeleri ezberlemeye çalıştım."},
{eng:"I repeated them several times.",tr:"Onları birkaç kez tekrar ettim."},
{eng:"I checked the pronunciation online.",tr:"Telaffuzu internette kontrol ettim."},
{eng:"I compared different explanations.",tr:"Farklı açıklamaları karşılaştırdım."},
{eng:"I searched for more examples.",tr:"Daha fazla örnek aradım."},
{eng:"I finally understood the grammar rule.",tr:"Sonunda dilbilgisi kuralını anladım."},
{eng:"I practiced using the rule in sentences.",tr:"Kuralı cümlelerde kullanarak pratik yaptım."},
{eng:"I spoke English with a friend.",tr:"Bir arkadaşımla İngilizce konuştum."},
{eng:"I tried to speak more confidently.",tr:"Daha özgüvenli konuşmaya çalıştım."},
{eng:"I made a few small mistakes.",tr:"Birkaç küçük hata yaptım."},
{eng:"I corrected myself immediately.",tr:"Kendimi hemen düzelttim."},
{eng:"I improved a little every day.",tr:"Her gün biraz geliştim."},
{eng:"I paid attention to the details.",tr:"Detaylara dikkat ettim."},
{eng:"I followed the instructions step by step.",tr:"Talimatları adım adım takip ettim."},
{eng:"I double-checked the information.",tr:"Bilgiyi iki kez kontrol ettim."},
{eng:"I made sure everything was correct.",tr:"Her şeyin doğru olduğundan emin oldum."},
{eng:"I sent the final version.",tr:"Son versiyonu gönderdim."},
{eng:"I waited for a response patiently.",tr:"Bir cevap için sabırla bekledim."},
{eng:"I received good news later.",tr:"Daha sonra iyi haber aldım."},
{eng:"I shared the news with my family.",tr:"Haberi ailemle paylaştım."},
{eng:"I celebrated the moment.",tr:"O anı kutladım."},
{eng:"I thanked everyone for their support.",tr:"Herkese destekleri için teşekkür ettim."},
{eng:"I planned my goals for next year.",tr:"Gelecek yıl için hedeflerimi planladım."},
{eng:"I wrote them in my notebook.",tr:"Onları defterime yazdım."},
{eng:"I thought about my priorities.",tr:"Önceliklerimi düşündüm."},
{eng:"I decided to focus on learning.",tr:"Öğrenmeye odaklanmaya karar verdim."},
{eng:"I promised myself to stay disciplined.",tr:"Kendime disiplinli kalacağıma söz verdim."},
{eng:"I woke up feeling motivated.",tr:"Motive olmuş şekilde uyandım."},
{eng:"I started the day with exercise.",tr:"Güne egzersizle başladım."},
{eng:"I drank a glass of water.",tr:"Bir bardak su içtim."},
{eng:"I prepared a healthy breakfast.",tr:"Sağlıklı bir kahvaltı hazırladım."},
{eng:"I checked my schedule.",tr:"Programımı kontrol ettim."},
{eng:"I arranged my tasks by priority.",tr:"Görevlerimi önceliğe göre düzenledim."},
{eng:"I focused on the most important one.",tr:"En önemli olana odaklandım."},
{eng:"I avoided unnecessary distractions.",tr:"Gereksiz dikkat dağıtıcıları kaçındım."},
{eng:"I worked efficiently.",tr:"Verimli çalıştım."},
{eng:"I finished earlier than expected.",tr:"Beklenenden erken bitirdim."},
{eng:"I took a short walk outside.",tr:"Dışarıda kısa bir yürüyüş yaptım."},
{eng:"I enjoyed the quiet street.",tr:"Sessiz sokağın tadını çıkardım."},
{eng:"I listened to music while walking.",tr:"Yürürken müzik dinledim."},
{eng:"I watched people passing by.",tr:"Geçen insanları izledim."},
{eng:"I returned home feeling calm.",tr:"Sakin hissederek eve döndüm."},
{eng:"I spent the evening learning something new.",tr:"Akşamı yeni bir şey öğrenerek geçirdim."},
{eng:"I watched an educational video.",tr:"Eğitici bir video izledim."},
{eng:"I paused it to take notes.",tr:"Not almak için videoyu durdurdum."},
{eng:"I rewound a part I didn't understand.",tr:"Anlamadığım kısmı geri sardım."},
{eng:"I finally understood the concept.",tr:"Sonunda kavramı anladım."},
{eng:"Knowledge grows with practice.",tr:"Bilgi pratikle büyür."},
{eng:"Small steps lead to big progress.",tr:"Küçük adımlar büyük ilerlemeye götürür."},
{eng:"Consistency is the key to success.",tr:"Tutarlılık başarının anahtarıdır."},
{eng:"Every mistake is a chance to learn.",tr:"Her hata öğrenmek için bir fırsattır."},
{eng:"Curiosity keeps the mind active.",tr:"Merak zihni aktif tutar."},
{eng:"The city looked different at night.",tr:"Şehir gece farklı görünüyordu."},
{eng:"The streets were full of lights.",tr:"Sokaklar ışıklarla doluydu."},
{eng:"The air felt cooler.",tr:"Hava daha serin hissediliyordu."},
{eng:"The atmosphere was peaceful.",tr:"Atmosfer huzurluydu."},
{eng:"The moment felt special.",tr:"An özel hissettirdi."},
{eng:"Traveling teaches valuable lessons.",tr:"Seyahat etmek değerli dersler öğretir."},
{eng:"Meeting new people changes perspectives.",tr:"Yeni insanlarla tanışmak bakış açısını değiştirir."},
{eng:"Different cultures offer new ideas.",tr:"Farklı kültürler yeni fikirler sunar."},
{eng:"Experiences shape our understanding.",tr:"Deneyimler anlayışımızı şekillendirir."},
{eng:"Memories stay with us forever.",tr:"Anılar bizimle sonsuza kadar kalır."},
{eng:"I woke up before my alarm today.",tr:"Bugün alarmımdan önce uyandım."},
{eng:"I quickly got out of bed.",tr:"Hızlıca yataktan kalktım."},
{eng:"I opened the window to get some fresh air.",tr:"Temiz hava almak için pencereyi açtım."},
{eng:"I checked the weather on my phone.",tr:"Telefonumdan havayı kontrol ettim."},
{eng:"I decided to wear a jacket.",tr:"Bir ceket giymeye karar verdim."},
{eng:"I made a simple breakfast.",tr:"Basit bir kahvaltı hazırladım."},
{eng:"I toasted some bread.",tr:"Biraz ekmek kızarttım."},
{eng:"I poured myself a cup of tea.",tr:"Kendime bir fincan çay koydum."},
{eng:"I sat quietly at the table.",tr:"Masada sessizce oturdum."},
{eng:"I thought about my plans for the day.",tr:"Günün planlarını düşündüm."},
{eng:"I checked my messages.",tr:"Mesajlarımı kontrol ettim."},
{eng:"I replied to a friend.",tr:"Bir arkadaşıma cevap verdim."},
{eng:"I packed my backpack.",tr:"Sırt çantamı hazırladım."},
{eng:"I left the house quietly.",tr:"Evden sessizce çıktım."},
{eng:"I locked the door behind me.",tr:"Arkamdan kapıyı kilitledim."},
{eng:"I walked down the street slowly.",tr:"Sokakta yavaşça yürüdüm."},
{eng:"I greeted my neighbor.",tr:"Komşumu selamladım."},
{eng:"I crossed the road carefully.",tr:"Yolu dikkatlice geçtim."},
{eng:"I waited for the traffic light.",tr:"Trafik ışığını bekledim."},
{eng:"I continued walking to the station.",tr:"İstasyona yürümeye devam ettim."},
{eng:"I saw a dog running in the park.",tr:"Parkta koşan bir köpek gördüm."},
{eng:"I watched the dog for a moment.",tr:"Bir an köpeği izledim."},
{eng:"I smiled at the owner.",tr:"Sahibine gülümsedim."},
{eng:"I reached the bus stop.",tr:"Otobüs durağına ulaştım."},
{eng:"I checked the bus schedule.",tr:"Otobüs saatlerini kontrol ettim."},
{eng:"I waited with a few people.",tr:"Birkaç kişiyle birlikte bekledim."},
{eng:"I looked around the street.",tr:"Sokağın etrafına baktım."},
{eng:"I heard a loud motorcycle.",tr:"Gürültülü bir motosiklet duydum."},
{eng:"I covered my ears for a second.",tr:"Bir saniye kulaklarımı kapattım."},
{eng:"I laughed quietly.",tr:"Sessizce güldüm."},
{eng:"I saw the bus arriving.",tr:"Otobüsün geldiğini gördüm."},
{eng:"I stepped onto the bus.",tr:"Otobüse bindim."},
{eng:"I paid for the ticket.",tr:"Bilet için ödeme yaptım."},
{eng:"I found an empty seat.",tr:"Boş bir koltuk buldum."},
{eng:"I sat near the window.",tr:"Pencerenin yanına oturdum."},
{eng:"I watched the city outside.",tr:"Dışarıdaki şehri izledim."},
{eng:"I noticed many people walking quickly.",tr:"Birçok insanın hızlı yürüdüğünü fark ettim."},
{eng:"I wondered where they were going.",tr:"Nereye gittiklerini merak ettim."},
{eng:"I checked the time.",tr:"Saati kontrol ettim."},
{eng:"I realized I was early.",tr:"Erken olduğumu fark ettim."},
{eng:"I relaxed in my seat.",tr:"Koltukta rahatladım."},
{eng:"I listened to music on my phone.",tr:"Telefonumdan müzik dinledim."},
{eng:"I closed my eyes for a moment.",tr:"Bir an gözlerimi kapattım."},
{eng:"I imagined my future plans.",tr:"Gelecek planlarımı hayal ettim."},
{eng:"I opened my eyes again.",tr:"Gözlerimi tekrar açtım."},
{eng:"I saw my stop approaching.",tr:"Durağımın yaklaştığını gördüm."},
{eng:"I stood up carefully.",tr:"Dikkatlice ayağa kalktım."},
{eng:"I pressed the stop button.",tr:"Dur düğmesine bastım."},
{eng:"I got off the bus.",tr:"Otobüsten indim."},
{eng:"I walked toward the office.",tr:"Ofise doğru yürüdüm."},
{eng:"I entered the building.",tr:"Binaya girdim."},
{eng:"I greeted the receptionist.",tr:"Resepsiyonisti selamladım."},
{eng:"I took the elevator upstairs.",tr:"Asansörle yukarı çıktım."},
{eng:"I reached my floor.",tr:"Katıma ulaştım."},
{eng:"I walked to my desk.",tr:"Masama yürüdüm."},
{eng:"I turned on my computer.",tr:"Bilgisayarımı açtım."},
{eng:"I checked my emails.",tr:"E-postalarımı kontrol ettim."},
{eng:"I organized my tasks.",tr:"Görevlerimi düzenledim."},
{eng:"I started working immediately.",tr:"Hemen çalışmaya başladım."},
{eng:"I read an important message.",tr:"Önemli bir mesaj okudum."},
{eng:"I replied politely.",tr:"Nazikçe cevap verdim."},
{eng:"I opened a document.",tr:"Bir belge açtım."},
{eng:"I reviewed the information.",tr:"Bilgiyi gözden geçirdim."},
{eng:"I corrected a mistake.",tr:"Bir hatayı düzelttim."},
{eng:"I saved the file.",tr:"Dosyayı kaydettim."},
{eng:"I continued working carefully.",tr:"Dikkatlice çalışmaya devam ettim."},
{eng:"I focused on the details.",tr:"Detaylara odaklandım."},
{eng:"I completed the first task.",tr:"İlk görevi tamamladım."},
{eng:"I felt satisfied.",tr:"Memnun hissettim."},
{eng:"I moved to the next task.",tr:"Sonraki göreve geçtim."},
{eng:"I wrote several emails.",tr:"Birkaç e-posta yazdım."},
{eng:"I answered a phone call.",tr:"Bir telefon çağrısını cevapladım."},
{eng:"I explained the situation.",tr:"Durumu açıkladım."},
{eng:"I solved the issue quickly.",tr:"Sorunu hızlıca çözdüm."},
{eng:"I took a short break.",tr:"Kısa bir mola verdim."},
{eng:"I drank some water.",tr:"Biraz su içtim."},
{eng:"I stretched my arms.",tr:"Kollarımı esnettim."},
{eng:"I walked around the office.",tr:"Ofiste dolaştım."},
{eng:"I returned to my desk.",tr:"Masama geri döndüm."},
{eng:"I continued working.",tr:"Çalışmaya devam ettim."},
{eng:"I finished another task.",tr:"Başka bir görevi bitirdim."},
{eng:"I checked the progress.",tr:"İlerlemeyi kontrol ettim."},
{eng:"I updated the report.",tr:"Raporu güncelledim."},
{eng:"I shared it with my team.",tr:"Ekibimle paylaştım."},
{eng:"I asked for feedback.",tr:"Geri bildirim istedim."},
{eng:"I listened to their suggestions.",tr:"Önerilerini dinledim."},
{eng:"I made a few improvements.",tr:"Birkaç iyileştirme yaptım."},
{eng:"I felt more confident.",tr:"Daha özgüvenli hissettim."},
{eng:"I checked the time again.",tr:"Saate tekrar baktım."},
{eng:"I realized it was lunchtime.",tr:"Öğle vakti olduğunu fark ettim."},
{eng:"I left the office for lunch.",tr:"Öğle yemeği için ofisten çıktım."},
{eng:"I walked to a nearby restaurant.",tr:"Yakındaki bir restorana yürüdüm."},
{eng:"I ordered a simple meal.",tr:"Basit bir yemek sipariş ettim."},
{eng:"I waited patiently.",tr:"Sabırla bekledim."},
{eng:"I received my food.",tr:"Yemeğimi aldım."},
{eng:"I started eating slowly.",tr:"Yavaşça yemeye başladım."},
{eng:"I enjoyed the flavor.",tr:"Lezzetin tadını çıkardım."},
{eng:"I finished my lunch.",tr:"Öğle yemeğimi bitirdim."},
{eng:"I paid the bill.",tr:"Hesabı ödedim."},
{eng:"I walked back to the office.",tr:"Ofise geri yürüdüm."},
{eng:"I felt ready to continue working.",tr:"Çalışmaya devam etmeye hazır hissettim."},
{eng:"I started the project with great enthusiasm.",tr:"Projeye büyük bir heyecanla başladım."},
{eng:"I carefully planned every step.",tr:"Her adımı dikkatlice planladım."},
{eng:"I wrote down all my ideas.",tr:"Tüm fikirlerimi yazdım."},
{eng:"I created a simple schedule.",tr:"Basit bir program oluşturdum."},
{eng:"I followed the plan step by step.",tr:"Planı adım adım takip ettim."},
{eng:"I adjusted my strategy when necessary.",tr:"Gerektiğinde stratejimi ayarladım."},
{eng:"I tried to stay organized.",tr:"Düzenli kalmaya çalıştım."},
{eng:"I avoided unnecessary distractions.",tr:"Gereksiz dikkat dağıtıcıları kaçındım."},
{eng:"I focused on the most important tasks.",tr:"En önemli görevlere odaklandım."},
{eng:"I managed my time wisely.",tr:"Zamanımı akıllıca yönettim."},
{eng:"I solved several problems during the process.",tr:"Süreç boyunca birkaç problem çözdüm."},
{eng:"I asked questions when I was unsure.",tr:"Emin olmadığımda sorular sordum."},
{eng:"I learned from other people's experiences.",tr:"Diğer insanların deneyimlerinden öğrendim."},
{eng:"I tried different approaches.",tr:"Farklı yaklaşımlar denedim."},
{eng:"I discovered new possibilities.",tr:"Yeni olasılıklar keşfettim."},
{eng:"I improved my skills gradually.",tr:"Yeteneklerimi yavaş yavaş geliştirdim."},
{eng:"I gained valuable experience.",tr:"Değerli deneyim kazandım."},
{eng:"I became more confident.",tr:"Daha özgüvenli oldum."},
{eng:"I learned how to stay patient.",tr:"Sabırlı kalmayı öğrendim."},
{eng:"I realized the importance of persistence.",tr:"Azmin önemini fark ettim."},
{eng:"I continued working even when it was difficult.",tr:"Zor olduğunda bile çalışmaya devam ettim."},
{eng:"I refused to give up.",tr:"Pes etmeyi reddettim."},
{eng:"I stayed determined until the end.",tr:"Sonuna kadar kararlı kaldım."},
{eng:"I finally completed the project.",tr:"Sonunda projeyi tamamladım."},
{eng:"I reviewed the final results.",tr:"Son sonuçları gözden geçirdim."},
{eng:"I corrected a few last mistakes.",tr:"Birkaç son hatayı düzelttim."},
{eng:"I felt proud of my work.",tr:"Yaptığım işle gurur duydum."},
{eng:"I shared the results with my team.",tr:"Sonuçları ekibimle paylaştım."},
{eng:"I received positive feedback.",tr:"Olumlu geri bildirim aldım."},
{eng:"I appreciated their support.",tr:"Desteklerini takdir ettim."},
{eng:"I thanked everyone who helped me.",tr:"Bana yardım eden herkese teşekkür ettim."},
{eng:"I reflected on what I learned.",tr:"Ne öğrendiğimi düşündüm."},
{eng:"I realized how much I improved.",tr:"Ne kadar geliştiğimi fark ettim."},
{eng:"I set new goals for the future.",tr:"Gelecek için yeni hedefler koydum."},
{eng:"I promised myself to keep learning.",tr:"Öğrenmeye devam edeceğime kendime söz verdim."},
{eng:"I stayed curious about new ideas.",tr:"Yeni fikirlere karşı meraklı kaldım."},
{eng:"I kept reading useful books.",tr:"Faydalı kitaplar okumaya devam ettim."},
{eng:"I kept practicing every day.",tr:"Her gün pratik yapmaya devam ettim."},
{eng:"I kept improving my knowledge.",tr:"Bilgimi geliştirmeye devam ettim."},
{eng:"I tried to help others as well.",tr:"Başkalarına da yardım etmeye çalıştım."},
{eng:"I shared what I learned.",tr:"Öğrendiklerimi paylaştım."},
{eng:"I encouraged my friends to learn.",tr:"Arkadaşlarımı öğrenmeye teşvik ettim."},
{eng:"I believed in continuous improvement.",tr:"Sürekli gelişime inandım."},
{eng:"I stayed motivated despite challenges.",tr:"Zorluklara rağmen motive kaldım."},
{eng:"I learned to accept mistakes.",tr:"Hataları kabul etmeyi öğrendim."},
{eng:"I understood that failure is part of success.",tr:"Başarısızlığın başarının bir parçası olduğunu anladım."},
{eng:"I stayed optimistic about the future.",tr:"Gelecek hakkında iyimser kaldım."},
{eng:"I focused on progress instead of perfection.",tr:"Mükemmellik yerine ilerlemeye odaklandım."},
{eng:"I reminded myself to stay patient.",tr:"Sabırlı kalmam gerektiğini kendime hatırlattım."},
{eng:"I continued moving forward.",tr:"İlerlemeye devam ettim."},
{eng:"I trusted the process.",tr:"Sürece güvendim."},
{eng:"I believed that effort always pays off.",tr:"Çabanın her zaman karşılık verdiğine inandım."},
{eng:"I stayed consistent in my work.",tr:"Çalışmamda tutarlı kaldım."},
{eng:"I created better habits.",tr:"Daha iyi alışkanlıklar oluşturdum."},
{eng:"I avoided wasting time.",tr:"Zaman harcamaktan kaçındım."},
{eng:"I stayed focused on my goals.",tr:"Hedeflerime odaklı kaldım."},
{eng:"I used my time productively.",tr:"Zamanımı verimli kullandım."},
{eng:"I appreciated small improvements.",tr:"Küçük gelişmeleri takdir ettim."},
{eng:"I stayed disciplined every day.",tr:"Her gün disiplinli kaldım."},
{eng:"I built stronger confidence.",tr:"Daha güçlü bir özgüven geliştirdim."},
{eng:"I realized learning never ends.",tr:"Öğrenmenin asla bitmediğini fark ettim."},
{eng:"I stayed excited about the journey.",tr:"Yolculuk hakkında heyecanlı kaldım."},
{eng:"I believed in my potential.",tr:"Potansiyelime inandım."},
{eng:"I stayed determined to improve.",tr:"Gelişmeye kararlı kaldım."},
{eng:"I kept moving toward my dreams.",tr:"Hayallerime doğru ilerlemeye devam ettim."},
{eng:"I understood that progress takes time.",tr:"İlerlemenin zaman aldığını anladım."},
{eng:"I respected the learning process.",tr:"Öğrenme sürecine saygı duydum."},
{eng:"I remained patient and persistent.",tr:"Sabırlı ve azimli kaldım."},
{eng:"I continued developing my abilities.",tr:"Yeteneklerimi geliştirmeye devam ettim."},
{eng:"I stayed open to new opportunities.",tr:"Yeni fırsatlara açık kaldım."},
{eng:"I believed every step mattered.",tr:"Her adımın önemli olduğuna inandım."},
{eng:"I trusted my efforts.",tr:"Çabalarıma güvendim."},
{eng:"I kept building my future.",tr:"Geleceğimi inşa etmeye devam ettim."},
{eng:"I never stopped learning.",tr:"Öğrenmeyi asla bırakmadım."},
{eng:"I started reading a book about history.",tr:"Tarih hakkında bir kitap okumaya başladım."},
{eng:"I found the introduction very interesting.",tr:"Girişi çok ilginç buldum."},
{eng:"I learned about important events.",tr:"Önemli olayları öğrendim."},
{eng:"I made notes on key points.",tr:"Ana noktalar hakkında not aldım."},
{eng:"I looked up words I didn't know.",tr:"Bilmediğim kelimeleri araştırdım."},
{eng:"I tried to understand the meaning.",tr:"Anlamını anlamaya çalıştım."},
{eng:"I discussed the topic with a friend.",tr:"Konuyu bir arkadaşla tartıştım."},
{eng:"I shared my opinion openly.",tr:"Fikrimi açıkça paylaştım."},
{eng:"I listened carefully to his opinion.",tr:"Fikrini dikkatlice dinledim."},
{eng:"I compared different perspectives.",tr:"Farklı bakış açılarını karşılaştırdım."},
{eng:"I asked questions to clarify ideas.",tr:"Fikirleri netleştirmek için sorular sordum."},
{eng:"I tried to remember important dates.",tr:"Önemli tarihleri hatırlamaya çalıştım."},
{eng:"I reviewed my notes in the evening.",tr:"Akşam notlarımı gözden geçirdim."},
{eng:"I summarized each chapter.",tr:"Her bölümü özetledim."},
{eng:"I highlighted essential information.",tr:"Temel bilgileri vurguladım."},
{eng:"I felt more confident about history.",tr:"Tarih konusunda daha özgüvenli hissettim."},
{eng:"I shared some facts with my teacher.",tr:"Öğretmenimle bazı bilgileri paylaştım."},
{eng:"I learned something new every day.",tr:"Her gün yeni bir şey öğrendim."},
{eng:"I tried to connect ideas logically.",tr:"Fikirleri mantıklı şekilde bağlamaya çalıştım."},
{eng:"I understood the importance of learning history.",tr:"Tarih öğrenmenin önemini anladım."},
{eng:"I reflected on past events.",tr:"Geçmiş olaylar üzerine düşündüm."},
{eng:"I imagined life in ancient times.",tr:"Eski zamanlarda hayatı hayal ettim."},
{eng:"I felt curious about different cultures.",tr:"Farklı kültürler hakkında meraklı hissettim."},
{eng:"I compared ancient and modern life.",tr:"Antik ve modern hayatı karşılaştırdım."},
{eng:"I discussed these ideas in class.",tr:"Bu fikirleri derste tartıştım."},
{eng:"I answered several questions correctly.",tr:"Birkaç soruyu doğru cevapladım."},
{eng:"I learned new vocabulary during the discussion.",tr:"Tartışma sırasında yeni kelimeler öğrendim."},
{eng:"I felt more interested in history now.",tr:"Şimdi tarihe daha ilgili hissettim."},
{eng:"I planned to read more books on this topic.",tr:"Bu konuda daha fazla kitap okumayı planladım."},
{eng:"I organized my notes in a notebook.",tr:"Notlarımı bir deftere düzenledim."},
{eng:"I reviewed the notes regularly.",tr:"Notları düzenli olarak gözden geçirdim."},
{eng:"I asked for advice on good resources.",tr:"İyi kaynaklar konusunda tavsiye istedim."},
{eng:"I found some useful websites.",tr:"Birkaç faydalı web sitesi buldum."},
{eng:"I bookmarked interesting articles.",tr:"İlginç makaleleri yer imlerine ekledim."},
{eng:"I tried to read every day.",tr:"Her gün okumaya çalıştım."},
{eng:"I set a goal to finish one book per week.",tr:"Haftada bir kitap bitirme hedefi koydum."},
{eng:"I discussed the chapters with my classmates.",tr:"Bölümleri sınıf arkadaşlarımla tartıştım."},
{eng:"I shared my insights with my teacher.",tr:"Öğretmenimle görüşlerimi paylaştım."},
{eng:"I realized that learning is a continuous process.",tr:"Öğrenmenin sürekli bir süreç olduğunu fark ettim."},
{eng:"I applied what I learned in assignments.",tr:"Öğrendiklerimi ödevlerde uyguladım."},
{eng:"I felt more prepared for exams.",tr:"Sınavlar için daha hazırlıklı hissettim."},
{eng:"I encouraged friends to read more.",tr:"Arkadaşlarımı daha fazla okumaya teşvik ettim."},
{eng:"I found group discussions helpful.",tr:"Grup tartışmalarını faydalı buldum."},
{eng:"I listened to historical podcasts.",tr:"Tarih podcastlerini dinledim."},
{eng:"I watched documentaries online.",tr:"Belgeselleri çevrimiçi izledim."},
{eng:"I took notes while watching videos.",tr:"Video izlerken not aldım."},
{eng:"I reviewed videos later for better understanding.",tr:"Daha iyi anlamak için videoları sonra gözden geçirdim."},
{eng:"I felt more confident discussing historical topics.",tr:"Tarih konularını tartışırken daha özgüvenli hissettim."},
{eng:"I understood the connection between events.",tr:"Olaylar arasındaki bağlantıyı anladım."},
{eng:"I explored different historical periods.",tr:"Farklı tarihi dönemleri araştırdım."},
{eng:"I learned about important historical figures.",tr:"Önemli tarihi kişiler hakkında öğrendim."},
{eng:"I compared different interpretations of events.",tr:"Olayların farklı yorumlarını karşılaştırdım."},
{eng:"I shared my findings with classmates.",tr:"Bulgularımı sınıf arkadaşlarımla paylaştım."},
{eng:"I wrote a short report.",tr:"Kısa bir rapor yazdım."},
{eng:"I proofread my work carefully.",tr:"Çalışmamı dikkatlice kontrol ettim."},
{eng:"I submitted the report on time.",tr:"Raporu zamanında teslim ettim."},
{eng:"I received constructive feedback.",tr:"Yapıcı geri bildirim aldım."},
{eng:"I corrected mistakes based on feedback.",tr:"Geri bildirimlere göre hataları düzelttim."},
{eng:"I felt proud of my improvement.",tr:"Gelişimimle gurur duydum."},
{eng:"I promised myself to keep learning.",tr:"Kendime öğrenmeye devam edeceğime söz verdim."},
{eng:"I felt motivated to study more.",tr:"Daha fazla çalışmak için motive hissettim."},
{eng:"I made a plan for the next month.",tr:"Gelecek ay için bir plan yaptım."},
{eng:"I set achievable goals.",tr:"Ulaşılabilir hedefler belirledim."},
{eng:"I stayed consistent in my learning.",tr:"Öğrenmede tutarlı kaldım."},
{eng:"I monitored my progress every week.",tr:"İlerlememi her hafta takip ettim."},
{eng:"I celebrated small achievements.",tr:"Küçük başarıları kutladım."},
{eng:"I reflected on my mistakes.",tr:"Hatalarım üzerine düşündüm."},
{eng:"I tried to learn from them.",tr:"Onlardan ders çıkarmaya çalıştım."},
{eng:"I felt more capable every day.",tr:"Her gün daha yetenekli hissettim."},
{eng:"I shared my knowledge with friends.",tr:"Bilgimi arkadaşlarımla paylaştım."},
{eng:"I encouraged others to study.",tr:"Başkalarını çalışmaya teşvik ettim."},
{eng:"I realized the importance of persistence.",tr:"Azmin önemini fark ettim."},
{eng:"I stayed focused even when tired.",tr:"Yorgunken bile odaklı kaldım."},
{eng:"I understood that success takes effort.",tr:"Başarının çaba gerektirdiğini anladım."},
{eng:"I appreciated every little progress.",tr:"Her küçük ilerlemeyi takdir ettim."},
{eng:"I felt grateful for my teachers.",tr:"Öğretmenlerime minnettar hissettim."},
{eng:"I kept improving my skills.",tr:"Yeteneklerimi geliştirmeye devam ettim."},
{eng:"I read, wrote, listened, and spoke every day.",tr:"Her gün okudum, yazdım, dinledim ve konuştum."},
{eng:"I learned to stay disciplined and patient.",tr:"Disiplinli ve sabırlı kalmayı öğrendim."},
{eng:"I realized learning is a lifelong journey.",tr:"Öğrenmenin ömür boyu süren bir yolculuk olduğunu fark ettim."},
{eng:"I stayed excited about new challenges.",tr:"Yeni zorluklar hakkında heyecanlı kaldım."},
{eng:"I trusted myself and my abilities.",tr:"Kendime ve yeteneklerime güvendim."},
{eng:"I kept moving forward step by step.",tr:"Adım adım ilerlemeye devam ettim."},
{eng:"I understood the value of patience.",tr:"Sabırın değerini anladım."},
{eng:"I felt proud of my consistency.",tr:"Tutarlılığımla gurur duydum."},
{eng:"I learned to manage my time better.",tr:"Zamanımı daha iyi yönetmeyi öğrendim."},
{eng:"I stayed motivated despite difficulties.",tr:"Zorluklara rağmen motive kaldım."},
{eng:"I believed that effort always pays off.",tr:"Çabanın her zaman karşılık verdiğine inandım."},
{eng:"I kept learning from mistakes.",tr:"Hatalardan öğrenmeye devam ettim."},
{eng:"I stayed curious and open-minded.",tr:"Meraklı ve açık fikirli kaldım."},
{eng:"I planned to apply my knowledge practically.",tr:"Bilgimi pratik olarak uygulamayı planladım."},
{eng:"I realized that small steps lead to big results.",tr:"Küçük adımların büyük sonuçlara yol açtığını fark ettim."}
];