const cumleler = [
{isp:"Yo soy estudiante.",tr:"Ben öğrenciyim."},
{isp:"Yo soy profesor.",tr:"Ben öğretmenim."},
{isp:"Yo soy turco.",tr:"Ben Türküm."},
{isp:"Yo estoy en casa.",tr:"Evdeyim."},
{isp:"Estoy en el trabajo.",tr:"İşteyim."},
{isp:"Estoy en la cocina.",tr:"Mutfaktayım."},
{isp:"Tengo un libro.",tr:"Bir kitabım var."},
{isp:"Tengo una pregunta.",tr:"Bir sorum var."},
{isp:"Tengo tiempo.",tr:"Zamanım var."},
{isp:"No tengo dinero.",tr:"Param yok."},
{isp:"Tengo un problema.",tr:"Bir sorunum var."},
{isp:"Tengo sueño.",tr:"Uykum var."},
{isp:"Tengo miedo.",tr:"Korkuyorum."},
{isp:"Tengo prisa.",tr:"Acele ediyorum."},
{isp:"La casa es pequeña.",tr:"Ev küçük."},
{isp:"La casa es bonita.",tr:"Ev güzel."},
{isp:"El coche es nuevo.",tr:"Araba yeni."},
{isp:"El coche es viejo.",tr:"Araba eski."},
{isp:"El libro es rojo.",tr:"Kitap kırmızı."},
{isp:"La mesa es blanca.",tr:"Masa beyaz."},
{isp:"La silla es cómoda.",tr:"Sandalye rahat."},
{isp:"La puerta está cerrada.",tr:"Kapı kapalı."},
{isp:"La ventana está abierta.",tr:"Pencere açık."},
{isp:"El agua está caliente.",tr:"Su sıcak."},
{isp:"La comida está fría.",tr:"Yemek soğuk."},
{isp:"Mi madre está en casa.",tr:"Annem evde."},
{isp:"Mi padre trabaja mucho.",tr:"Babam çok çalışır."},
{isp:"Tengo un hermano.",tr:"Bir erkek kardeşim var."},
{isp:"Tengo una hermana.",tr:"Bir kız kardeşim var."},
{isp:"Mi amigo vive aquí.",tr:"Arkadaşım burada yaşıyor."},
{isp:"Mi amiga es simpática.",tr:"Kız arkadaşım sempatik."},
{isp:"Me gusta el café.",tr:"Kahveyi severim."},
{isp:"Me gusta el té.",tr:"Çayı severim."},
{isp:"No me gusta el frío.",tr:"Soğuğu sevmem."},
{isp:"Me gusta la música.",tr:"Müziği severim."},
{isp:"Escucho música.",tr:"Müzik dinliyorum."},
{isp:"Leo un libro.",tr:"Kitap okuyorum."},
{isp:"Escribo un mensaje.",tr:"Mesaj yazıyorum."},
{isp:"Abro la puerta.",tr:"Kapıyı açıyorum."},
{isp:"Cierro la ventana.",tr:"Pencereyi kapatıyorum."},
{isp:"Como pan.",tr:"Ekmek yiyorum."},
{isp:"Bebo agua.",tr:"Su içiyorum."},
{isp:"Veo una película.",tr:"Film izliyorum."},
{isp:"Voy a la escuela.",tr:"Okula gidiyorum."},
{isp:"Voy al trabajo.",tr:"İşe gidiyorum."},
{isp:"Voy al supermercado.",tr:"Markete gidiyorum."},
{isp:"Vengo de casa.",tr:"Evden geliyorum."},
{isp:"Duermo ocho horas.",tr:"Sekiz saat uyuyorum."},
{isp:"Trabajo hoy.",tr:"Bugün çalışıyorum."},
{isp:"Estudio español.",tr:"İspanyolca çalışıyorum."},
{isp:"Aprendo rápido.",tr:"Hızlı öğreniyorum."},
{isp:"Hablas español.",tr:"İspanyolca konuşuyorsun."},
{isp:"Hablo un poco de español.",tr:"Biraz İspanyolca konuşuyorum."},
{isp:"¿Dónde estás?",tr:"Neredesin?"},
{isp:"Estoy aquí.",tr:"Buradayım."},
{isp:"Estoy allí.",tr:"Oradayım."},
{isp:"¿Qué haces?",tr:"Ne yapıyorsun?"},
{isp:"Estoy trabajando.",tr:"Çalışıyorum."},
{isp:"Estoy estudiando.",tr:"Ders çalışıyorum."},
{isp:"Estoy comiendo.",tr:"Yemek yiyorum."},
{isp:"Estoy bebiendo café.",tr:"Kahve içiyorum."},
{isp:"Estoy viendo la televisión.",tr:"Televizyon izliyorum."},
{isp:"Es mi libro.",tr:"Bu benim kitabım."},
{isp:"Es tu casa.",tr:"Bu senin evin."},
{isp:"Es su coche.",tr:"Bu onun arabası."},
{isp:"Mi casa está cerca.",tr:"Evim yakın."},
{isp:"La escuela está lejos.",tr:"Okul uzak."},
{isp:"Hoy hace frío.",tr:"Bugün hava soğuk."},
{isp:"Hoy hace calor.",tr:"Bugün hava sıcak."},
{isp:"Es verano.",tr:"Yaz mevsimi."},
{isp:"Es invierno.",tr:"Kış mevsimi."},
{isp:"Es primavera.",tr:"Bahar mevsimi."},
{isp:"Es lunes hoy.",tr:"Bugün pazartesi."},
{isp:"Mañana es martes.",tr:"Yarın salı."},
{isp:"Son las dos.",tr:"Saat iki."},
{isp:"Es la una.",tr:"Saat bir."},
{isp:"Son las cinco.",tr:"Saat beş."},
{isp:"Tengo veinte años.",tr:"Yirmi yaşındayım."},
{isp:"Tengo treinta años.",tr:"Otuz yaşındayım."},
{isp:"Soy alto.",tr:"Uzunum."},
{isp:"Soy bajo.",tr:"Kısayım."},
{isp:"Soy feliz.",tr:"Mutluyum."},
{isp:"Estoy triste.",tr:"Üzgünüm."},
{isp:"Estoy cansado.",tr:"Yorgunum."},
{isp:"Estoy enfermo.",tr:"Hastayım."},
{isp:"Necesito ayuda.",tr:"Yardıma ihtiyacım var."},
{isp:"Necesito agua.",tr:"Suya ihtiyacım var."},
{isp:"Quiero comer.",tr:"Yemek istiyorum."},
{isp:"Quiero dormir.",tr:"Uyumak istiyorum."},
{isp:"Quiero aprender español.",tr:"İspanyolca öğrenmek istiyorum."},
{isp:"Puedo ayudarte.",tr:"Sana yardım edebilirim."},
{isp:"No puedo ir.",tr:"Gidemem."},
{isp:"Es fácil.",tr:"Kolay."},
{isp:"Es difícil.",tr:"Zor."},
{isp:"Es importante.",tr:"Önemli."},
{isp:"Es interesante.",tr:"İlginç."},
{isp:"Es verdad.",tr:"Doğru."},
{isp:"Es mentira.",tr:"Yalan."},
{isp:"Estoy listo.",tr:"Hazırım."},
{isp:"Estoy ocupado.",tr:"Meşgulüm."},
{isp:"Estoy libre.",tr:"Boştayım."},
{isp:"Llamo a mi madre.",tr:"Annemi arıyorum."},
{isp:"Llamo a mi amigo.",tr:"Arkadaşımı arıyorum."},
{isp:"Mando un mensaje.",tr:"Mesaj gönderiyorum."},
{isp:"Espero aquí.",tr:"Burada bekliyorum."},
{isp:"Entro en la casa.",tr:"Eve giriyorum."},
{isp:"Salgo de la casa.",tr:"Evden çıkıyorum."},
{isp:"Subo la escalera.",tr:"Merdiven çıkıyorum."},
{isp:"Bajo la escalera.",tr:"Merdiven iniyorum."},
{isp:"Compro pan.",tr:"Ekmek alıyorum."},
{isp:"Pago la cuenta.",tr:"Hesabı ödüyorum."},
{isp:"Abro el libro.",tr:"Kitabı açıyorum."},
{isp:"Cierro el libro.",tr:"Kitabı kapatıyorum."},
{isp:"Busco mi teléfono.",tr:"Telefonumu arıyorum."},
{isp:"Encuentro mi llave.",tr:"Anahtarımı buluyorum."},
{isp:"Empiezo ahora.",tr:"Şimdi başlıyorum."},
{isp:"Termino el trabajo.",tr:"İşi bitiriyorum."},
{isp:"Camino en el parque.",tr:"Parkta yürüyorum."},
{isp:"Corro rápido.",tr:"Hızlı koşuyorum."},
{isp:"Miro el cielo.",tr:"Gökyüzüne bakıyorum."},
{isp:"Escucho ruido.",tr:"Gürültü duyuyorum."},
{isp:"Hago ejercicio.",tr:"Egzersiz yapıyorum."},
{isp:"Limpio la casa.",tr:"Evi temizliyorum."},
{isp:"Cocino la cena.",tr:"Akşam yemeği yapıyorum."},
{isp:"Desayuno a las ocho.",tr:"Saat sekizde kahvaltı yapıyorum."},
{isp:"Ceno con mi familia.",tr:"Ailemle akşam yemeği yiyorum."},
{isp:"Vivo en un apartamento.",tr:"Bir apartmanda yaşıyorum."},
{isp:"Mi ciudad es grande.",tr:"Şehrim büyük."},
{isp:"Mi país es bonito.",tr:"Ülkem güzel."},
{isp:"Tengo una idea.",tr:"Bir fikrim var."},
{isp:"Tengo una respuesta.",tr:"Bir cevabım var."},
{isp:"El niño juega.",tr:"Çocuk oynuyor."},
{isp:"La niña estudia.",tr:"Kız çocuk ders çalışıyor."},
{isp:"El perro duerme.",tr:"Köpek uyuyor."},
{isp:"El gato come.",tr:"Kedi yemek yiyor."},
{isp:"La flor es bonita.",tr:"Çiçek güzel."},
{isp:"El sol brilla.",tr:"Güneş parlıyor."},
{isp:"La luna es blanca.",tr:"Ay beyaz."},
{isp:"El mar es azul.",tr:"Deniz mavi."},
{isp:"La montaña es alta.",tr:"Dağ yüksek."},
{isp:"El río es largo.",tr:"Nehir uzun."},
{isp:"El banco está cerrado.",tr:"Banka kapalı."},
{isp:"El hospital es grande.",tr:"Hastane büyük."},
{isp:"El profesor habla.",tr:"Öğretmen konuşuyor."},
{isp:"El estudiante escucha.",tr:"Öğrenci dinliyor."},
{isp:"La clase empieza ahora.",tr:"Ders şimdi başlıyor."},
{isp:"La película es buena.",tr:"Film iyi."},
{isp:"La serie es interesante.",tr:"Dizi ilginç."},
{isp:"El juego es divertido.",tr:"Oyun eğlenceli."},
{isp:"Tengo una cita hoy.",tr:"Bugün randevum var."},
{isp:"Estoy muy feliz hoy.",tr:"Bugün çok mutluyum."},
{isp:"Estoy un poco cansado.",tr:"Biraz yorgunum."},
{isp:"Estoy muy ocupado.",tr:"Çok meşgulüm."},
{isp:"Estoy en la cama.",tr:"Yataktayım."},
{isp:"Estoy en el sofá.",tr:"Koltuktayım."}
];