// ─────────────────────────────────────────────
//  espKelimeB.js · Intermediate Words (B Level)
//  Format: { eng: "word", esp: "palabra" }
// ─────────────────────────────────────────────

var EspKelimeBListesi = [
  // Emotions & Personality / Emociones y Personalidad
  { eng: "anxious",       esp: "ansioso"           },
  { eng: "confident",     esp: "seguro de sí mismo" },
  { eng: "curious",       esp: "curioso"           },
  { eng: "frustrated",    esp: "frustrado"         },
  { eng: "grateful",      esp: "agradecido"        },
  { eng: "jealous",       esp: "celoso"            },
  { eng: "lonely",        esp: "solitario"         },
  { eng: "nervous",       esp: "nervioso"          },
  { eng: "patient",       esp: "paciente"          },
  { eng: "proud",         esp: "orgulloso"         },
  { eng: "relieved",      esp: "aliviado"          },
  { eng: "stubborn",      esp: "terco"             },
  { eng: "suspicious",    esp: "sospechoso"        },
  { eng: "cheerful",      esp: "alegre"            },
  { eng: "generous",      esp: "generoso"          },
  { eng: "brave",         esp: "valiente"          },
  { eng: "shy",           esp: "tímido"            },
  { eng: "ambitious",     esp: "ambicioso"         },

  // Work & Professions / Trabajo y Profesiones
  { eng: "accountant",    esp: "contador"          },
  { eng: "architect",     esp: "arquitecto"        },
  { eng: "colleague",     esp: "colega"            },
  { eng: "deadline",      esp: "fecha límite"      },
  { eng: "employee",      esp: "empleado"          },
  { eng: "employer",      esp: "empleador"         },
  { eng: "interview",     esp: "entrevista"        },
  { eng: "manager",       esp: "gerente"           },
  { eng: "negotiate",     esp: "negociar"          },
  { eng: "promote",       esp: "promover"          },
  { eng: "resign",        esp: "renunciar"         },
  { eng: "salary",        esp: "salario"           },
  { eng: "career",        esp: "carrera"           },
  { eng: "contract",      esp: "contrato"          },
  { eng: "profession",    esp: "profesión"         },
  { eng: "lawyer",        esp: "abogado"           },
  { eng: "surgeon",       esp: "cirujano"          },
  { eng: "engineer",      esp: "ingeniero"         },

  // Technology / Tecnología
  { eng: "application",   esp: "aplicación"        },
  { eng: "browser",       esp: "navegador"         },
  { eng: "database",      esp: "base de datos"     },
  { eng: "download",      esp: "descargar"         },
  { eng: "hardware",      esp: "hardware"          },
  { eng: "network",       esp: "red"               },
  { eng: "password",      esp: "contraseña"        },
  { eng: "software",      esp: "software"          },
  { eng: "upload",        esp: "subir"             },
  { eng: "wireless",      esp: "inalámbrico"       },
  { eng: "device",        esp: "dispositivo"       },
  { eng: "screen",        esp: "pantalla"          },
  { eng: "update",        esp: "actualizar"        },
  { eng: "backup",        esp: "copia de seguridad"},
  { eng: "keyboard",      esp: "teclado"           },

  // Health / Salud
  { eng: "allergy",       esp: "alergia"           },
  { eng: "diagnosis",     esp: "diagnóstico"       },
  { eng: "fever",         esp: "fiebre"            },
  { eng: "headache",      esp: "dolor de cabeza"   },
  { eng: "injection",     esp: "inyección"         },
  { eng: "medicine",      esp: "medicina"          },
  { eng: "operation",     esp: "operación"         },
  { eng: "prescription",  esp: "receta"            },
  { eng: "symptom",       esp: "síntoma"           },
  { eng: "treatment",     esp: "tratamiento"       },
  { eng: "vaccine",       esp: "vacuna"            },
  { eng: "pharmacy",      esp: "farmacia"          },
  { eng: "emergency",     esp: "emergencia"        },
  { eng: "pain",          esp: "dolor"             },
  { eng: "disease",       esp: "enfermedad"        },

  // Environment / Medio Ambiente
  { eng: "atmosphere",    esp: "atmósfera"         },
  { eng: "climate",       esp: "clima"             },
  { eng: "drought",       esp: "sequía"            },
  { eng: "earthquake",    esp: "terremoto"         },
  { eng: "ecosystem",     esp: "ecosistema"        },
  { eng: "flood",         esp: "inundación"        },
  { eng: "pollution",     esp: "contaminación"     },
  { eng: "recycle",       esp: "reciclar"          },
  { eng: "renewable",     esp: "renovable"         },
  { eng: "species",       esp: "especie"           },
  { eng: "sustainable",   esp: "sostenible"        },
  { eng: "wildlife",      esp: "vida silvestre"    },
  { eng: "extinct",       esp: "extinto"           },
  { eng: "forest",        esp: "bosque"            },
  { eng: "desert",        esp: "desierto"          },

  // Education / Educación
  { eng: "assignment",    esp: "tarea"             },
  { eng: "certificate",   esp: "certificado"       },
  { eng: "curriculum",    esp: "currículo"         },
  { eng: "discipline",    esp: "disciplina"        },
  { eng: "graduate",      esp: "graduarse"         },
  { eng: "lecture",       esp: "conferencia"       },
  { eng: "scholarship",   esp: "beca"              },
  { eng: "semester",      esp: "semestre"          },
  { eng: "thesis",        esp: "tesis"             },
  { eng: "knowledge",     esp: "conocimiento"      },
  { eng: "research",      esp: "investigación"     },
  { eng: "academic",      esp: "académico"         },
  { eng: "university",    esp: "universidad"       },
  { eng: "library",       esp: "biblioteca"        },

  // Society & Politics / Sociedad y Política
  { eng: "campaign",      esp: "campaña"           },
  { eng: "citizen",       esp: "ciudadano"         },
  { eng: "conflict",      esp: "conflicto"         },
  { eng: "democracy",     esp: "democracia"        },
  { eng: "economy",       esp: "economía"          },
  { eng: "election",      esp: "elección"          },
  { eng: "equality",      esp: "igualdad"          },
  { eng: "government",    esp: "gobierno"          },
  { eng: "immigration",   esp: "inmigración"       },
  { eng: "justice",       esp: "justicia"          },
  { eng: "law",           esp: "ley"               },
  { eng: "protest",       esp: "protesta"          },
  { eng: "revolution",    esp: "revolución"        },
  { eng: "society",       esp: "sociedad"          },
  { eng: "freedom",       esp: "libertad"          },

  // Economy & Finance / Economía y Finanzas
  { eng: "budget",        esp: "presupuesto"       },
  { eng: "debt",          esp: "deuda"             },
  { eng: "export",        esp: "exportación"       },
  { eng: "import",        esp: "importación"       },
  { eng: "inflation",     esp: "inflación"         },
  { eng: "invest",        esp: "invertir"          },
  { eng: "loan",          esp: "préstamo"          },
  { eng: "profit",        esp: "ganancia"          },
  { eng: "revenue",       esp: "ingresos"          },
  { eng: "tax",           esp: "impuesto"          },
  { eng: "trade",         esp: "comercio"          },
  { eng: "currency",      esp: "moneda"            },
  { eng: "bankrupt",      esp: "en bancarrota"     },
  { eng: "market",        esp: "mercado"           },

  // Advanced Verbs / Verbos avanzados
  { eng: "accomplish",    esp: "lograr"            },
  { eng: "analyze",       esp: "analizar"          },
  { eng: "argue",         esp: "discutir"          },
  { eng: "concentrate",   esp: "concentrarse"      },
  { eng: "convince",      esp: "convencer"         },
  { eng: "describe",      esp: "describir"         },
  { eng: "develop",       esp: "desarrollar"       },
  { eng: "encourage",     esp: "animar"            },
  { eng: "establish",     esp: "establecer"        },
  { eng: "estimate",      esp: "estimar"           },
  { eng: "emphasize",     esp: "enfatizar"         },
  { eng: "implement",     esp: "implementar"       },
  { eng: "interpret",     esp: "interpretar"       },
  { eng: "maintain",      esp: "mantener"          },
  { eng: "obtain",        esp: "obtener"           },
  { eng: "overcome",      esp: "superar"           },
  { eng: "participate",   esp: "participar"        },
  { eng: "recognize",     esp: "reconocer"         },
  { eng: "represent",     esp: "representar"       },
  { eng: "suggest",       esp: "sugerir"           },
  { eng: "consider",      esp: "considerar"        },
  { eng: "achieve",       esp: "lograr"            },
  { eng: "distinguish",   esp: "distinguir"        },
];