// ─────────────────────────────────────────────
//  espKelimeA.js · Easy Words (A Level)
//  Format: { eng: "word", esp: "palabra" }
// ─────────────────────────────────────────────

var EspKelimeAListesi = [
  // Colors / Colores
  { eng: "red",          esp: "rojo"          },
  { eng: "blue",         esp: "azul"          },
  { eng: "green",        esp: "verde"         },
  { eng: "yellow",       esp: "amarillo"      },
  { eng: "black",        esp: "negro"         },
  { eng: "white",        esp: "blanco"        },
  { eng: "orange",       esp: "naranja"       },
  { eng: "purple",       esp: "morado"        },
  { eng: "pink",         esp: "rosa"          },
  { eng: "brown",        esp: "marrón"        },
  { eng: "grey",         esp: "gris"          },

  // Numbers / Números
  { eng: "one",          esp: "uno"           },
  { eng: "two",          esp: "dos"           },
  { eng: "three",        esp: "tres"          },
  { eng: "four",         esp: "cuatro"        },
  { eng: "five",         esp: "cinco"         },
  { eng: "six",          esp: "seis"          },
  { eng: "seven",        esp: "siete"         },
  { eng: "eight",        esp: "ocho"          },
  { eng: "nine",         esp: "nueve"         },
  { eng: "ten",          esp: "diez"          },
  { eng: "hundred",      esp: "cien"          },
  { eng: "thousand",     esp: "mil"           },

  // Family / Familia
  { eng: "mother",       esp: "madre"         },
  { eng: "father",       esp: "padre"         },
  { eng: "sister",       esp: "hermana"       },
  { eng: "brother",      esp: "hermano"       },
  { eng: "grandmother",  esp: "abuela"        },
  { eng: "grandfather",  esp: "abuelo"        },
  { eng: "baby",         esp: "bebé"          },
  { eng: "child",        esp: "niño / niña"   },
  { eng: "family",       esp: "familia"       },
  { eng: "friend",       esp: "amigo / amiga" },
  { eng: "husband",      esp: "esposo"        },
  { eng: "wife",         esp: "esposa"        },
  { eng: "son",          esp: "hijo"          },
  { eng: "daughter",     esp: "hija"          },

  // Animals / Animales
  { eng: "cat",          esp: "gato"          },
  { eng: "dog",          esp: "perro"         },
  { eng: "bird",         esp: "pájaro"        },
  { eng: "fish",         esp: "pez"           },
  { eng: "horse",        esp: "caballo"       },
  { eng: "cow",          esp: "vaca"          },
  { eng: "sheep",        esp: "oveja"         },
  { eng: "rabbit",       esp: "conejo"        },
  { eng: "lion",         esp: "león"          },
  { eng: "tiger",        esp: "tigre"         },
  { eng: "elephant",     esp: "elefante"      },
  { eng: "monkey",       esp: "mono"          },
  { eng: "snake",        esp: "serpiente"     },
  { eng: "chicken",      esp: "pollo"         },
  { eng: "duck",         esp: "pato"          },
  { eng: "bear",         esp: "oso"           },
  { eng: "wolf",         esp: "lobo"          },

  // Food / Comida
  { eng: "apple",        esp: "manzana"       },
  { eng: "bread",        esp: "pan"           },
  { eng: "milk",         esp: "leche"         },
  { eng: "water",        esp: "agua"          },
  { eng: "egg",          esp: "huevo"         },
  { eng: "cheese",       esp: "queso"         },
  { eng: "rice",         esp: "arroz"         },
  { eng: "soup",         esp: "sopa"          },
  { eng: "meat",         esp: "carne"         },
  { eng: "orange",       esp: "naranja"       },
  { eng: "banana",       esp: "plátano"       },
  { eng: "tomato",       esp: "tomate"        },
  { eng: "potato",       esp: "patata"        },
  { eng: "butter",       esp: "mantequilla"   },
  { eng: "sugar",        esp: "azúcar"        },
  { eng: "coffee",       esp: "café"          },
  { eng: "tea",          esp: "té"            },
  { eng: "juice",        esp: "jugo"          },
  { eng: "cake",         esp: "pastel"        },
  { eng: "wine",         esp: "vino"          },
  { eng: "beer",         esp: "cerveza"       },
  { eng: "salad",        esp: "ensalada"      },

  // Body / Cuerpo
  { eng: "head",         esp: "cabeza"        },
  { eng: "eye",          esp: "ojo"           },
  { eng: "nose",         esp: "nariz"         },
  { eng: "mouth",        esp: "boca"          },
  { eng: "ear",          esp: "oreja"         },
  { eng: "hand",         esp: "mano"          },
  { eng: "arm",          esp: "brazo"         },
  { eng: "leg",          esp: "pierna"        },
  { eng: "foot",         esp: "pie"           },
  { eng: "hair",         esp: "pelo"          },
  { eng: "heart",        esp: "corazón"       },
  { eng: "back",         esp: "espalda"       },

  // Home / Casa
  { eng: "house",        esp: "casa"          },
  { eng: "door",         esp: "puerta"        },
  { eng: "window",       esp: "ventana"       },
  { eng: "chair",        esp: "silla"         },
  { eng: "table",        esp: "mesa"          },
  { eng: "bed",          esp: "cama"          },
  { eng: "book",         esp: "libro"         },
  { eng: "pen",          esp: "bolígrafo"     },
  { eng: "bag",          esp: "bolsa"         },
  { eng: "clock",        esp: "reloj"         },
  { eng: "key",          esp: "llave"         },
  { eng: "phone",        esp: "teléfono"      },
  { eng: "lamp",         esp: "lámpara"       },
  { eng: "mirror",       esp: "espejo"        },
  { eng: "floor",        esp: "suelo"         },
  { eng: "wall",         esp: "pared"         },

  // Nature / Naturaleza
  { eng: "sun",          esp: "sol"           },
  { eng: "moon",         esp: "luna"          },
  { eng: "star",         esp: "estrella"      },
  { eng: "rain",         esp: "lluvia"        },
  { eng: "snow",         esp: "nieve"         },
  { eng: "sea",          esp: "mar"           },
  { eng: "river",        esp: "río"           },
  { eng: "tree",         esp: "árbol"         },
  { eng: "flower",       esp: "flor"          },
  { eng: "mountain",     esp: "montaña"       },
  { eng: "sky",          esp: "cielo"         },
  { eng: "wind",         esp: "viento"        },
  { eng: "cloud",        esp: "nube"          },
  { eng: "beach",        esp: "playa"         },

  // Adjectives / Adjetivos
  { eng: "big",          esp: "grande"        },
  { eng: "small",        esp: "pequeño"       },
  { eng: "long",         esp: "largo"         },
  { eng: "short",        esp: "corto"         },
  { eng: "fast",         esp: "rápido"        },
  { eng: "slow",         esp: "lento"         },
  { eng: "hot",          esp: "caliente"      },
  { eng: "cold",         esp: "frío"          },
  { eng: "happy",        esp: "feliz"         },
  { eng: "sad",          esp: "triste"        },
  { eng: "good",         esp: "bueno"         },
  { eng: "bad",          esp: "malo"          },
  { eng: "new",          esp: "nuevo"         },
  { eng: "old",          esp: "viejo"         },
  { eng: "easy",         esp: "fácil"         },
  { eng: "hard",         esp: "difícil"       },
  { eng: "clean",        esp: "limpio"        },
  { eng: "dirty",        esp: "sucio"         },
  { eng: "open",         esp: "abierto"       },
  { eng: "closed",       esp: "cerrado"       },
  { eng: "beautiful",    esp: "hermoso"       },
  { eng: "ugly",         esp: "feo"           },
  { eng: "tired",        esp: "cansado"       },
  { eng: "hungry",       esp: "hambriento"    },
  { eng: "thirsty",      esp: "sediento"      },

  // Basic Verbs / Verbos básicos
  { eng: "eat",          esp: "comer"         },
  { eng: "drink",        esp: "beber"         },
  { eng: "sleep",        esp: "dormir"        },
  { eng: "run",          esp: "correr"        },
  { eng: "walk",         esp: "caminar"       },
  { eng: "read",         esp: "leer"          },
  { eng: "write",        esp: "escribir"      },
  { eng: "play",         esp: "jugar"         },
  { eng: "listen",       esp: "escuchar"      },
  { eng: "look",         esp: "mirar"         },
  { eng: "sit",          esp: "sentarse"      },
  { eng: "come",         esp: "venir"         },
  { eng: "go",           esp: "ir"            },
  { eng: "open",         esp: "abrir"         },
  { eng: "close",        esp: "cerrar"        },
  { eng: "buy",          esp: "comprar"       },
  { eng: "give",         esp: "dar"           },
  { eng: "take",         esp: "tomar"         },
  { eng: "see",          esp: "ver"           },
  { eng: "speak",        esp: "hablar"        },
  { eng: "know",         esp: "saber"         },
  { eng: "want",         esp: "querer"        },
  { eng: "have",         esp: "tener"         },
  { eng: "need",         esp: "necesitar"     },
  { eng: "love",         esp: "amar"          },
  { eng: "work",         esp: "trabajar"      },
  { eng: "live",         esp: "vivir"         },
  { eng: "cook",         esp: "cocinar"       },
  { eng: "sing",         esp: "cantar"        },
  { eng: "dance",        esp: "bailar"        },
];