// ── Fiil Çekimleri Veri Seti ──
// Her obje: { soru, dogru, yanlis: [3 yanlış şık], ipucu }
// Soru türleri: base→past, past→base, özne+fiil çekimi, vs.

const FiilCekimleri = [
  // ── Düzensiz fiiller: base → past ──
  { soru: "\"know\" fiilinin geçmiş zaman hali nedir?", dogru: "knew", yanlis: ["knowed","known","knows"], ipucu: "know → knew → known" },
  { soru: "\"go\" fiilinin geçmiş zaman hali nedir?", dogru: "went", yanlis: ["goed","gone","goes"], ipucu: "go → went → gone" },
  { soru: "\"see\" fiilinin geçmiş zaman hali nedir?", dogru: "saw", yanlis: ["seed","seen","sees"], ipucu: "see → saw → seen" },
  { soru: "\"take\" fiilinin geçmiş zaman hali nedir?", dogru: "took", yanlis: ["taked","taken","takes"], ipucu: "take → took → taken" },
  { soru: "\"give\" fiilinin geçmiş zaman hali nedir?", dogru: "gave", yanlis: ["gived","given","gives"], ipucu: "give → gave → given" },
  { soru: "\"come\" fiilinin geçmiş zaman hali nedir?", dogru: "came", yanlis: ["comed","come","comes"], ipucu: "come → came → come" },
  { soru: "\"run\" fiilinin geçmiş zaman hali nedir?", dogru: "ran", yanlis: ["runned","run","runs"], ipucu: "run → ran → run" },
  { soru: "\"eat\" fiilinin geçmiş zaman hali nedir?", dogru: "ate", yanlis: ["eated","eaten","eats"], ipucu: "eat → ate → eaten" },
  { soru: "\"drink\" fiilinin geçmiş zaman hali nedir?", dogru: "drank", yanlis: ["drinked","drunk","drinks"], ipucu: "drink → drank → drunk" },
  { soru: "\"write\" fiilinin geçmiş zaman hali nedir?", dogru: "wrote", yanlis: ["writed","written","writes"], ipucu: "write → wrote → written" },
  { soru: "\"speak\" fiilinin geçmiş zaman hali nedir?", dogru: "spoke", yanlis: ["speaked","spoken","speaks"], ipucu: "speak → spoke → spoken" },
  { soru: "\"think\" fiilinin geçmiş zaman hali nedir?", dogru: "thought", yanlis: ["thinked","thunk","thinks"], ipucu: "think → thought → thought" },
  { soru: "\"bring\" fiilinin geçmiş zaman hali nedir?", dogru: "brought", yanlis: ["bringed","brung","brings"], ipucu: "bring → brought → brought" },
  { soru: "\"buy\" fiilinin geçmiş zaman hali nedir?", dogru: "bought", yanlis: ["buyed","buyd","buys"], ipucu: "buy → bought → bought" },
  { soru: "\"teach\" fiilinin geçmiş zaman hali nedir?", dogru: "taught", yanlis: ["teached","tought","teaches"], ipucu: "teach → taught → taught" },
  { soru: "\"catch\" fiilinin geçmiş zaman hali nedir?", dogru: "caught", yanlis: ["catched","cotched","catches"], ipucu: "catch → caught → caught" },
  { soru: "\"find\" fiilinin geçmiş zaman hali nedir?", dogru: "found", yanlis: ["finded","foud","finds"], ipucu: "find → found → found" },
  { soru: "\"leave\" fiilinin geçmiş zaman hali nedir?", dogru: "left", yanlis: ["leaved","leafed","leaves"], ipucu: "leave → left → left" },
  { soru: "\"meet\" fiilinin geçmiş zaman hali nedir?", dogru: "met", yanlis: ["meeted","mett","meets"], ipucu: "meet → met → met" },
  { soru: "\"lose\" fiilinin geçmiş zaman hali nedir?", dogru: "lost", yanlis: ["losed","losted","loses"], ipucu: "lose → lost → lost" },
  { soru: "\"send\" fiilinin geçmiş zaman hali nedir?", dogru: "sent", yanlis: ["sended","sened","sends"], ipucu: "send → sent → sent" },
  { soru: "\"sit\" fiilinin geçmiş zaman hali nedir?", dogru: "sat", yanlis: ["sitted","sut","sits"], ipucu: "sit → sat → sat" },
  { soru: "\"stand\" fiilinin geçmiş zaman hali nedir?", dogru: "stood", yanlis: ["standed","stond","stands"], ipucu: "stand → stood → stood" },
  { soru: "\"break\" fiilinin geçmiş zaman hali nedir?", dogru: "broke", yanlis: ["breaked","broken","breaks"], ipucu: "break → broke → broken" },
  { soru: "\"fall\" fiilinin geçmiş zaman hali nedir?", dogru: "fell", yanlis: ["falled","fallen","falls"], ipucu: "fall → fell → fallen" },
  { soru: "\"grow\" fiilinin geçmiş zaman hali nedir?", dogru: "grew", yanlis: ["growed","grown","grows"], ipucu: "grow → grew → grown" },
  { soru: "\"fly\" fiilinin geçmiş zaman hali nedir?", dogru: "flew", yanlis: ["flyed","flown","flies"], ipucu: "fly → flew → flown" },
  { soru: "\"sleep\" fiilinin geçmiş zaman hali nedir?", dogru: "slept", yanlis: ["sleeped","slapt","sleeps"], ipucu: "sleep → slept → slept" },
  { soru: "\"keep\" fiilinin geçmiş zaman hali nedir?", dogru: "kept", yanlis: ["keeped","kep","keeps"], ipucu: "keep → kept → kept" },
  { soru: "\"hear\" fiilinin geçmiş zaman hali nedir?", dogru: "heard", yanlis: ["heared","herd","hears"], ipucu: "hear → heard → heard" },
  { soru: "\"feel\" fiilinin geçmiş zaman hali nedir?", dogru: "felt", yanlis: ["feeled","feled","feels"], ipucu: "feel → felt → felt" },
  { soru: "\"tell\" fiilinin geçmiş zaman hali nedir?", dogru: "told", yanlis: ["telled","tolled","tells"], ipucu: "tell → told → told" },
  { soru: "\"sell\" fiilinin geçmiş zaman hali nedir?", dogru: "sold", yanlis: ["selled","solded","sells"], ipucu: "sell → sold → sold" },
  { soru: "\"hold\" fiilinin geçmiş zaman hali nedir?", dogru: "held", yanlis: ["holded","holt","holds"], ipucu: "hold → held → held" },
  { soru: "\"build\" fiilinin geçmiş zaman hali nedir?", dogru: "built", yanlis: ["builded","bild","builds"], ipucu: "build → built → built" },
  { soru: "\"spend\" fiilinin geçmiş zaman hali nedir?", dogru: "spent", yanlis: ["spended","spened","spends"], ipucu: "spend → spent → spent" },
  { soru: "\"win\" fiilinin geçmiş zaman hali nedir?", dogru: "won", yanlis: ["winned","wun","wins"], ipucu: "win → won → won" },
  { soru: "\"pay\" fiilinin geçmiş zaman hali nedir?", dogru: "paid", yanlis: ["payed","payd","pays"], ipucu: "pay → paid → paid" },
  { soru: "\"say\" fiilinin geçmiş zaman hali nedir?", dogru: "said", yanlis: ["sayed","sayd","says"], ipucu: "say → said → said" },
  { soru: "\"make\" fiilinin geçmiş zaman hali nedir?", dogru: "made", yanlis: ["maked","maded","makes"], ipucu: "make → made → made" },
  { soru: "\"begin\" fiilinin geçmiş zaman hali nedir?", dogru: "began", yanlis: ["beginned","begun","begins"], ipucu: "begin → began → begun" },
  { soru: "\"swim\" fiilinin geçmiş zaman hali nedir?", dogru: "swam", yanlis: ["swimmed","swum","swims"], ipucu: "swim → swam → swum" },
  { soru: "\"sing\" fiilinin geçmiş zaman hali nedir?", dogru: "sang", yanlis: ["singed","sung","sings"], ipucu: "sing → sang → sung" },
  { soru: "\"ring\" fiilinin geçmiş zaman hali nedir?", dogru: "rang", yanlis: ["ringed","rung","rings"], ipucu: "ring → rang → rung" },
  { soru: "\"drive\" fiilinin geçmiş zaman hali nedir?", dogru: "drove", yanlis: ["drived","driven","drives"], ipucu: "drive → drove → driven" },
  { soru: "\"choose\" fiilinin geçmiş zaman hali nedir?", dogru: "chose", yanlis: ["choosed","chosen","chooses"], ipucu: "choose → chose → chosen" },
  { soru: "\"freeze\" fiilinin geçmiş zaman hali nedir?", dogru: "froze", yanlis: ["freezed","frozen","freezes"], ipucu: "freeze → froze → frozen" },
  { soru: "\"steal\" fiilinin geçmiş zaman hali nedir?", dogru: "stole", yanlis: ["stealed","stolen","steals"], ipucu: "steal → stole → stolen" },
  { soru: "\"throw\" fiilinin geçmiş zaman hali nedir?", dogru: "threw", yanlis: ["throwed","thrown","throws"], ipucu: "throw → threw → thrown" },
  { soru: "\"blow\" fiilinin geçmiş zaman hali nedir?", dogru: "blew", yanlis: ["blowed","blown","blows"], ipucu: "blow → blew → blown" },

  // ── past → base (ters yön) ──
  { soru: "\"knew\" fiilinin kök hali (base form) nedir?", dogru: "know", yanlis: ["known","knews","knowed"], ipucu: "know → knew → known" },
  { soru: "\"went\" fiilinin kök hali nedir?", dogru: "go", yanlis: ["gone","goed","went"], ipucu: "go → went → gone" },
  { soru: "\"saw\" fiilinin kök hali nedir?", dogru: "see", yanlis: ["seen","sees","sea"], ipucu: "see → saw → seen" },
  { soru: "\"took\" fiilinin kök hali nedir?", dogru: "take", yanlis: ["taken","took","taked"], ipucu: "take → took → taken" },
  { soru: "\"thought\" fiilinin kök hali nedir?", dogru: "think", yanlis: ["thought","thinked","though"], ipucu: "think → thought → thought" },
  { soru: "\"brought\" fiilinin kök hali nedir?", dogru: "bring", yanlis: ["bought","broke","bringed"], ipucu: "bring → brought → brought" },
  { soru: "\"taught\" fiilinin kök hali nedir?", dogru: "teach", yanlis: ["tell","tought","thought"], ipucu: "teach → taught → taught" },
  { soru: "\"caught\" fiilinin kök hali nedir?", dogru: "catch", yanlis: ["cut","cough","cotch"], ipucu: "catch → caught → caught" },
  { soru: "\"bought\" fiilinin kök hali nedir?", dogru: "buy", yanlis: ["bring","brought","bid"], ipucu: "buy → bought → bought" },
  { soru: "\"told\" fiilinin kök hali nedir?", dogru: "tell", yanlis: ["toll","told","tale"], ipucu: "tell → told → told" },

  // ── Özne + present simple çekimi ──
  { soru: "\"She ___ (know) the answer.\" Boşluğa ne gelir?", dogru: "knows", yanlis: ["know","knowing","knowed"], ipucu: "He/She/It → fiile -s/-es eklenir" },
  { soru: "\"He ___ (go) to school every day.\" Boşluğa ne gelir?", dogru: "goes", yanlis: ["go","going","went"], ipucu: "go → goes (he/she/it için)" },
  { soru: "\"They ___ (run) every morning.\" Boşluğa ne gelir?", dogru: "run", yanlis: ["runs","running","ran"], ipucu: "They → fiil kök haliyle kalır" },
  { soru: "\"I ___ (have) two cats.\" Boşluğa ne gelir?", dogru: "have", yanlis: ["has","had","having"], ipucu: "I/You/We/They → have; He/She/It → has" },
  { soru: "\"She ___ (have) a red bag.\" Boşluğa ne gelir?", dogru: "has", yanlis: ["have","had","having"], ipucu: "He/She/It → has" },
  { soru: "\"We ___ (do) our homework.\" Boşluğa ne gelir?", dogru: "do", yanlis: ["does","did","doing"], ipucu: "We → do; He/She → does" },
  { soru: "\"He ___ (do) the dishes.\" Boşluğa ne gelir?", dogru: "does", yanlis: ["do","did","doing"], ipucu: "He/She/It → does" },

  // ── Özne + past simple çekimi ──
  { soru: "\"She ___ (see) a movie yesterday.\" Boşluğa ne gelir?", dogru: "saw", yanlis: ["seed","seen","sees"], ipucu: "Geçmiş zaman: see → saw" },
  { soru: "\"They ___ (eat) pizza last night.\" Boşluğa ne gelir?", dogru: "ate", yanlis: ["eated","eaten","eat"], ipucu: "Geçmiş zaman: eat → ate" },
  { soru: "\"He ___ (write) a letter.\" Boşluğa ne gelir?", dogru: "wrote", yanlis: ["writed","written","write"], ipucu: "Geçmiş zaman: write → wrote" },
  { soru: "\"I ___ (give) him a book.\" Boşluğa ne gelir?", dogru: "gave", yanlis: ["given","gived","give"], ipucu: "Geçmiş zaman: give → gave" },
  { soru: "\"We ___ (run) very fast.\" Boşluğa ne gelir?", dogru: "ran", yanlis: ["runned","run","runs"], ipucu: "Geçmiş zaman: run → ran" },
  { soru: "\"She ___ (speak) to the teacher.\" Boşluğa ne gelir?", dogru: "spoke", yanlis: ["speaked","spoken","speak"], ipucu: "Geçmiş zaman: speak → spoke" },
  { soru: "\"They ___ (drive) to Ankara.\" Boşluğa ne gelir?", dogru: "drove", yanlis: ["drived","driven","drive"], ipucu: "Geçmiş zaman: drive → drove" },
  { soru: "\"He ___ (break) the window.\" Boşluğa ne gelir?", dogru: "broke", yanlis: ["breaked","broken","break"], ipucu: "Geçmiş zaman: break → broke" },

  // ── Past participle (V3) soruları ──
  { soru: "\"know\" fiilinin V3 (past participle) hali nedir?", dogru: "known", yanlis: ["knew","knows","know"], ipucu: "know → knew → known" },
  { soru: "\"go\" fiilinin V3 hali nedir?", dogru: "gone", yanlis: ["went","goes","go"], ipucu: "go → went → gone" },
  { soru: "\"see\" fiilinin V3 hali nedir?", dogru: "seen", yanlis: ["saw","sees","sea"], ipucu: "see → saw → seen" },
  { soru: "\"take\" fiilinin V3 hali nedir?", dogru: "taken", yanlis: ["took","takes","take"], ipucu: "take → took → taken" },
  { soru: "\"write\" fiilinin V3 hali nedir?", dogru: "written", yanlis: ["wrote","writes","write"], ipucu: "write → wrote → written" },
  { soru: "\"give\" fiilinin V3 hali nedir?", dogru: "given", yanlis: ["gave","gives","give"], ipucu: "give → gave → given" },
  { soru: "\"eat\" fiilinin V3 hali nedir?", dogru: "eaten", yanlis: ["ate","eats","eat"], ipucu: "eat → ate → eaten" },
  { soru: "\"break\" fiilinin V3 hali nedir?", dogru: "broken", yanlis: ["broke","breaks","break"], ipucu: "break → broke → broken" },
  { soru: "\"drive\" fiilinin V3 hali nedir?", dogru: "driven", yanlis: ["drove","drives","drive"], ipucu: "drive → drove → driven" },
  { soru: "\"speak\" fiilinin V3 hali nedir?", dogru: "spoken", yanlis: ["spoke","speaks","speak"], ipucu: "speak → spoke → spoken" },
  { soru: "\"fall\" fiilinin V3 hali nedir?", dogru: "fallen", yanlis: ["fell","falls","fall"], ipucu: "fall → fell → fallen" },
  { soru: "\"grow\" fiilinin V3 hali nedir?", dogru: "grown", yanlis: ["grew","grows","grow"], ipucu: "grow → grew → grown" },
  { soru: "\"fly\" fiilinin V3 hali nedir?", dogru: "flown", yanlis: ["flew","flies","fly"], ipucu: "fly → flew → flown" },
  { soru: "\"begin\" fiilinin V3 hali nedir?", dogru: "begun", yanlis: ["began","begins","begin"], ipucu: "begin → began → begun" },
  { soru: "\"swim\" fiilinin V3 hali nedir?", dogru: "swum", yanlis: ["swam","swims","swim"], ipucu: "swim → swam → swum" },
  { soru: "\"sing\" fiilinin V3 hali nedir?", dogru: "sung", yanlis: ["sang","sings","sing"], ipucu: "sing → sang → sung" },
  { soru: "\"drink\" fiilinin V3 hali nedir?", dogru: "drunk", yanlis: ["drank","drinks","drink"], ipucu: "drink → drank → drunk" },
  { soru: "\"ring\" fiilinin V3 hali nedir?", dogru: "rung", yanlis: ["rang","rings","ring"], ipucu: "ring → rang → rung" },
  { soru: "\"choose\" fiilinin V3 hali nedir?", dogru: "chosen", yanlis: ["chose","chooses","choose"], ipucu: "choose → chose → chosen" },
  { soru: "\"steal\" fiilinin V3 hali nedir?", dogru: "stolen", yanlis: ["stole","steals","steal"], ipucu: "steal → stole → stolen" },
  { soru: "\"throw\" fiilinin V3 hali nedir?", dogru: "thrown", yanlis: ["threw","throws","throw"], ipucu: "throw → threw → thrown" },
  { soru: "\"blow\" fiilinin V3 hali nedir?", dogru: "blown", yanlis: ["blew","blows","blow"], ipucu: "blow → blew → blown" },
  { soru: "\"freeze\" fiilinin V3 hali nedir?", dogru: "frozen", yanlis: ["froze","freezes","freeze"], ipucu: "freeze → froze → frozen" },
];