// ─────────────────────────────────────────────
//  kelimeB.js  ·  Orta Kelimeler  (B Seviyesi)
//  Format: { eng: "word", tr: "karşılık" }
// ─────────────────────────────────────────────

var KelimeBListesi = [
  { eng: "anxious",      tr: "endişeli"       },
  { eng: "confident",    tr: "kendinden emin" },
  { eng: "curious",      tr: "meraklı"        },
  { eng: "frustrated",   tr: "sinirlenmiş"    },
  { eng: "grateful",     tr: "minnettar"      },
  { eng: "jealous",      tr: "kıskanç"        },
  { eng: "lonely",       tr: "yalnız"         },
  { eng: "nervous",      tr: "gergin"         },
  { eng: "patient",      tr: "sabırlı"        },
  { eng: "proud",        tr: "gururlu"        },
  { eng: "relieved",     tr: "rahatlamış"     },
  { eng: "stubborn",     tr: "inatçı"         },
  { eng: "suspicious",   tr: "şüpheci"        },
  { eng: "cheerful",     tr: "neşeli"         },
  { eng: "generous",     tr: "cömert"         },
  { eng: "accountant",   tr: "muhasebeci"     },
  { eng: "architect",    tr: "mimar"          },
  { eng: "colleague",    tr: "meslektaş"      },
  { eng: "deadline",     tr: "son tarih"      },
  { eng: "employee",     tr: "çalışan"        },
  { eng: "employer",     tr: "işveren"        },
  { eng: "interview",    tr: "mülakat"        },
  { eng: "manager",      tr: "yönetici"       },
  { eng: "negotiate",    tr: "müzakere etmek" },
  { eng: "promote",      tr: "terfi ettirmek" },
  { eng: "resign",       tr: "istifa etmek"   },
  { eng: "salary",       tr: "maaş"           },
  { eng: "profession",   tr: "meslek"         },
  { eng: "career",       tr: "kariyer"        },
  { eng: "contract",     tr: "sözleşme"       },
  { eng: "application",  tr: "uygulama"       },
  { eng: "browser",      tr: "tarayıcı"       },
  { eng: "database",     tr: "veri tabanı"    },
  { eng: "download",     tr: "indirmek"       },
  { eng: "hardware",     tr: "donanım"        },
  { eng: "network",      tr: "ağ"             },
  { eng: "password",     tr: "şifre"          },
  { eng: "software",     tr: "yazılım"        },
  { eng: "upload",       tr: "yüklemek"       },
  { eng: "wireless",     tr: "kablosuz"       },
  { eng: "device",       tr: "cihaz"          },
  { eng: "screen",       tr: "ekran"          },
  { eng: "update",       tr: "güncelleme"     },
  { eng: "backup",       tr: "yedek"          },
  { eng: "virus",        tr: "virüs"          },
  { eng: "allergy",      tr: "alerji"         },
  { eng: "diagnosis",    tr: "teşhis"         },
  { eng: "fever",        tr: "ateş"           },
  { eng: "headache",     tr: "baş ağrısı"     },
  { eng: "injection",    tr: "iğne / enjeksiyon"},
  { eng: "medicine",     tr: "ilaç"           },
  { eng: "operation",    tr: "ameliyat"       },
  { eng: "patient",      tr: "hasta"          },
  { eng: "prescription", tr: "reçete"         },
  { eng: "symptom",      tr: "belirti"        },
  { eng: "treatment",    tr: "tedavi"         },
  { eng: "vaccine",      tr: "aşı"            },
  { eng: "pharmacy",     tr: "eczane"         },
  { eng: "emergency",    tr: "acil durum"     },
  { eng: "surgeon",      tr: "cerrah"         },
  { eng: "atmosphere",   tr: "atmosfer"       },
  { eng: "climate",      tr: "iklim"          },
  { eng: "drought",      tr: "kuraklık"       },
  { eng: "earthquake",   tr: "deprem"         },
  { eng: "ecosystem",    tr: "ekosistem"      },
  { eng: "endangered",   tr: "nesli tehlike altında"},
  { eng: "flood",        tr: "sel"            },
  { eng: "pollution",    tr: "kirlilik"       },
  { eng: "recycle",      tr: "geri dönüştürmek"},
  { eng: "renewable",    tr: "yenilenebilir"  },
  { eng: "species",      tr: "tür"            },
  { eng: "sustainable",  tr: "sürdürülebilir" },
  { eng: "wildlife",     tr: "yaban hayatı"   },
  { eng: "fossil",       tr: "fosil"          },
  { eng: "extinct",      tr: "soyu tükenmiş"  },
  { eng: "assignment",   tr: "ödev"           },
  { eng: "certificate",  tr: "sertifika"      },
  { eng: "curriculum",   tr: "müfredat"       },
  { eng: "discipline",   tr: "disiplin"       },
  { eng: "graduate",     tr: "mezun olmak"    },
  { eng: "lecture",      tr: "ders / konferans"},
  { eng: "scholarship",  tr: "burs"           },
  { eng: "semester",     tr: "dönem / sömestr"},
  { eng: "thesis",       tr: "tez"            },
  { eng: "tuition",      tr: "öğretim ücreti" },
  { eng: "evaluate",     tr: "değerlendirmek" },
  { eng: "knowledge",    tr: "bilgi"          },
  { eng: "research",     tr: "araştırma"      },
  { eng: "publication",  tr: "yayın"          },
  { eng: "academic",     tr: "akademik"       },
  { eng: "campaign",     tr: "kampanya"       },
  { eng: "citizen",      tr: "vatandaş"       },
  { eng: "conflict",     tr: "çatışma"        },
  { eng: "democracy",    tr: "demokrasi"      },
  { eng: "economy",      tr: "ekonomi"        },
  { eng: "election",     tr: "seçim"          },
  { eng: "equality",     tr: "eşitlik"        },
  { eng: "government",   tr: "hükümet"        },
  { eng: "immigration",  tr: "göç"            },
  { eng: "justice",      tr: "adalet"         },
  { eng: "law",          tr: "kanun"          },
  { eng: "minority",     tr: "azınlık"        },
  { eng: "protest",      tr: "protesto"       },
  { eng: "revolution",   tr: "devrim"         },
  { eng: "society",      tr: "toplum"         },
  { eng: "budget",       tr: "bütçe"          },
  { eng: "debt",         tr: "borç"           },
  { eng: "dividend",     tr: "temettü"        },
  { eng: "export",       tr: "ihracat"        },
  { eng: "import",       tr: "ithalat"        },
  { eng: "inflation",    tr: "enflasyon"      },
  { eng: "invest",       tr: "yatırım yapmak" },
  { eng: "loan",         tr: "kredi"          },
  { eng: "profit",       tr: "kâr"            },
  { eng: "revenue",      tr: "gelir"          },
  { eng: "stock",        tr: "hisse senedi"   },
  { eng: "tax",          tr: "vergi"          },
  { eng: "trade",        tr: "ticaret"        },
  { eng: "bankrupt",     tr: "iflas etmiş"    },
  { eng: "currency",     tr: "para birimi"    },
  { eng: "accomplish",   tr: "başarmak"       },
  { eng: "analyze",      tr: "analiz etmek"   },
  { eng: "argue",        tr: "tartışmak"      },
  { eng: "concentrate",  tr: "konsantre olmak"},
  { eng: "convince",     tr: "ikna etmek"     },
  { eng: "describe",     tr: "tanımlamak"     },
  { eng: "develop",      tr: "geliştirmek"    },
  { eng: "distinguish",  tr: "ayırt etmek"    },
  { eng: "encourage",    tr: "teşvik etmek"   },
  { eng: "establish",    tr: "kurmak"         },
  { eng: "estimate",     tr: "tahmin etmek"   },
  { eng: "emphasize",    tr: "vurgulamak"     },
  { eng: "implement",    tr: "uygulamak"      },
  { eng: "interpret",    tr: "yorumlamak"     },
  { eng: "maintain",     tr: "sürdürmek"      },
  { eng: "obtain",       tr: "elde etmek"     },
  { eng: "overcome",     tr: "aşmak"          },
  { eng: "participate",  tr: "katılmak"       },
  { eng: "recognize",    tr: "tanımak"        },
  { eng: "represent",    tr: "temsil etmek"   },
  { eng: "ability", tr: "yetenek" },
  { eng: "accept", tr: "kabul etmek" },
  { eng: "accident", tr: "kaza" },
  { eng: "achieve", tr: "başarmak" },
  { eng: "act", tr: "davranmak" },
  { eng: "active", tr: "aktif" },
  { eng: "activity", tr: "aktivite" },
  { eng: "adult", tr: "yetişkin" },
  { eng: "advice", tr: "tavsiye" },
  { eng: "advise", tr: "tavsiye etmek" },
  { eng: "afford", tr: "karşılayabilmek" },
  { eng: "against", tr: "karşı" },
  { eng: "agent", tr: "ajan" },
  { eng: "alive", tr: "canlı" },
  { eng: "allow", tr: "izin vermek" },
  { eng: "almost", tr: "neredeyse" },
  { eng: "alone", tr: "yalnız" },
  { eng: "already", tr: "zaten" },
  { eng: "although", tr: "rağmen" },
  { eng: "amazing", tr: "şaşırtıcı" },
  { eng: "amount", tr: "miktar" },
  { eng: "ancient", tr: "antik" },
  { eng: "angry", tr: "sinirli" },
  { eng: "announce", tr: "duyurmak" },
  { eng: "annoying", tr: "sinir bozucu" },
  { eng: "appear", tr: "ortaya çıkmak" },
  { eng: "appearance", tr: "görünüş" },
  { eng: "apply", tr: "başvurmak" },
  { eng: "argue", tr: "tartışmak" },
  { eng: "army", tr: "ordu" },
  { eng: "arrange", tr: "düzenlemek" },
  { eng: "article", tr: "makale" },
  { eng: "artist", tr: "sanatçı" },
  { eng: "asleep", tr: "uykuda" },
  { eng: "assistant", tr: "asistan" },
  { eng: "attack", tr: "saldırmak" },
  { eng: "attend", tr: "katılmak" },
  { eng: "attention", tr: "dikkat" },
  { eng: "attract", tr: "çekmek" },
  { eng: "audience", tr: "seyirci" },
  { eng: "available", tr: "mevcut" },
  { eng: "avoid", tr: "kaçınmak" },
  { eng: "award", tr: "ödül" },
  { eng: "awful", tr: "berbat" },
  { eng: "background", tr: "arka plan" },
  { eng: "balance", tr: "denge" },
  { eng: "basic", tr: "temel" },
  { eng: "battle", tr: "savaş" },
  { eng: "beauty", tr: "güzellik" },
  { eng: "belong", tr: "ait olmak" },
  { eng: "belt", tr: "kemer" },
  { eng: "benefit", tr: "fayda" },
  { eng: "block", tr: "engellemek" },
  { eng: "blood", tr: "kan" },
  { eng: "board", tr: "tahta" },
  { eng: "brain", tr: "beyin" },
  { eng: "brave", tr: "cesur" },
  { eng: "breath", tr: "nefes" },
  { eng: "breathe", tr: "nefes almak" },
  { eng: "bridge", tr: "köprü" },
  { eng: "bright", tr: "parlak" },
  { eng: "broken", tr: "kırık" },
  { eng: "brush", tr: "fırçalamak" },
  { eng: "burn", tr: "yanmak" },
  { eng: "businessman", tr: "iş adamı" },
  { eng: "calm", tr: "sakin" },
  { eng: "campaign", tr: "kampanya" },
  { eng: "cancel", tr: "iptal etmek" },
  { eng: "care", tr: "önem vermek" },
  { eng: "career", tr: "kariyer" },
  { eng: "careful", tr: "dikkatli" },
  { eng: "carpet", tr: "halı" },
  { eng: "carry", tr: "taşımak" },
  { eng: "case", tr: "durum" },
  { eng: "cash", tr: "nakit" },
  { eng: "cause", tr: "sebep olmak" },
  { eng: "celebrate", tr: "kutlamak" },
  { eng: "certain", tr: "emin" },
  { eng: "challenge", tr: "meydan okuma" },
  { eng: "chance", tr: "şans" },
  { eng: "character", tr: "karakter" },
  { eng: "charge", tr: "şarj etmek" },
  { eng: "choice", tr: "seçim" },
  { eng: "citizen", tr: "vatandaş" },
  { eng: "clearly", tr: "açıkça" },
  { eng: "clever", tr: "zeki" },
  { eng: "climate", tr: "iklim" },
  { eng: "close", tr: "yakın" },
  { eng: "coach", tr: "antrenör" },
  { eng: "collect", tr: "toplamak" },
  { eng: "comfortable", tr: "rahat" },
  { eng: "comment", tr: "yorum" },
  { eng: "communicate", tr: "iletişim kurmak" },
  { eng: "community", tr: "topluluk" },
  { eng: "compare", tr: "karşılaştırmak" },
  { eng: "compete", tr: "rekabet etmek" },
  { eng: "complain", tr: "şikayet etmek" },
  { eng: "complete", tr: "tamamlamak" },
  { eng: "condition", tr: "durum" },
  { eng: "conference", tr: "konferans" },
  { eng: "confused", tr: "kafası karışmış" },
  { eng: "connect", tr: "bağlamak" },
  { eng: "consider", tr: "düşünmek" },
  { eng: "contact", tr: "iletişim" },
  { eng: "contain", tr: "içermek" },
  { eng: "continue", tr: "devam etmek" },
  { eng: "control", tr: "kontrol etmek" },
  { eng: "conversation", tr: "konuşma" },
  { eng: "corner", tr: "köşe" },
  { eng: "correctly", tr: "doğru şekilde" },
  { eng: "count", tr: "saymak" },
  { eng: "couple", tr: "çift" },
  { eng: "cover", tr: "kaplamak" },
  { eng: "crazy", tr: "çılgın" },
  { eng: "creative", tr: "yaratıcı" },
  { eng: "crime", tr: "suç" },
  { eng: "crowd", tr: "kalabalık" },
  { eng: "culture", tr: "kültür" },
  { eng: "curious", tr: "meraklı" },
  { eng: "customer", tr: "müşteri" },
  { eng: "damage", tr: "hasar" },
  { eng: "danger", tr: "tehlike" },
  { eng: "dead", tr: "ölü" },
  { eng: "deal", tr: "anlaşma" },
  { eng: "decide", tr: "karar vermek" },
  { eng: "deep", tr: "derin" },
  { eng: "defend", tr: "savunmak" },
  { eng: "degree", tr: "derece" },
  { eng: "deliver", tr: "teslim etmek" },
  { eng: "demand", tr: "talep etmek" },
  { eng: "depend", tr: "bağlı olmak" },
  { eng: "describe", tr: "tanımlamak" },
  { eng: "design", tr: "tasarlamak" },
  { eng: "destroy", tr: "yok etmek" },
  { eng: "develop", tr: "geliştirmek" },
  { eng: "development", tr: "gelişim" },
  { eng: "device", tr: "cihaz" },
  { eng: "diet", tr: "diyet" },
  { eng: "difference", tr: "fark" },
  { eng: "difficult", tr: "zor" },
  { eng: "direct", tr: "yönlendirmek" },
  { eng: "direction", tr: "yön" },
  { eng: "disappear", tr: "kaybolmak" },
  { eng: "discover", tr: "keşfetmek" },
  { eng: "discussion", tr: "tartışma" },
  { eng: "disease", tr: "hastalık" },
  { eng: "distance", tr: "mesafe" },
  { eng: "divide", tr: "bölmek" },
  { eng: "double", tr: "iki kat" },
  { eng: "dream", tr: "hayal kurmak" },
  { eng: "dress", tr: "giyinmek" },
  { eng: "drop", tr: "düşürmek" },
  { eng: "drug", tr: "ilaç" },
  { eng: "during", tr: "boyunca" },
  { eng: "earn", tr: "kazanmak" },
  { eng: "earth", tr: "dünya" },
  { eng: "education", tr: "eğitim" },
  { eng: "effect", tr: "etki" },
  { eng: "effort", tr: "çaba" },
  { eng: "election", tr: "seçim" },
  { eng: "employee", tr: "çalışan" },
  { eng: "employer", tr: "işveren" },
  { eng: "empty", tr: "boş" },
  { eng: "encourage", tr: "teşvik etmek" },
  { eng: "enemy", tr: "düşman" },
  { eng: "energy", tr: "enerji" },
  { eng: "engine", tr: "motor" },
  { eng: "enjoy", tr: "keyif almak" },
  { eng: "enormous", tr: "muazzam" },
  { eng: "environment", tr: "çevre" },
  { eng: "equal", tr: "eşit" },
  { eng: "especially", tr: "özellikle" },
  { eng: "event", tr: "etkinlik" },
  { eng: "everyday", tr: "günlük" },
  { eng: "evidence", tr: "kanıt" },
  { eng: "exact", tr: "tam" },
  { eng: "excellent", tr: "mükemmel" },
  { eng: "except", tr: "hariç" },
  { eng: "exchange", tr: "değiş tokuş" },
  { eng: "excuse", tr: "bahane" },
  { eng: "exercise", tr: "egzersiz" },
  { eng: "exist", tr: "var olmak" },
  { eng: "expect", tr: "beklemek" },
  { eng: "experience", tr: "deneyim" },
  { eng: "expert", tr: "uzman" },
  { eng: "explain", tr: "açıklamak" },
  { eng: "express", tr: "ifade etmek" },
  { eng: "extra", tr: "ekstra" },
  { eng: "factory", tr: "fabrika" },
  { eng: "fail", tr: "başarısız olmak" },
  { eng: "fair", tr: "adil" },
  { eng: "familiar", tr: "tanıdık" },
  { eng: "fancy", tr: "şık" },
  { eng: "fashion", tr: "moda" },
  { eng: "fear", tr: "korku" },
  { eng: "feature", tr: "özellik" },
  { eng: "feed", tr: "beslemek" },
  { eng: "female", tr: "kadın" },
  { eng: "fiction", tr: "kurgu" },
  { eng: "field", tr: "alan" },
  { eng: "fight", tr: "kavga etmek" },
  { eng: "final", tr: "son" },
  { eng: "finally", tr: "sonunda" },
  { eng: "finger", tr: "parmak" },
  { eng: "flight", tr: "uçuş" },
  { eng: "focus", tr: "odaklanmak" },
  { eng: "follow", tr: "takip etmek" },
  { eng: "foreign", tr: "yabancı" },
  { eng: "forever", tr: "sonsuzca" },
  { eng: "formal", tr: "resmi" },
  { eng: "forward", tr: "ileri" },
  { eng: "freeze", tr: "donmak" },
  { eng: "freedom", tr: "özgürlük" },
  { eng: "frightened", tr: "korkmuş" },
  { eng: "funeral", tr: "cenaze" },
  { eng: "future", tr: "gelecek" },
    { eng: "gain", tr: "kazanmak" },
  { eng: "garbage", tr: "çöp" },
  { eng: "general", tr: "genel" },
  { eng: "generous", tr: "cömert" },
  { eng: "gentle", tr: "nazik" },
  { eng: "government", tr: "hükümet" },
  { eng: "graduate", tr: "mezun olmak" },
  { eng: "grain", tr: "tahıl" },
  { eng: "grateful", tr: "minnettar" },
  { eng: "greedy", tr: "açgözlü" },
  { eng: "ground", tr: "zemin" },
  { eng: "guard", tr: "korumak" },
  { eng: "guess", tr: "tahmin etmek" },
  { eng: "guest", tr: "misafir" },
  { eng: "guide", tr: "rehber" },
  { eng: "habit", tr: "alışkanlık" },
  { eng: "hall", tr: "salon" },
  { eng: "handle", tr: "idare etmek" },
  { eng: "harm", tr: "zarar vermek" },
  { eng: "hate", tr: "nefret etmek" },
  { eng: "health", tr: "sağlık" },
  { eng: "heat", tr: "ısı" },
  { eng: "heavy", tr: "ağır" },
  { eng: "height", tr: "yükseklik" },
  { eng: "heroic", tr: "kahramanca" },
  { eng: "hesitate", tr: "tereddüt etmek" },
  { eng: "hide", tr: "saklanmak" },
  { eng: "highly", tr: "oldukça" },
  { eng: "hire", tr: "işe almak" },
  { eng: "historical", tr: "tarihi" },
  { eng: "honest", tr: "dürüst" },
  { eng: "honor", tr: "onur" },
  { eng: "horrible", tr: "korkunç" },
  { eng: "host", tr: "ev sahibi" },
  { eng: "however", tr: "ancak" },
  { eng: "huge", tr: "devasa" },
  { eng: "humor", tr: "mizah" },
  { eng: "hunt", tr: "avlamak" },
  { eng: "hurry", tr: "acele etmek" },
  { eng: "identity", tr: "kimlik" },
  { eng: "ignore", tr: "görmezden gelmek" },
  { eng: "illegal", tr: "yasadışı" },
  { eng: "imagine", tr: "hayal etmek" },
  { eng: "immediate", tr: "acil" },
  { eng: "immigrant", tr: "göçmen" },
  { eng: "impact", tr: "etki" },
  { eng: "impatient", tr: "sabırsız" },
  { eng: "import", tr: "ithal etmek" },
  { eng: "importance", tr: "önem" },
  { eng: "impress", tr: "etkilemek" },
  { eng: "improve", tr: "geliştirmek" },
  { eng: "include", tr: "içermek" },
  { eng: "income", tr: "gelir" },
  { eng: "increase", tr: "artırmak" },
  { eng: "indeed", tr: "gerçekten" },
  { eng: "independent", tr: "bağımsız" },
  { eng: "industry", tr: "endüstri" },
  { eng: "infect", tr: "enfekte etmek" },
  { eng: "influence", tr: "etkilemek" },
  { eng: "inform", tr: "bilgilendirmek" },
  { eng: "injury", tr: "yaralanma" },
  { eng: "insect", tr: "böcek" },
  { eng: "inside", tr: "içeride" },
  { eng: "insist", tr: "ısrar etmek" },
  { eng: "instead", tr: "yerine" },
  { eng: "intelligence", tr: "zeka" },
  { eng: "intend", tr: "niyet etmek" },
  { eng: "international", tr: "uluslararası" },
  { eng: "interrupt", tr: "bölmek" },
  { eng: "interview", tr: "mülakat" },
  { eng: "introduce", tr: "tanıtmak" },
  { eng: "invent", tr: "icat etmek" },
  { eng: "invite", tr: "davet etmek" },
  { eng: "involve", tr: "içermek" },
  { eng: "issue", tr: "sorun" },
  { eng: "item", tr: "eşya" },
  { eng: "jail", tr: "hapishane" },
  { eng: "jealous", tr: "kıskanç" },
  { eng: "jewel", tr: "mücevher" },
  { eng: "journey", tr: "yolculuk" },
  { eng: "judge", tr: "yargıç" },
  { eng: "justice", tr: "adalet" },
  { eng: "kick", tr: "tekmelemek" },
  { eng: "kidnap", tr: "kaçırmak" },
  { eng: "kill", tr: "öldürmek" },
  { eng: "kindness", tr: "iyilik" },
  { eng: "knowledge", tr: "bilgi" },
  { eng: "labor", tr: "emek" },
  { eng: "lack", tr: "eksiklik" },
  { eng: "land", tr: "toprak" },
  { eng: "latest", tr: "en son" },
  { eng: "lawyer", tr: "avukat" },
  { eng: "lead", tr: "liderlik etmek" },
  { eng: "leader", tr: "lider" },
  { eng: "legal", tr: "yasal" },
  { eng: "leisure", tr: "boş zaman" },
  { eng: "length", tr: "uzunluk" },
  { eng: "level", tr: "seviye" },
  { eng: "library", tr: "kütüphane" },
  { eng: "license", tr: "lisans" },
  { eng: "likely", tr: "muhtemel" },
  { eng: "limit", tr: "sınır" },
  { eng: "link", tr: "bağlantı" },
  { eng: "liquid", tr: "sıvı" },
  { eng: "literature", tr: "edebiyat" },
  { eng: "local", tr: "yerel" },
  { eng: "locate", tr: "yerini bulmak" },
  { eng: "lonely", tr: "yalnız" },
  { eng: "loudly", tr: "yüksek sesle" },
  { eng: "luxury", tr: "lüks" },
  { eng: "mad", tr: "deli" },
  { eng: "magic", tr: "sihir" },
  { eng: "mainly", tr: "çoğunlukla" },
  { eng: "major", tr: "önemli" },
  { eng: "male", tr: "erkek" },
  { eng: "manage", tr: "yönetmek" },
  { eng: "manner", tr: "davranış biçimi" },
  { eng: "mark", tr: "işaretlemek" },
  { eng: "marriage", tr: "evlilik" },
  { eng: "mass", tr: "kitle" },
  { eng: "master", tr: "usta" },
  { eng: "material", tr: "malzeme" },
  { eng: "measure", tr: "ölçmek" },
  { eng: "medical", tr: "tıbbi" },
  { eng: "mental", tr: "zihinsel" },
  { eng: "mention", tr: "bahsetmek" },
  { eng: "method", tr: "yöntem" },
  { eng: "middle", tr: "orta" },
  { eng: "military", tr: "askeri" },
  { eng: "mind", tr: "zihin" },
  { eng: "miner", tr: "madenci" },
  { eng: "mirror", tr: "ayna" },
  { eng: "mix", tr: "karıştırmak" },
  { eng: "model", tr: "model" },
  { eng: "modern", tr: "modern" },
  { eng: "modify", tr: "değiştirmek" },
  { eng: "moment", tr: "an" },
  { eng: "monster", tr: "canavar" },
  { eng: "mood", tr: "ruh hali" },
  { eng: "moral", tr: "ahlaki" },
  { eng: "motorcycle", tr: "motosiklet" },
  { eng: "mount", tr: "tırmanmak" },
  { eng: "murder", tr: "cinayet" },
  { eng: "muscle", tr: "kas" },
  { eng: "mysterious", tr: "gizemli" },
  { eng: "narrow", tr: "dar" },
  { eng: "nation", tr: "ulus" },
  { eng: "native", tr: "yerli" },
  { eng: "nature", tr: "doğa" },
  { eng: "neighbor", tr: "komşu" },
  { eng: "neither", tr: "hiçbiri" },
  { eng: "nervous", tr: "gergin" },
  { eng: "network", tr: "ağ" },
  { eng: "noise", tr: "gürültü" },
  { eng: "normal", tr: "normal" },
  { eng: "notice", tr: "fark etmek" },
  { eng: "nowadays", tr: "günümüzde" },
  { eng: "nuclear", tr: "nükleer" },
  { eng: "obey", tr: "itaat etmek" },
  { eng: "object", tr: "nesne" },
  { eng: "observe", tr: "gözlemlemek" },
  { eng: "obvious", tr: "açık" },
  { eng: "occasion", tr: "fırsat" },
  { eng: "occupy", tr: "işgal etmek" },
  { eng: "occur", tr: "meydana gelmek" },
  { eng: "ocean", tr: "okyanus" },
  { eng: "offend", tr: "gücendirmek" },
  { eng: "offer", tr: "teklif etmek" },
  { eng: "official", tr: "resmi" },
  { eng: "operation", tr: "operasyon" },
  { eng: "opinion", tr: "görüş" },
  { eng: "opportunity", tr: "fırsat" },
  { eng: "ordinary", tr: "sıradan" },
  { eng: "organize", tr: "organize etmek" },
  { eng: "original", tr: "orijinal" },
  { eng: "otherwise", tr: "aksi takdirde" },
  { eng: "outdoor", tr: "açık hava" },
  { eng: "outer", tr: "dış" },
  { eng: "owner", tr: "sahip" },
  { eng: "package", tr: "paket" },
  { eng: "painful", tr: "acı verici" },
  { eng: "palace", tr: "saray" },
  { eng: "participate", tr: "katılmak" },
  { eng: "particular", tr: "belirli" },
  { eng: "passenger", tr: "yolcu" },
  { eng: "patient", tr: "hasta" },
  { eng: "pattern", tr: "desen" },
  { eng: "peaceful", tr: "huzurlu" },
  { eng: "performance", tr: "performans" },
  { eng: "permission", tr: "izin" },
  { eng: "personality", tr: "kişilik" },
  { eng: "persuade", tr: "ikna etmek" },
  { eng: "photograph", tr: "fotoğraf" },
  { eng: "physical", tr: "fiziksel" },
  { eng: "planet", tr: "gezegen" },
  { eng: "plastic", tr: "plastik" },
  { eng: "pleasant", tr: "hoş" },
  { eng: "pleasure", tr: "zevk" },
  { eng: "plenty", tr: "bol miktarda" },
  { eng: "poison", tr: "zehir" },
  { eng: "political", tr: "politik" },
  { eng: "population", tr: "nüfus" },
  { eng: "position", tr: "pozisyon" },
  { eng: "possibility", tr: "olasılık" },
  { eng: "powerful", tr: "güçlü" },
  { eng: "practical", tr: "pratik" },
  { eng: "praise", tr: "övmek" },
  { eng: "precious", tr: "değerli" },
  { eng: "predict", tr: "tahmin etmek" },
  { eng: "prefer", tr: "tercih etmek" },
  { eng: "prepare", tr: "hazırlamak" },
  { eng: "presence", tr: "varlık" },
  { eng: "prevent", tr: "önlemek" },
  { eng: "pride", tr: "gurur" },
  { eng: "primary", tr: "birincil" },
  { eng: "prison", tr: "hapishane" },
  { eng: "private", tr: "özel" },
  { eng: "produce", tr: "üretmek" },
  { eng: "profession", tr: "meslek" },
  { eng: "profit", tr: "kar" },
  { eng: "program", tr: "program" },
  { eng: "project", tr: "proje" },
  { eng: "promise", tr: "söz vermek" },
  { eng: "protect", tr: "korumak" },
  { eng: "proud", tr: "gururlu" },
  { eng: "prove", tr: "kanıtlamak" },
  { eng: "publish", tr: "yayınlamak" },
  { eng: "punish", tr: "cezalandırmak" },
  { eng: "quality", tr: "kalite" },
  { eng: "quantity", tr: "miktar" },
  { eng: "quarter", tr: "çeyrek" },
  { eng: "quit", tr: "bırakmak" },
  { eng: "raise", tr: "yükseltmek" },
  { eng: "rare", tr: "nadir" },
  { eng: "rate", tr: "oran" },
  { eng: "reach", tr: "ulaşmak" },
  { eng: "react", tr: "tepki vermek" },
  { eng: "realize", tr: "farkına varmak" },
  { eng: "reason", tr: "sebep" },
  { eng: "receive", tr: "almak" },
  { eng: "recent", tr: "yakın tarihli" },
  { eng: "recognize", tr: "tanımak" },
  { eng: "recommend", tr: "önermek" },
  { eng: "recover", tr: "iyileşmek" },
  { eng: "reduce", tr: "azaltmak" },
  { eng: "refer", tr: "bahsetmek" },
  { eng: "reflect", tr: "yansıtmak" },
  { eng: "refuse", tr: "reddetmek" },
  { eng: "regret", tr: "pişman olmak" },
  { eng: "regular", tr: "düzenli" },
  { eng: "reject", tr: "reddetmek" },
  { eng: "relationship", tr: "ilişki" },
  { eng: "relax", tr: "rahatlamak" },
  { eng: "release", tr: "serbest bırakmak" },
  { eng: "reliable", tr: "güvenilir" },
  { eng: "remain", tr: "kalmak" },
  { eng: "remind", tr: "hatırlatmak" },
  { eng: "remove", tr: "kaldırmak" },
  { eng: "repair", tr: "tamir etmek" },
  { eng: "repeat", tr: "tekrarlamak" },
  { eng: "replace", tr: "yerine koymak" },
  { eng: "reply", tr: "yanıtlamak" },
  { eng: "report", tr: "rapor etmek" },
  { eng: "request", tr: "rica etmek" },
  { eng: "require", tr: "gerektirmek" },
  { eng: "rescue", tr: "kurtarmak" },
  { eng: "research", tr: "araştırma" },
  { eng: "respect", tr: "saygı göstermek" },
  { eng: "responsible", tr: "sorumlu" },
  { eng: "result", tr: "sonuç" },
  { eng: "retire", tr: "emekli olmak" },
  { eng: "return", tr: "geri dönmek" },
  { eng: "reveal", tr: "ortaya çıkarmak" },
  { eng: "revenge", tr: "intikam" },
  { eng: "review", tr: "inceleme" },
  { eng: "reward", tr: "ödül" },
  { eng: "risk", tr: "risk" },
  { eng: "rob", tr: "soymak" },
  { eng: "romantic", tr: "romantik" },
  { eng: "rough", tr: "sert" },
  { eng: "rude", tr: "kaba" },
  { eng: "ruin", tr: "mahvetmek" },
  { eng: "rural", tr: "kırsal" },
  { eng: "satisfy", tr: "tatmin etmek" },
  { eng: "save", tr: "kurtarmak" },
  { eng: "schedule", tr: "program" },
  { eng: "scientist", tr: "bilim insanı" },
  { eng: "search", tr: "aramak" },
  { eng: "secret", tr: "gizli" },
  { eng: "section", tr: "bölüm" },
  { eng: "secure", tr: "güvenli" },
  { eng: "select", tr: "seçmek" },
  { eng: "selfish", tr: "bencil" },
  { eng: "sense", tr: "his" },
  { eng: "separate", tr: "ayırmak" },
  { eng: "serious", tr: "ciddi" },
  { eng: "serve", tr: "hizmet etmek" },
  { eng: "settle", tr: "yerleşmek" },
  { eng: "several", tr: "birkaç" },
  { eng: "shadow", tr: "gölge" },
  { eng: "shallow", tr: "sığ" },
  { eng: "share", tr: "paylaşmak" },
  { eng: "sharp", tr: "keskin" },
  { eng: "shelter", tr: "barınak" },
  { eng: "shift", tr: "değişim" },
  { eng: "shine", tr: "parlamak" },
  { eng: "shoot", tr: "ateş etmek" },
  { eng: "signal", tr: "sinyal" },
  { eng: "silent", tr: "sessiz" },
  { eng: "similar", tr: "benzer" },
  { eng: "sincere", tr: "samimi" },
  { eng: "single", tr: "bekar" },
  { eng: "situation", tr: "durum" },
  { eng: "skill", tr: "beceri" },
  { eng: "slave", tr: "köle" },
  { eng: "society", tr: "toplum" },
  { eng: "solution", tr: "çözüm" },
  { eng: "source", tr: "kaynak" },
  { eng: "specific", tr: "belirli" },
  { eng: "speech", tr: "konuşma" },
  { eng: "spend", tr: "harcamak" },
  { eng: "spirit", tr: "ruh" },
  { eng: "spread", tr: "yaymak" },
  { eng: "stage", tr: "sahne" },
  { eng: "standard", tr: "standart" },
  { eng: "state", tr: "durum" },
  { eng: "steady", tr: "istikrarlı" },
  { eng: "steal", tr: "çalmak" },
  { eng: "steel", tr: "çelik" },
  { eng: "step", tr: "adım" },
  { eng: "strange", tr: "garip" },
  { eng: "strategy", tr: "strateji" },
  { eng: "strength", tr: "güç" },
  { eng: "stress", tr: "stres" },
  { eng: "stretch", tr: "esnetmek" },
  { eng: "strike", tr: "vurmak" },
  { eng: "structure", tr: "yapı" },
  { eng: "struggle", tr: "mücadele etmek" },
  { eng: "suffer", tr: "acı çekmek" },
  { eng: "suggest", tr: "önermek" },
  { eng: "support", tr: "desteklemek" },
  { eng: "suppose", tr: "varsaymak" },
  { eng: "surface", tr: "yüzey" },
  { eng: "survive", tr: "hayatta kalmak" },
  { eng: "suspect", tr: "şüphelenmek" },
  { eng: "swear", tr: "yemin etmek" },
  { eng: "symbol", tr: "sembol" },
  { eng: "system", tr: "sistem" }
];