const ingKaliplar = [
  // Selamlama ve Vedalaşma
  {eng:"How's it going?", tr:"Nasıl gidiyor?"},
  {eng:"What's up?", tr:"Ne var ne yok?"},
  {eng:"Long time no see!", tr:"Çok uzun zaman oldu!"},
  {eng:"Nice to meet you!", tr:"Tanıştığıma memnun oldum!"},
  {eng:"Take care!", tr:"Kendine iyi bak!"},
  {eng:"See you around!", tr:"Görüşürüz!"},
  {eng:"Have a good one!", tr:"İyi günler!"},
  {eng:"Catch you later!", tr:"Sonra görüşürüz!"},

  // Anlamak / Anlamadığında
  {eng:"I see what you mean.", tr:"Ne demek istediğini anlıyorum."},
  {eng:"Could you say that again?", tr:"Bunu tekrar söyler misiniz?"},
  {eng:"Could you speak more slowly, please?", tr:"Lütfen daha yavaş konuşabilir misiniz?"},
  {eng:"What do you mean by that?", tr:"Bununla ne demek istiyorsunuz?"},
  {eng:"I'm not sure I follow.", tr:"Tam olarak anlayamadım."},
  {eng:"Can you give me an example?", tr:"Bir örnek verebilir misiniz?"},
  {eng:"That makes sense.", tr:"Bu mantıklı."},
  {eng:"Got it!", tr:"Anladım!"},
  {eng:"I had no idea.", tr:"Hiç bilmiyordum."},

  // Fikir Belirtme
  {eng:"In my opinion,", tr:"Benim görüşüme göre,"},
  {eng:"As far as I know,", tr:"Bildiğim kadarıyla,"},
  {eng:"To be honest,", tr:"Dürüst olmak gerekirse,"},
  {eng:"I strongly believe that...", tr:"Güçlü bir şekilde inanıyorum ki..."},
  {eng:"I'm not sure about that.", tr:"Bu konuda emin değilim."},
  {eng:"I think it depends.", tr:"Bence duruma göre değişir."},
  {eng:"That's a good point.", tr:"Bu iyi bir nokta."},
  {eng:"I totally agree.", tr:"Tamamen katılıyorum."},
  {eng:"I couldn't agree more.", tr:"Daha fazla katılamam."},
  {eng:"I disagree with that.", tr:"Buna katılmıyorum."},
  {eng:"I see it differently.", tr:"Bunu farklı görüyorum."},
  {eng:"You have a point, but...", tr:"Bir noktanız var, ama..."},

  // Rica / İsteme
  {eng:"Could you help me with this?", tr:"Bu konuda bana yardım eder misiniz?"},
  {eng:"Would you mind opening the window?", tr:"Pencereyi açar mısınız?"},
  {eng:"Do you mind if I sit here?", tr:"Buraya oturursam sakıncası var mı?"},
  {eng:"Is it okay if I leave early?", tr:"Erken ayrılsam uygun olur mu?"},
  {eng:"May I ask you something?", tr:"Size bir şey sorabilir miyim?"},
  {eng:"Could I borrow your pen?", tr:"Kalemini ödünç alabilir miyim?"},
  {eng:"Would you do me a favor?", tr:"Bana bir iyilik yapar mısın?"},
  {eng:"Can I get some help here?", tr:"Burada biraz yardım alabilir miyim?"},

  // Teklif / Öneri
  {eng:"Why don't we try this?", tr:"Bunu neden denemiyoruz?"},
  {eng:"How about meeting tomorrow?", tr:"Yarın buluşmaya ne dersin?"},
  {eng:"What if we change the plan?", tr:"Planı değiştirirsek ne olur?"},
  {eng:"Let's give it a shot.", tr:"Deneyelim."},
  {eng:"It might be worth trying.", tr:"Denemek değer olabilir."},
  {eng:"You should give it a try.", tr:"Bir denemelisin."},
  {eng:"Have you considered...?", tr:"...düşündünüz mü?"},
  {eng:"I suggest we start over.", tr:"Baştan başlamamızı öneriyorum."},

  // Zaman İfadeleri
  {eng:"in the meantime", tr:"bu arada / o süre zarfında"},
  {eng:"sooner or later", tr:"er ya da geç"},
  {eng:"from time to time", tr:"zaman zaman"},
  {eng:"once in a while", tr:"ara sıra"},
  {eng:"right away", tr:"hemen şimdi"},
  {eng:"all of a sudden", tr:"aniden / birdenbire"},
  {eng:"at the last minute", tr:"son dakikada"},
  {eng:"ahead of schedule", tr:"programın önünde / erken"},
  {eng:"behind schedule", tr:"programın gerisinde / gecikmeli"},

  // Neden / Sonuç
  {eng:"As a result,", tr:"Sonuç olarak,"},
  {eng:"Due to this,", tr:"Bundan dolayı,"},
  {eng:"Because of that,", tr:"Bunun nedeniyle,"},
  {eng:"That's why...", tr:"Bu yüzden..."},
  {eng:"Therefore,", tr:"Bu nedenle,"},
  {eng:"It led to...", tr:"Bu... yol açtı."},
  {eng:"This caused...", tr:"Bu... neden oldu."},
  {eng:"Thanks to this,", tr:"Bunun sayesinde,"},

  // Karşılaştırma
  {eng:"compared to", tr:"ile karşılaştırıldığında"},
  {eng:"on the other hand,", tr:"öte yandan,"},
  {eng:"in contrast,", tr:"buna karşın,"},
  {eng:"similarly,", tr:"benzer şekilde,"},
  {eng:"just like", tr:"tıpkı ... gibi"},
  {eng:"unlike", tr:"... den farklı olarak"},
  {eng:"both ... and ...", tr:"hem ... hem de ..."},
  {eng:"either ... or ...", tr:"ya ... ya da ..."},
  {eng:"neither ... nor ...", tr:"ne ... ne de ..."},

  // Bağlaçlar / Geçiş İfadeleri
  {eng:"First of all,", tr:"Her şeyden önce,"},
  {eng:"To begin with,", tr:"Başlamak gerekirse,"},
  {eng:"In addition,", tr:"Bunun yanı sıra,"},
  {eng:"Furthermore,", tr:"Üstelik,"},
  {eng:"On top of that,", tr:"Bunun üstüne,"},
  {eng:"Last but not least,", tr:"Son olarak ama az önemli değil,"},
  {eng:"To sum up,", tr:"Özetlemek gerekirse,"},
  {eng:"In conclusion,", tr:"Sonuç olarak,"},
  {eng:"To put it simply,", tr:"Basitçe söylemek gerekirse,"},

  // Duygu / Tepki
  {eng:"That's amazing!", tr:"Bu inanılmaz!"},
  {eng:"I can't believe it!", tr:"İnanamıyorum!"},
  {eng:"What a surprise!", tr:"Ne sürpriz!"},
  {eng:"I'm so relieved.", tr:"Çok rahatladım."},
  {eng:"I'm really disappointed.", tr:"Gerçekten hayal kırıklığına uğradım."},
  {eng:"I'm looking forward to it.", tr:"Bunu dört gözle bekliyorum."},
  {eng:"I'm thrilled about this.", tr:"Bu konuda çok heyecanlıyım."},
  {eng:"I'm a bit worried.", tr:"Biraz endişeleniyorum."},
  {eng:"I feel much better now.", tr:"Şimdi çok daha iyi hissediyorum."},
  {eng:"That really bothers me.", tr:"Bu gerçekten beni rahatsız ediyor."},

  // Telefon / E-posta Kalıpları
  {eng:"I'm calling about...", tr:"... hakkında arıyorum."},
  {eng:"Could I speak to...?", tr:"... ile konuşabilir miyim?"},
  {eng:"I'll get back to you.", tr:"Sana geri döneceğim."},
  {eng:"Please find attached...", tr:"Ekte ... bulacaksınız."},
  {eng:"I'm writing to inform you that...", tr:"... hakkında sizi bilgilendirmek için yazıyorum."},
  {eng:"I look forward to hearing from you.", tr:"Yanıtınızı bekliyorum."},
  {eng:"Thank you for your quick response.", tr:"Hızlı yanıtınız için teşekkür ederim."},
  {eng:"As per our conversation,", tr:"Konuşmamıza göre,"},

  // Alışveriş / Restoran
  {eng:"How much does this cost?", tr:"Bu ne kadar?"},
  {eng:"Can I try this on?", tr:"Bunu deneyebilir miyim?"},
  {eng:"Do you have this in a different size?", tr:"Bunu farklı bir bedende var mı?"},
  {eng:"I'll take this one.", tr:"Bunu alacağım."},
  {eng:"Can I get the bill, please?", tr:"Hesabı alabilir miyim?"},
  {eng:"Is service included?", tr:"Servis dahil mi?"},
  {eng:"I'd like to order...", tr:"... sipariş etmek istiyorum."},
  {eng:"What do you recommend?", tr:"Ne önerirsiniz?"},
  {eng:"I'm allergic to...", tr:"... alerjim var."},
  {eng:"Can I have this to go?", tr:"Bunu paket olarak alabilir miyim?"},

  // Seyahat
  {eng:"Where is the nearest subway station?", tr:"En yakın metro istasyonu nerede?"},
  {eng:"How long does it take to get there?", tr:"Oraya gitmek ne kadar sürer?"},
  {eng:"Can you take me to this address?", tr:"Beni bu adrese götürür müsünüz?"},
  {eng:"I'd like to check in.", tr:"Check-in yapmak istiyorum."},
  {eng:"I have a reservation.", tr:"Rezervasyonum var."},
  {eng:"Is breakfast included?", tr:"Kahvaltı dahil mi?"},
  {eng:"What time is check-out?", tr:"Check-out saati ne zaman?"},
  {eng:"Could I have a wake-up call at 7?", tr:"7'de uyandırma servisi isteyebilir miyim?"},

  // İş / Toplantı
  {eng:"Let's get down to business.", tr:"İşe geçelim."},
  {eng:"Can we go over the agenda?", tr:"Gündemi gözden geçirebilir miyiz?"},
  {eng:"I'd like to raise a point.", tr:"Bir konuya değinmek istiyorum."},
  {eng:"Could we schedule a meeting?", tr:"Bir toplantı planlayabilir miyiz?"},
  {eng:"Let's touch base later.", tr:"Daha sonra iletişime geçelim."},
  {eng:"I'll follow up on this.", tr:"Bunu takip edeceğim."},
  {eng:"We're on the same page.", tr:"Aynı fikirde / sayfadayız."},
  {eng:"Can we wrap this up?", tr:"Bunu bitirebilir miyiz?"},
  {eng:"Let's table this for now.", tr:"Bunu şimdilik erteleyelim."},

  // Yaygın Deyimler
  {eng:"It's up to you.", tr:"Bu sana bağlı."},
  {eng:"Never mind.", tr:"Boşver."},
  {eng:"It doesn't matter.", tr:"Önemi yok."},
  {eng:"That's not a big deal.", tr:"Bu büyük bir mesele değil."},
  {eng:"It's now or never.", tr:"Ya şimdi ya hiç."},
  {eng:"Better late than never.", tr:"Hiç yoktan geç olsun."},
  {eng:"It's easier said than done.", tr:"Söylemesi yapmaktan kolay."},
  {eng:"That's the last straw.", tr:"Bu son damla."},
  {eng:"We'll cross that bridge when we come to it.", tr:"O köprüye gelince geçeriz."},
  {eng:"Let's not jump to conclusions.", tr:"Aceleyle sonuca atlayalım."},
  {eng:"It's worth it.", tr:"Değer."},
  {eng:"It's not worth it.", tr:"Değmez."},
  {eng:"That's beside the point.", tr:"Bu konunun dışında."},
  {eng:"What's the point?", tr:"Ne anlamı var?"},
  {eng:"At the end of the day,", tr:"Günün sonunda,"},
  {eng:"You never know.", tr:"Hiç bilinmez."},
  {eng:"It goes without saying.", tr:"Bu söylemeye gerek yok."},
  {eng:"Keep it up!", tr:"Devam et / Böyle devam!"},
  {eng:"Well done!", tr:"Aferin!"},
  {eng:"Good luck with that!", tr:"İyi şanslar!"},
];