const sayilar = [
 { sayi: 0, isp: "cero", tr: "sıfır" },
  { sayi: 1, isp: "uno", tr: "bir" },
  { sayi: 2, isp: "dos", tr: "iki" },
  { sayi: 3, isp: "tres", tr: "üç" },
  { sayi: 4, isp: "cuatro", tr: "dört" },
  { sayi: 5, isp: "cinco", tr: "beş" },
  { sayi: 6, isp: "seis", tr: "altı" },
  { sayi: 7, isp: "siete", tr: "yedi" },
  { sayi: 8, isp: "ocho", tr: "sekiz" },
  { sayi: 9, isp: "nueve", tr: "dokuz" },
  { sayi: 10, isp: "diez", tr: "on" },
  { sayi: 11, isp: "once", tr: "on bir" },
  { sayi: 12, isp: "doce", tr: "on iki" },
  { sayi: 13, isp: "trece", tr: "on üç" },
  { sayi: 14, isp: "catorce", tr: "on dört" },
  { sayi: 15, isp: "quince", tr: "on beş" },
  { sayi: 16, isp: "dieciséis", tr: "on altı" },
  { sayi: 17, isp: "diecisiete", tr: "on yedi" },
  { sayi: 18, isp: "dieciocho", tr: "on sekiz" },
  { sayi: 19, isp: "diecinueve", tr: "on dokuz" },
  { sayi: 20, isp: "veinte", tr: "yirmi" },
  { sayi: 21, isp: "veintiuno", tr: "yirmi bir" },
  { sayi: 22, isp: "veintidós", tr: "yirmi iki" },
  { sayi: 23, isp: "veintitrés", tr: "yirmi üç" },
  { sayi: 24, isp: "veinticuatro", tr: "yirmi dört" },
  { sayi: 25, isp: "veinticinco", tr: "yirmi beş" },
  { sayi: 26, isp: "veintiséis", tr: "yirmi altı" },
  { sayi: 27, isp: "veintisiete", tr: "yirmi yedi" },
  { sayi: 28, isp: "veintiocho", tr: "yirmi sekiz" },
  { sayi: 29, isp: "veintinueve", tr: "yirmi dokuz" },
  { sayi: 30, isp: "treinta", tr: "otuz" },
  { sayi: 31, isp: "treinta y uno", tr: "otuz bir" },
  { sayi: 32, isp: "treinta y dos", tr: "otuz iki" },
  { sayi: 33, isp: "treinta y tres", tr: "otuz üç" },
  { sayi: 34, isp: "treinta y cuatro", tr: "otuz dört" },
  { sayi: 35, isp: "treinta y cinco", tr: "otuz beş" },
  { sayi: 36, isp: "treinta y seis", tr: "otuz altı" },
  { sayi: 37, isp: "treinta y siete", tr: "otuz yedi" },
  { sayi: 38, isp: "treinta y ocho", tr: "otuz sekiz" },
  { sayi: 39, isp: "treinta y nueve", tr: "otuz dokuz" },
  { sayi: 40, isp: "cuarenta", tr: "kırk" },
  { sayi: 41, isp: "cuarenta y uno", tr: "kırk bir" },
  { sayi: 42, isp: "cuarenta y dos", tr: "kırk iki" },
  { sayi: 43, isp: "cuarenta y tres", tr: "kırk üç" },
  { sayi: 44, isp: "cuarenta y cuatro", tr: "kırk dört" },
  { sayi: 45, isp: "cuarenta y cinco", tr: "kırk beş" },
  { sayi: 46, isp: "cuarenta y seis", tr: "kırk altı" },
  { sayi: 47, isp: "cuarenta y siete", tr: "kırk yedi" },
  { sayi: 48, isp: "cuarenta y ocho", tr: "kırk sekiz" },
  { sayi: 49, isp: "cuarenta y nueve", tr: "kırk dokuz" },
  { sayi: 50, isp: "cincuenta", tr: "elli" },
  { sayi: 51, isp: "cincuenta y uno", tr: "elli bir" },
  { sayi: 52, isp: "cincuenta y dos", tr: "elli iki" },
  { sayi: 53, isp: "cincuenta y tres", tr: "elli üç" },
  { sayi: 54, isp: "cincuenta y cuatro", tr: "elli dört" },
  { sayi: 55, isp: "cincuenta y cinco", tr: "elli beş" },
  { sayi: 56, isp: "cincuenta y seis", tr: "elli altı" },
  { sayi: 57, isp: "cincuenta y siete", tr: "elli yedi" },
  { sayi: 58, isp: "cincuenta y ocho", tr: "elli sekiz" },
  { sayi: 59, isp: "cincuenta y nueve", tr: "elli dokuz" },
  { sayi: 60, isp: "sesenta", tr: "altmış" },
  { sayi: 61, isp: "sesenta y uno", tr: "altmış bir" },
  { sayi: 62, isp: "sesenta y dos", tr: "altmış iki" },
  { sayi: 63, isp: "sesenta y tres", tr: "altmış üç" },
  { sayi: 64, isp: "sesenta y cuatro", tr: "altmış dört" },
  { sayi: 65, isp: "sesenta y cinco", tr: "altmış beş" },
  { sayi: 66, isp: "sesenta y seis", tr: "altmış altı" },
  { sayi: 67, isp: "sesenta y siete", tr: "altmış yedi" },
  { sayi: 68, isp: "sesenta y ocho", tr: "altmış sekiz" },
  { sayi: 69, isp: "sesenta y nueve", tr: "altmış dokuz" },
  { sayi: 70, isp: "setenta", tr: "yetmiş" },
  { sayi: 71, isp: "setenta y uno", tr: "yetmiş bir" },
  { sayi: 72, isp: "setenta y dos", tr: "yetmiş iki" },
  { sayi: 73, isp: "setenta y tres", tr: "yetmiş üç" },
  { sayi: 74, isp: "setenta y cuatro", tr: "yetmiş dört" },
  { sayi: 75, isp: "setenta y cinco", tr: "yetmiş beş" },
  { sayi: 76, isp: "setenta y seis", tr: "yetmiş altı" },
  { sayi: 77, isp: "setenta y siete", tr: "yetmiş yedi" },
  { sayi: 78, isp: "setenta y ocho", tr: "yetmiş sekiz" },
  { sayi: 79, isp: "setenta y nueve", tr: "yetmiş dokuz" },
  { sayi: 80, isp: "ochenta", tr: "seksen" },
  { sayi: 81, isp: "ochenta y uno", tr: "seksen bir" },
  { sayi: 82, isp: "ochenta y dos", tr: "seksen iki" },
  { sayi: 83, isp: "ochenta y tres", tr: "seksen üç" },
  { sayi: 84, isp: "ochenta y cuatro", tr: "seksen dört" },
  { sayi: 85, isp: "ochenta y cinco", tr: "seksen beş" },
  { sayi: 86, isp: "ochenta y seis", tr: "seksen altı" },
  { sayi: 87, isp: "ochenta y siete", tr: "seksen yedi" },
  { sayi: 88, isp: "ochenta y ocho", tr: "seksen sekiz" },
  { sayi: 89, isp: "ochenta y nueve", tr: "seksen dokuz" },
  { sayi: 90, isp: "noventa", tr: "doksan" },
  { sayi: 91, isp: "noventa y uno", tr: "doksan bir" },
  { sayi: 92, isp: "noventa y dos", tr: "doksan iki" },
  { sayi: 93, isp: "noventa y tres", tr: "doksan üç" },
  { sayi: 94, isp: "noventa y cuatro", tr: "doksan dört" },
  { sayi: 95, isp: "noventa y cinco", tr: "doksan beş" },
  { sayi: 96, isp: "noventa y seis", tr: "doksan altı" },
  { sayi: 97, isp: "noventa y siete", tr: "doksan yedi" },
  { sayi: 98, isp: "noventa y ocho", tr: "doksan sekiz" },
  { sayi: 99, isp: "noventa y nueve", tr: "doksan dokuz" },
  { sayi: 100, isp: "cien", tr: "yüz" },
   { sayi: 101, isp: "ciento uno", tr: "yüz bir" },
  { sayi: 102, isp: "ciento dos", tr: "yüz iki" },
  { sayi: 103, isp: "ciento tres", tr: "yüz üç" },
  { sayi: 104, isp: "ciento cuatro", tr: "yüz dört" },
  { sayi: 105, isp: "ciento cinco", tr: "yüz beş" },
  { sayi: 106, isp: "ciento seis", tr: "yüz altı" },
  { sayi: 107, isp: "ciento siete", tr: "yüz yedi" },
  { sayi: 108, isp: "ciento ocho", tr: "yüz sekiz" },
  { sayi: 109, isp: "ciento nueve", tr: "yüz dokuz" },
  { sayi: 110, isp: "ciento diez", tr: "yüz on" },
  { sayi: 111, isp: "ciento once", tr: "yüz on bir" },
  { sayi: 112, isp: "ciento doce", tr: "yüz on iki" },
  { sayi: 113, isp: "ciento trece", tr: "yüz on üç" },
  { sayi: 114, isp: "ciento catorce", tr: "yüz on dört" },
  { sayi: 115, isp: "ciento quince", tr: "yüz on beş" },
  { sayi: 116, isp: "ciento dieciséis", tr: "yüz on altı" },
  { sayi: 117, isp: "ciento diecisiete", tr: "yüz on yedi" },
  { sayi: 118, isp: "ciento dieciocho", tr: "yüz on sekiz" },
  { sayi: 119, isp: "ciento diecinueve", tr: "yüz on dokuz" },
  { sayi: 120, isp: "ciento veinte", tr: "yüz yirmi" },
  { sayi: 121, isp: "ciento veintiuno", tr: "yüz yirmi bir" },
  { sayi: 122, isp: "ciento veintidós", tr: "yüz yirmi iki" },
  { sayi: 123, isp: "ciento veintitrés", tr: "yüz yirmi üç" },
  { sayi: 124, isp: "ciento veinticuatro", tr: "yüz yirmi dört" },
  { sayi: 125, isp: "ciento veinticinco", tr: "yüz yirmi beş" },
  { sayi: 126, isp: "ciento veintiséis", tr: "yüz yirmi altı" },
  { sayi: 127, isp: "ciento veintisiete", tr: "yüz yirmi yedi" },
  { sayi: 128, isp: "ciento veintiocho", tr: "yüz yirmi sekiz" },
  { sayi: 129, isp: "ciento veintinueve", tr: "yüz yirmi dokuz" },
  { sayi: 130, isp: "ciento treinta", tr: "yüz otuz" },
  { sayi: 131, isp: "ciento treinta y uno", tr: "yüz otuz bir" },
  { sayi: 132, isp: "ciento treinta y dos", tr: "yüz otuz iki" },
  { sayi: 133, isp: "ciento treinta y tres", tr: "yüz otuz üç" },
  { sayi: 134, isp: "ciento treinta y cuatro", tr: "yüz otuz dört" },
  { sayi: 135, isp: "ciento treinta y cinco", tr: "yüz otuz beş" },
  { sayi: 136, isp: "ciento treinta y seis", tr: "yüz otuz altı" },
  { sayi: 137, isp: "ciento treinta y siete", tr: "yüz otuz yedi" },
  { sayi: 138, isp: "ciento treinta y ocho", tr: "yüz otuz sekiz" },
  { sayi: 139, isp: "ciento treinta y nueve", tr: "yüz otuz dokuz" },
  { sayi: 140, isp: "ciento cuarenta", tr: "yüz kırk" },
  { sayi: 141, isp: "ciento cuarenta y uno", tr: "yüz kırk bir" },
  { sayi: 142, isp: "ciento cuarenta y dos", tr: "yüz kırk iki" },
  { sayi: 143, isp: "ciento cuarenta y tres", tr: "yüz kırk üç" },
  { sayi: 144, isp: "ciento cuarenta y cuatro", tr: "yüz kırk dört" },
  { sayi: 145, isp: "ciento cuarenta y cinco", tr: "yüz kırk beş" },
  { sayi: 146, isp: "ciento cuarenta y seis", tr: "yüz kırk altı" },
  { sayi: 147, isp: "ciento cuarenta y siete", tr: "yüz kırk yedi" },
  { sayi: 148, isp: "ciento cuarenta y ocho", tr: "yüz kırk sekiz" },
  { sayi: 149, isp: "ciento cuarenta y nueve", tr: "yüz kırk dokuz" },
  { sayi: 150, isp: "ciento cincuenta", tr: "yüz elli" },
  { sayi: 160, isp: "ciento sesenta", tr: "yüz altmış" },
  { sayi: 170, isp: "ciento setenta", tr: "yüz yetmiş" },
  { sayi: 180, isp: "ciento ochenta", tr: "yüz seksen" },
  { sayi: 190, isp: "ciento noventa", tr: "yüz doksan" },
  { sayi: 200, isp: "doscientos", tr: "iki yüz" },
  { sayi: 201, isp: "doscientos uno", tr: "iki yüz bir" },
  { sayi: 202, isp: "doscientos dos", tr: "iki yüz iki" },
  { sayi: 203, isp: "doscientos tres", tr: "iki yüz üç" },
  { sayi: 204, isp: "doscientos cuatro", tr: "iki yüz dört" },
  { sayi: 205, isp: "doscientos cinco", tr: "iki yüz beş" },
  { sayi: 206, isp: "doscientos seis", tr: "iki yüz altı" },
  { sayi: 207, isp: "doscientos siete", tr: "iki yüz yedi" },
  { sayi: 208, isp: "doscientos ocho", tr: "iki yüz sekiz" },
  { sayi: 209, isp: "doscientos nueve", tr: "iki yüz dokuz" },
  { sayi: 210, isp: "doscientos diez", tr: "iki yüz on" },
  { sayi: 211, isp: "doscientos once", tr: "iki yüz on bir" },
  { sayi: 212, isp: "doscientos doce", tr: "iki yüz on iki" },
  { sayi: 213, isp: "doscientos trece", tr: "iki yüz on üç" },
  { sayi: 214, isp: "doscientos catorce", tr: "iki yüz on dört" },
  { sayi: 215, isp: "doscientos quince", tr: "iki yüz on beş" },
  { sayi: 216, isp: "doscientos dieciséis", tr: "iki yüz on altı" },
  { sayi: 217, isp: "doscientos diecisiete", tr: "iki yüz on yedi" },
  { sayi: 218, isp: "doscientos dieciocho", tr: "iki yüz on sekiz" },
  { sayi: 219, isp: "doscientos diecinueve", tr: "iki yüz on dokuz" },
  { sayi: 220, isp: "doscientos veinte", tr: "iki yüz yirmi" },
  { sayi: 221, isp: "doscientos veintiuno", tr: "iki yüz yirmi bir" },
  { sayi: 222, isp: "doscientos veintidós", tr: "iki yüz yirmi iki" },
  { sayi: 223, isp: "doscientos veintitrés", tr: "iki yüz yirmi üç" },
  { sayi: 224, isp: "doscientos veinticuatro", tr: "iki yüz yirmi dört" },
  { sayi: 225, isp: "doscientos veinticinco", tr: "iki yüz yirmi beş" },
  { sayi: 226, isp: "doscientos veintiséis", tr: "iki yüz yirmi altı" },
  { sayi: 227, isp: "doscientos veintisiete", tr: "iki yüz yirmi yedi" },
  { sayi: 228, isp: "doscientos veintiocho", tr: "iki yüz yirmi sekiz" },
  { sayi: 229, isp: "doscientos veintinueve", tr: "iki yüz yirmi dokuz" },
  { sayi: 230, isp: "doscientos treinta", tr: "iki yüz otuz" },
  { sayi: 231, isp: "doscientos treinta y uno", tr: "iki yüz otuz bir" },
  { sayi: 232, isp: "doscientos treinta y dos", tr: "iki yüz otuz iki" },
  { sayi: 233, isp: "doscientos treinta y tres", tr: "iki yüz otuz üç" },
  { sayi: 234, isp: "doscientos treinta y cuatro", tr: "iki yüz otuz dört" },
  { sayi: 235, isp: "doscientos treinta y cinco", tr: "iki yüz otuz beş" },
  { sayi: 236, isp: "doscientos treinta y seis", tr: "iki yüz otuz altı" },
  { sayi: 237, isp: "doscientos treinta y siete", tr: "iki yüz otuz yedi" },
  { sayi: 238, isp: "doscientos treinta y ocho", tr: "iki yüz otuz sekiz" },
  { sayi: 239, isp: "doscientos treinta y nueve", tr: "iki yüz otuz dokuz" },
  { sayi: 240, isp: "doscientos cuarenta", tr: "iki yüz kırk" },
  { sayi: 250, isp: "doscientos cincuenta", tr: "iki yüz elli" },
  { sayi: 260, isp: "doscientos sesenta", tr: "iki yüz altmış" },
  { sayi: 270, isp: "doscientos setenta", tr: "iki yüz yetmiş" },
  { sayi: 280, isp: "doscientos ochenta", tr: "iki yüz seksen" },
  { sayi: 290, isp: "doscientos noventa", tr: "iki yüz doksan" },
  { sayi: 300, isp: "trescientos", tr: "üç yüz" },
  { sayi: 300, isp: "trescientos", tr: "üç yüz" },
  { sayi: 400, isp: "cuatrocientos", tr: "dört yüz" },
  { sayi: 500, isp: "quinientos", tr: "beş yüz" },
  { sayi: 600, isp: "seiscientos", tr: "altı yüz" },
  { sayi: 700, isp: "setecientos", tr: "yedi yüz" },
  { sayi: 800, isp: "ochocientos", tr: "sekiz yüz" },
  { sayi: 900, isp: "novecientos", tr: "dokuz yüz" },
  { sayi: 1000, isp: "mil", tr: "bin" },
  { sayi: 2000, isp: "dos mil", tr: "iki bin" },
  { sayi: 1000000, isp: "un millón", tr: "bir milyon" }
];